### ISSUE TITLE
Android v7a permissions error

### ISSUE THREAD

**Issue by zach-morris** [zach-morris/plugin.program.iagl#1]
When trying to use IAGL on Kodi v18 and android v7a, there's some sort of permissions error that prevents Kodi from being able to write to the userdata cache folder.  As a result, the only option currently is to set an alternate download location (that the user has write access to).  Still trying to figure this one out.

**Comment by drinfernoo** [comment]
Honestly, I would prefer this. For Kodi tinkering, my most common frustration is losing ROM-related files during a Kodi wipe.

**Comment by Philps** [comment]
I could do some arm7 debugging (FireTV Gen2) if required.

**Comment by zach-morris** [comment]
This should work now.  Closing.
