### ISSUE TITLE
Search option(Random search)

### ISSUE THREAD

**Issue by NerdFlix** [zach-morris/plugin.program.iagl#10]
Hi Zach,
my bad, I forgot to test this **closed** issue after the last update, I've tested it now and the issue is that no list is returned by both search option and random play, no matter what filter or tag(title) you make the search. Windows 10 and kodi 18 Alpha 3

Here is my log(unfortunately, it doesn't give any clue about what's wrong):
https://pastebin.com/xUNddapm

Thanks in advance.

**Comment by zach-morris** [comment]
I don't see the appropriate debug info in the log.  Both are working for me.  As an example, [here's](https://pastebin.com/8nERHwDk) a search.

**Comment by NerdFlix** [comment]
Holy sh***, I'm stupid :), I"ll use git from now on, the addon is working fine after update.

Sorry again and thanks for your addon.

**Comment by zach-morris** [comment]
No worries - I haven't pushed the update to the repository, so the change isn't quite live yet either.  Thanks for testing
