### ISSUE TITLE
applaunch.sh doesn't work the way I expected

### ISSUE THREAD

**Issue by Cyber1000** [zach-morris/plugin.program.iagl#100]
Perhaps it's my setup (raspbian), but following happens, when I activate the "kodi stop" in iagl-setup:
- Starting a game
- applaunch.sh gehts started (with iagl plugin, which runs as kodi)
- kodi is killed within the script
- the script itself is killed immediately (before starting retroarch and before starting kodi again)
- screen is black, nothing happens

I've written my own script (see feature request #99 ), so it works for me now. Just wanted to know if anything (preferable on a "normal" linux, not android or libreelec) is experiencing the same issue.

**Comment by zach-morris** [comment]
Hmm.  I think this script works on Linux.  Not sure why the script would exit/be killed before running the retroarch command.  Do you have a copy of your script I can see?

**Comment by zach-morris** [comment]
I've updated both applaunch (exit kodi) and apppause (pause kodi) scripts.  If possible please try the latest master on git to see if the issue is resolved
