### ISSUE TITLE
Feature Request: Make libretro path configurable

### ISSUE THREAD

**Issue by Cyber1000** [zach-morris/plugin.program.iagl#101]
- libretro is expected on /usr/lib/libretro, on my raspbian it's /usr/lib/arm-linux-gnueabihf/libretro, make this path configurable
- As workaround I've made a symlink and it works for me

**Comment by zach-morris** [comment]
Thanks.  I think this commit will fix that.  [This line ](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/lib/main.py#L135) attempts to find the libretro path automagically based on all the various linux flavors.

**Comment by zach-morris** [comment]
Closing this issue with the update from IAGL 2.1.2.  If the issue persists let me know.

**Comment by Reptarsrage** [comment]
I'm still seeing this issue on 2.1.2. On Ubuntu 19.04, Kodi 18.3, the launch command it's using by default is `Sending Launch Command: "/usr/bin/retroarch"  -L /usr/lib/libretro/mgba_libretro.so "/home/me/.kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/game.gba"` (taken from Kodi logs). Is there anyway to change this? My core is located in `/home/me/.config/retroarch/cores` not in `/usr/lib/libretro`

**Comment by Reptarsrage** [comment]
Also a relevant log line was `The Retroarch Core directory could not be found.  Defaulting to /usr/lib/libretro`

**Comment by Reptarsrage** [comment]
debugging it I can see it definitely checks `~/.config/retroarch/cores/snes9x_libretro.so` which exists, and is correct, but for some reason [this if check](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/lib/main.py#L3951) is failing. Maybe there is an issue using relative paths in the `xbmcvfs.exists` method.

**Comment by Reptarsrage** [comment]
I can confirm that changing from the relative path `~/.config/retroarch/cores` to the absolute path `/home/me/.config/retroarch/cores` fixes the problem. I'm opening an issue with the library itself to support relative paths: https://github.com/romanvm/Kodistubs/issues/15

**Comment by Reptarsrage** [comment]
Making this value configurable would resolve the issue until the kodi team can fix the underlying relative paths issue

**Comment by Reptarsrage** [comment]
I'm not familiar with the Kodi/Plugin coding standards. But couldn't you resolve the home path with:
```
from os.path import expanduser
home = expanduser("~")
```

and then use that instead of relative paths?

**Comment by zach-morris** [comment]
OK thanks for this info.  I'll see if I can add a configurable path somehow, or see if expanduser will work.  I try and use Kodi builtin functions whenever possible to ensure compatibility across OS'

**Comment by zach-morris** [comment]
Added some code to expand the user path, if possible please give the latest master in git a try and see if this works for you
