### ISSUE TITLE
Feature Request: Add Retroelec to systems. 

### ISSUE THREAD

**Issue by camatthew** [zach-morris/plugin.program.iagl#102]
Retroelec is a fork for libreelec which has emulators built in. in works for the xu4, rpi 3 and generic (x86(32bit)) systems. you can find it here https://forum.libreelec.tv/thread/302-retroelec-generic-rpi-xu4-emulationstation-retroarch-kodi/?pageNo=1

**Comment by camatthew** [comment]
Added pull request to add retroelec to remix_applaunch.sh 
#104

**Comment by zach-morris** [comment]
Updated slightly differently than suggested, take a look at [this commit](https://github.com/zach-morris/plugin.program.iagl/commit/e14ea422d9fbd0f39fd6434c68a979ef825eddce) and see if it works if possible

**Comment by camatthew** [comment]
Still doesent work

**Comment by camatthew** [comment]
I figured it out everytime /usr/bin/retroarch.sh is referneced and replace it with /usr/bin/retroarch

**Comment by camatthew** [comment]
I tried everything

**Comment by zach-morris** [comment]
OK, thats a bummer.  It should work in theory, the script is pretty simple.  I'll try and test it on my end

**Comment by camatthew** [comment]
I heard this from esclade. When showing the launch commands for one of the cores

> Don't use -L, it's already used in the script. The first argument should be the core.

**Comment by zach-morris** [comment]
OK, i see that now.  The two have to be split up unfortunately since they now use different launch methods

**Comment by camatthew** [comment]
Any news?

**Comment by camatthew** [comment]
anything?

**Comment by drinfernoo** [comment]
@camatthew You should probably be patient. Whenever there's movement in this issue, it likely means "something" happened.

**Comment by zach-morris** [comment]
The last commit should make this work.  Can you download from master and see if this works for you?

**Comment by camatthew** [comment]
yes

**Comment by camatthew** [comment]
I will do it asap

**Comment by camatthew** [comment]
it didnt work very well it works better on android/

**Comment by zach-morris** [comment]
OK.... I'm not a professional developer or anything, but your response I can imagine is like a developers worst nightmare:  bad review and little information.  So, what exactly isn't working?

**Comment by camatthew** [comment]
not enough  cores from retroelec and glitches from retroarch. I found that android works much better ith all of the cores i need. retroarch doesent have as many cores for retroelec or retroarch buildbot android gives a much better experience. Also i prefer android as that is what i usually have installed.
