### ISSUE TITLE
Bug?: Force Download of a Game if already exitent

### ISSUE THREAD

**Issue by Philps** [zach-morris/plugin.program.iagl#103]
While this option is possible to configure for game launches ( Launch Game, Launch + Download Game, just Download ) + if Game existent overwrite game, it doesnt work when manually downloading a game. it will just skip over it

Example:
- cancelled Game Download after xy%
- re-download, it will state straight away that game has been donwloaded

Workaround:
- manually delete the game via Explorer etc

**Comment by zach-morris** [comment]
Thanks.  I've confirmed this bug.  I'll work on a fix to delete the file being downloaded if cancel is selected.
