### ISSUE TITLE
With new libertro core PLAY! please add Playstation 2 to game list

### ISSUE THREAD

**Issue by Philps** [zach-morris/plugin.program.iagl#107]
With new libertro core PLAY! please add Playstation 2 to game list

**Comment by drinfernoo** [comment]
See this issue: https://github.com/zach-morris/plugin.program.iagl/issues/38

**Comment by lanarainx** [comment]
I don't think it's a good idea if you want to force KODI to render all asset files from a PS2 Game + Not a friendly storage if you're playing on Android TV (say, 3 GB Memory Space required for downloading WWE 2K10 or Midnight Club 3. And a BIOS for Configuration like the System Time)

**Comment by zach-morris** [comment]
I will close this issue, then add it to the other list requests.  I have been playing with Play! and it actually works relatively well on my mac.
