### ISSUE TITLE
Can someone please help me I've been having problems lately

### ISSUE THREAD

**Issue by Fatheroftearsx** [zach-morris/plugin.program.iagl#109]
Okay here goes I'm on a fire stick Pro 4K and certain emulators don't work with retroarch for example N64 Atari 2600 and Super Nintendo and Nintendo DS I don't know what I'm doing wrong please help every time I click to use any ROM it force closes back to the list. Could it be a retroarch problem or is it because of Kodi I'm using leia

**Comment by Fatheroftearsx** [comment]
Also for some reason even though retroarch is linked to Kodi whenever I choose a Super Nintendo game it chooses the rom from the Kodi and not from retroarch even though I downloaded the core

**Comment by drinfernoo** [comment]
For your first comment, that is an issue with RetroArch. IAGL doesn't handle any of the actual *playing* of games.

For your second comment, you need to go through the setup instructions here: https://github.com/zach-morris/plugin.program.iagl/wiki/1.--Setup

**Comment by zach-morris** [comment]
Closing for lack of log.  Reopen a new issue with a log and specifics of the problem if your issue persists
