### ISSUE TITLE
Atari games shows blank screen

### ISSUE THREAD

**Issue by viniciuscordeiro** [zach-morris/plugin.program.iagl#111]
Every Atari games shows blank screen, when I press SELECT + X I can see the game screen and all controls are available. Setup: RPi 3 + libreelec + 8BITDO

**Comment by zach-morris** [comment]
Works for me
<img src="https://i.imgur.com/PkalRG5.png" width="350">

I think the problem isn't an addon problem, but a Kodi Retroplayer problem.  See [here](https://github.com/kodi-game/game.libretro.stella/issues/5).
