### ISSUE TITLE
Force Update

### ISSUE THREAD

**Issue by manurafal** [zach-morris/plugin.program.iagl#115]
How can I force the console update? There are some that I don't have, my friend has 2 of FBA and I only have one.

Thanks.

**Comment by zach-morris** [comment]
FBAlpha list was replaced by FBNeo list.  There's only one list now, but it was renamed and FBNeo is the one that is updated.  You can keep or delete the old list if you want depending on your setup.

**Comment by manurafal** [comment]
How should I do it to update everything?
Where are the list files to delete them?

Thanks.

**Comment by zach-morris** [comment]
The only update is to have the latest version of the addon.  If you want to delete an old list that is no longer maintained, you can either hide it, or uninstall the addon (and select yes when Kodi asks if you want to delete the user data) and then re-install.

**Comment by manurafal** [comment]
ok, thanks a lot.
