### ISSUE TITLE
[Feature Request] Display System in Multi-List Lists

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#116]
That title... Sorry about that 🤣

In any case, that I'd like to see is some label for what system a game belongs to in lists like searches or favorites that could have different versions of the same game, only on different platforms.

**Comment by zach-morris** [comment]
OK, I think i understand this request.  I could either insert the <emu_name> tag or the <emu_description> tag into search/random results if the user has selected more than one list, that seems like the cleanest way to make this work.
