### ISSUE TITLE
Extremly slow download-speed of roms

### ISSUE THREAD

**Issue by Morti90** [zach-morris/plugin.program.iagl#117]
Hi guys,

Does anyone have the experience of a very slow download speed of the game roms.
Its downloading with, i dont know, like 50 kb/s, which is no problem with roms for c64/snes etc. of course, but downloading a rom for ps1 will take me hours.
Is it normal or does anybody have any clue to fix it?

Thanks in advance
Morti

**Comment by zach-morris** [comment]
I do not have this problem, and I'm guessing it's your connection to the archive.

**Comment by Morti90** [comment]
just wanted to let you know that i fixed the problem.
i disconnected from ethernet and connected to wireless and it works.
Dont know why, but anyway :D
