### ISSUE TITLE
Games missing

### ISSUE THREAD

**Issue by ITV4Free** [zach-morris/plugin.program.iagl#120]
The retro libraries are missing games and some have duplicates
Missing games PS ii,Pokemon Crystal
Also can u add hacks,homebrews,ect to each romset
Nes,GB/GBC/GBA/Snes,Genesis thanks

**Comment by zach-morris** [comment]
I think this has already been requested.  Requests go [here](https://github.com/zach-morris/plugin.program.iagl/issues/38).

**Comment by ITV4Free** [comment]
Can u also add NDS rom hacks(Pokemon ones)
