### ISSUE TITLE
update

### ISSUE THREAD

**Issue by ITV4Free** [zach-morris/plugin.program.iagl#123]
Zelda links awakening DX(GBC) is missing
can u add this one thanks

**Comment by ITV4Free** [comment]
Also Links awakening GB is listed 3 times remove 2 of them thanks

**Comment by drinfernoo** [comment]
As mentioned [here](https://github.com/zach-morris/plugin.program.iagl/issues/121#issuecomment-537702794), there is a standing issue for requests.

There's likely a good reason there are three entries for that game as well... as there were indeed releases from NA, JP, and EU. You'll find this with many, many games in IAGL, but that doesn't make them any less valid.

**Comment by zach-morris** [comment]
Yes, when you see duplicates, it's likely you have the setting 'Clean Game Title' enabled.  If you disable that, you will see the entries are different versions, languages, etc.  Not sure why that game isn't listed.  I do see it in the archive, so i will update the game list

**Comment by drinfernoo** [comment]
@zach-morris Would it be possible to have an option to filter lists by region? If I only wanted to see NA games, for example.

**Comment by zach-morris** [comment]
Thats possible using the search function, choose your list(s), then in tag enter the appropriate tag (USA, Europe, etc)

**Comment by ITV4Free** [comment]
Ok thanks it make more sense if versions were hacked/modded

**Comment by ITV4Free** [comment]
Can u add FFvii,Pokemon yellow(nes version)
