### ISSUE TITLE
Enter not working

### ISSUE THREAD

**Issue by gsjv2** [zach-morris/plugin.program.iagl#13]
I am using Leia beta 1.  I can launch a game, however, when I exit that game enter ceases to function in the app.  I can no longer select another game, or select another folder.  Restarting Kodi is the only fix I've found.

**Comment by zach-morris** [comment]
I've upgraded to the Beta, and launching a game with Retroplayer straight up crashes now on OSX.  However, if I choose external launching everything seems to work.  I'm guessing this is an issue in the Beta, but can you provide a debug log?

**Comment by gsjv2** [comment]
Backing all the way out of the addon doesn't work for me.  I'll get you a debug log when I get home.

**Comment by zach-morris** [comment]
Fixed thanks to @garbear

**Comment by gsjv2** [comment]
wonderful!

I can't wait to test it.
