### ISSUE TITLE
Poll:  Game list content

### ISSUE THREAD

**Issue by zach-morris** [zach-morris/plugin.program.iagl#131]
In the past, I've tried to whittle down game lists to be similar to 1G1R, but I wanted to get a feel for what others prefer.  Do you want to see all the games and then filter on your own (via the addon), or do you want them pre-filtered?

[![](https://api.gh-polls.com/poll/01DPKXCGGECV44EFZNMH936X27/All%20Available%20Games%20and%20Versions%20in%20a%20Set)](https://api.gh-polls.com/poll/01DPKXCGGECV44EFZNMH936X27/All%20Available%20Games%20and%20Versions%20in%20a%20Set/vote)
[![](https://api.gh-polls.com/poll/01DPKXCGGECV44EFZNMH936X27/1%20Game%20per%20set%20mentality)](https://api.gh-polls.com/poll/01DPKXCGGECV44EFZNMH936X27/1%20Game%20per%20set%20mentality/vote)

There's pros/cons to each:  Size of file, time it takes for browsing, content choice, etc

If you prefer 1G1R, what would your criteria be for pre-filtering?

**Comment by ITV4Free** [comment]
All versions if fan translated,hacks/mods are included

**Comment by drinfernoo** [comment]
One thing I'd particularly like to see would be a setting to hide releases outside of the user's language, if possible.

**Comment by ITV4Free** [comment]
How soon will these changes be added to current rom libraries

**Comment by zach-morris** [comment]
If I move to full lists, it could take a while.  I'll have to get more input from users before changing all lists

I've added additional filtering method 'Group by Tag' for the next release, so you can filter by language or region (which are the most common tags added to game sets)

**Comment by ITV4Free** [comment]
Sounds great thanks more retro games for us old school types

**Comment by zach-morris** [comment]
Closing this.  Most people want everything.  I've added custom group filtering in 2.1.4 so I think that will provide the best of both worlds.  When I update game lists to be unfiltered, I will add a custom group of '1G1R'
