### ISSUE TITLE
IAGL refuses to use external launcher

### ISSUE THREAD

**Issue by Garreat** [zach-morris/plugin.program.iagl#132]
Hello!
Using IAGL with Kodi 18.4 on Ubuntu 18.04.

Performed the external launcher setup to launch games using standard RetroArch installation.
I have used parameters:
RetroArch App Location: **/usr/bin/retroarch**
RetroArch System Folder: **/home/user/.config/retroarch/cores/**

Then I did 'Update Launch Command' for a SNES list to choose my installed SNES9x core.
Selectin 'View List Settings' I see:
Launch With: **external**
Launch with Command: **"%APP_PATH%" %NETPLAY_COMMAND% -L %RETROARCH_CORE_DIR%/snes9x_libretro.so "%ROM_PATH%"**

As far as I understand, that should translate to:
/usr/bin/retroarch -L /home/user/.config/retroarch/cores/snes9x_libretro.so (ROM_PATH)

I have tried that command manually and it works fine,
However, IAGL complains: **"This game isn't compatible with any available emulators"**.

In Kodi log I see:
`2019-10-13 00:25:32.593 T:139639561045760  NOTICE: IAGL:  Gameclient for Retroplayer set to: None
2019-10-13 00:25:32.593 T:139639561045760  NOTICE: IAGL:  Attempting to play the following file through Retroplayer: /home/user/.kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/ROM.sfc`

So it looks like the external launcher isnt used at all.
Plugin options show "Emulator Launcher: External".

Has to be an issue there somewhere.
Help appreciated! Thanks.

**Comment by zach-morris** [comment]
Hmm, well you got it exactly right.  If the view list settings say what you describe, then thats what is  written to the file.  When you change that setting, the list cache is supposed to be cleared automatically, but perhaps it wasn't?  You can manually clear it by right clicking on the list and hit 'refresh game list', which will manually clear it.

**Comment by Garreat** [comment]
After some dwindling with cache I could make IAGL use external launcher.
I stumbled on the error:
`2019-10-14 20:28:26.783 T:139753395578624   DEBUG: IAGL:  The Retroarch Core directory could not be found.  Defaulting to /usr/lib/libretro`
I have double checked and 'Retroarch Core directory' was 100% fine.

I ended up symlinking /usr/lib/libretro to the actual retroarch core directory.
Some bugs there, but now it works ;). Thanks

**Comment by zach-morris** [comment]
OK.  Glad it works.  Did you happen to use '~' in your path previously?  There's an issue there, which I've actually fixed (hopefully) in the git master, just not released yet on my repository.

**Comment by Garreat** [comment]
No, it was a legitimate absolute path.
I think this can be closed now. Probably I'll open another issue soon ;).

**Comment by zach-morris** [comment]
One thing I noticed:
RetroArch System Folder is not the core folder.  Thats the 'system' folder, where BIOS files and whatnot go.

**Comment by zach-morris** [comment]
I believe this is fixed in version 2.1.3 (the addon now translates ~ correctly).  If you still see an issue please let me know.
