### ISSUE TITLE
Empty “Browse by Category” sublists

### ISSUE THREAD

**Issue by tarkh** [zach-morris/plugin.program.iagl#134]
Android 7.1.2 arch 64
Nightly IAGL version
All lists works fine except “Browse by Category”... I can enter it and I do see categories (8 bit, 16 bit etc...), but when I select any it shows me empty content with only .. (back) option.

**Comment by zach-morris** [comment]
Yeah, I found that bug too (utf-8 issue).  It is already fixed in git master, but i haven't yet released it in my repository.

**Comment by tarkh** [comment]
Thanx! Updated from git master and now everything works!
