### ISSUE TITLE
PSX emulator

### ISSUE THREAD

**Issue by ITV4Free** [zach-morris/plugin.program.iagl#135]
How do u access the memory card/s inside the emulator(via Kodi) without booting u a game

**Comment by drinfernoo** [comment]
@ITV4Free Kodi does not have this functionality. That would be an emulator feature, and outside the scope of this project.

**Comment by zach-morris** [comment]
Yes, this isn't an IAGL issue per-se.  There's nothing the addon does or can do for memory cards.  For questions like this, best to ask in the Kodi forums.
