### ISSUE TITLE
NDS Emulator

### ISSUE THREAD

**Issue by ITV4Free** [zach-morris/plugin.program.iagl#137]
The Emulator frame rate is junk its so slow you cant lay any games can u fix this issue thanks

**Comment by zach-morris** [comment]
The addon does not do anything as far as the actual emulation is concerned.  That is specifically answered in the FAQ [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#14a-game-xyz-starts-but-has-issues-your-addon-is-broken).
