### ISSUE TITLE
Cache Size

### ISSUE THREAD

**Issue by ITV4Free** [zach-morris/plugin.program.iagl#138]
Can u make this alot bigger than 64GB if youre adding PSP,GameCube,PS2 games since theyre alot bigger PSP&Game Cube are 1.5GB per game average(mini dvds)

**Comment by zach-morris** [comment]
I suggest if you're making cache 64GB, then you do not want the files to be deleted.  Try changing the download location, then there is no filesize limit.  See [here in the FAQ](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to).
