### ISSUE TITLE
PSX BIOS`

### ISSUE THREAD

**Issue by ITV4Free** [zach-morris/plugin.program.iagl#139]
ive added the BIOS to retro arche and downloaded the offical BIOS addon for KODI but i cant find it in the system to(add BIOS files into cd based emulators)PSX,Saturn,Sega CD,ect

**Comment by drinfernoo** [comment]
@ITV4Free This is not something that IAGL handles in any way. That's something that needs to be set up at emulator level.

**Comment by zach-morris** [comment]
This isn't an issue, it's a question.  Please reserve the issues area for coding/software issues with the addon (stop opening issues for non-issues).  BIOS files have to be setup by the user.  There's no way around that unfortunately.

[The wiki ](https://github.com/zach-morris/plugin.program.iagl/wiki/1.--Setup#setup-with-retroplayer)specifically covers where BIOS files go:
```
For current status of the Retroplayer, please see the Games Support Kodi forum.

Note that some systems require BIOS files to function, and that includes the game addons for libretro. The BIOS files required are the same BIOS files listed in the libretro wiki. The BIOS files need to be installed in the appropriate game addon userdata system folder.

An addon to help you place the BIOS files in the appropriate spot for Kodi Retroplayer can be found here.

For example(s):

Genesis Plus GX emulator (game.libretro.genplus) requires these files to be placed in ..path_to_userdata/addon_data/game.libretro.genplus/resources/system/

Reicast (Dreamcast/Naomi) emulator (game.libretro.reicast) requires these files to be placed in ..path_to_userdata/addon_data/game.libretro.reicast/resources/system/dc/
```

**Comment by drinfernoo** [comment]
Be aware that those example paths for BIOS locations are in no way exhaustive of all (or even a few) emulators in general, and those two specific examples only apply to the libretro cores available from the Kodi repository.

**Comment by zach-morris** [comment]
Right.  If you're using Retroarch, then the best place to check is the libretro wiki [here](https://docs.libretro.com/).  Each core specifies what files are required and where they need to go.

**Comment by ITV4Free** [comment]
Got the emulator to work correctly using the bios kodi plugin found on this site
