### ISSUE TITLE
Update unhide list function

### ISSUE THREAD

**Issue by beta-tester** [zach-morris/plugin.program.iagl#140]
hello, this is more a question than a bug report.
i hided few game lists by using the "Update Visibility" option.
but how can i bring back specific hidden game lists?

**Comment by zach-morris** [comment]
See [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#8--wait-wait-i-guess-i-do-want-to-see-that-archive-after-all)

**Comment by drinfernoo** [comment]
@zach-morris, is it possible to have hidden lists show up in a separate "Hidden Lists" section, where you could then unhide them individually?

**Comment by zach-morris** [comment]
I could probably update the advanced setting to be smarter, to show all currently hidden lists for the user to select, but is this really something that happens often?

**Comment by beta-tester** [comment]
normally i only interested to see very few game lists, so i hide al unnecessary game lists one by one. (ubdate visibility to hide and accept the choice)
this task is already a bit boring/alloying with all the fan game lists - but hey, other peoples have interest in those and that is absolutely ok.
 
but sometimes i decide to take a look to game lists that is previously had selected as hidden but then i have to bring all game lists back to view, that means for unhide one single game list i have to re-hide 95% of the game lists again i previously hide before. and if in that annoying boring task i kae a mistake, then i have to redo everything again...
it is already the third time, i want to unhide one singel game list.

**Comment by skarragallagher** [comment]
I just went through this with IAGL and it took me about 1/2 hour to hide all the lists. Not a big deal, but i would love to see a better dialog for this rather than mindlessly going through all the lists. Me personally only show about 8 lists (NES, SNES, PS1, Dreamcast, N64) so perhaps something similar to one screen showing all of the lists and a little on/off toggle next to it so you can turn on and off lists much quicker. Just a thought...

**Comment by zach-morris** [comment]
OK, i'll look into updating the unhide option.  As an alternative way to view your smaller batch of lists, see [update metadata](https://github.com/zach-morris/plugin.program.iagl/wiki/2.--Addon-Settings#game-list-settings).
You can select each list you want to group, then select Update Metadata>Category, then enter a new category (example "Zachs Custom Category").  Using this way you can categorize the groups your most interested in.  Giving them all the same custom category will group them all together, the custom category can be added as a widget, etc.
<img src="https://i.imgur.com/FeY9qjn.png">

**Comment by zach-morris** [comment]
Fixed in last commit, now you get a window with options, or choose 'All' from the top
