### ISSUE TITLE
Failed Links in Final Burn Neo Directory

### ISSUE THREAD

**Issue by pirsir76** [zach-morris/plugin.program.iagl#141]
Hello Master Zack,

I'm just reporting that I'm getting failed download links when I'm trying to play the Final Burn Neo games.

It comes up with the message 
[game name here] download failed Archive returned no file.

Note:
I do have an  archive.org account and I did enter my email and password.
It is possible archive.org no longer provides the file(s)
Final Burn Neo was working fine for me for a long time, could have been the updates to IAGL that made it stop working for me?

If other people are able to download the games still, it must be a problem on my end.
I am using a Sony 2019 model TV (Android OS) + Kodi + Retroarch + IAGL to play.
If anyone has any ideas? I did notice something strange in the Final Burn Neo 'View List Settings'
everything looks normal but the 'Post Download Command' says None. Which is not like the other emulators.

**Comment by zach-morris** [comment]
The archive for that game list recently changed.  I have an update coming soon to update it

**Comment by pirsir76** [comment]
Sounds great Lord Morris.
How will I know when the update is out?

Final Burn Neo is the main emulator I play.

**Comment by bongobil** [comment]
Psp returns the same

**Comment by zach-morris** [comment]
@pirsir76 , this repository already has an updated list [here](https://github.com/zach-morris/plugin.program.iagl/tree/main/resources/data/dat_files).  When the addon version is updated in the repository, the addon will tell you a new version of a list is available and ask you what to do (get the new one or keep the old one)

**Comment by zach-morris** [comment]
@bongobil , PSP also changed recently.  Most of the archive is no longer available.  PSP Mini's are the only ones that seem to still be there.

**Comment by pirsir76** [comment]
> @pirsir76 , this repository already has an updated list [here](https://github.com/zach-morris/plugin.program.iagl/tree/main/resources/data/dat_files). When the addon version is updated in the repository, the addon will tell you a new version of a list is available and ask you what to do (get the new one or keep the old one)

I don't know if my particular set-up informs me of when the repository is updated.
It never has prompted me for an update in the past.
I'm playing off my Sony TV in Kodi.

**Comment by Philps** [comment]
Would be great if you could release a new update, so this list is being rolled out.

**Comment by Philps** [comment]
Seems the link is incorrect, so this list is not working

NOTICE: IAGL:  Attempting to download file http://archive.org/download/https://archive.org/download/FBA_Arcade_Latest/roms.zip/<xxx>.7z

**Comment by zach-morris** [comment]
Should be fixed in 2.1.4
