### ISSUE TITLE
Adventure games kodi

### ISSUE THREAD

**Issue by natila31** [zach-morris/plugin.program.iagl#145]
Hey im new to this and sorry if i ask something silly, i really love the retro games section of kodi, i Just cant get any adventure game to work, its either not the right emulator or some kind of error, is there something i need to change in settings or so? For example like scummvm.
And i Read the topic bout exodos, but will that one ever going tot work, because i was zo happy when i saw that one, or is it going to be deleted completly, friendly greetings nathalie

**Comment by drinfernoo** [comment]
This sounds like you've skipped a few steps, probably.

Follow the guide [here](https://github.com/zach-morris/plugin.program.iagl/wiki/1.--Setup) to set everything up correctly.

**Comment by natila31** [comment]
Thx for your reaction, seems no scummvm for me lol, ive done everything as it says in the description, at least i think i did, and im kinde a newby with the retro games section, it says that there is no emulator for the scummvm one, all the other games section seems to work, except that one

**Comment by drinfernoo** [comment]
It doesn't appear that there's a ScummVM core for Kodi's libretro implementation. There is one in RetroArch, if you're able to set that up.

**Comment by natila31** [comment]
Oh okay, and i just have to follow the guide about retroarch then?

**Comment by natila31** [comment]
Okay i added retroarch, updated everything, also downloaded the bios and all that and when i click a game in iagl it opens scummvm on retroarch and then a pop-up turns up stating unable tot locatie the 'access.dat' engine data file, im really confused now

**Comment by natila31** [comment]
@zach-morris you probably have been this already, but i Saw this and thought is this maybe An option, sorry if im asking the wrong questions 😳

**Comment by zach-morris** [comment]
ScummVM is now available in Kodi as a retroplayer core.
Regarding setup, there may be some supporting files you need to put into your Retroarch system folder (search the web for retroarch full bios packs to find the files you need).  See the info [here](https://docs.libretro.com/library/scummvm/).  I dont think anything is specifically needed for scummvm out of the box though.
