### ISSUE TITLE
Your PSP Games from IAGL makes me expensive paid

### ISSUE THREAD

**Issue by zianfernandez** [zach-morris/plugin.program.iagl#146]
**Yo!**

Your PSP is **REALLY BAD!**

1.) Playing PSP Games requires me creating Account for Internet Archive

2.) Does **NOT** Work in Kodi Retroplayer and Does **Not** Recognize the third party program or Emulator

3.) Few days after trying to play Sword Art Online Infinity Moment and it failed to launch on Kodi, I have been **SUED** for copyright infringement by "Downloading Pirated Content".

You should remove the PSP Content on IAGL, Because _I trying to **Not to blame you about this**_ But my Government will trace down the source _(I know it really sucks, But they monitors our activities and preventing any copyright contents that are registered trademarks in our country.)_

**Comment by zach-morris** [comment]
Well, read the [FAQ](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#18-dmca).
