### ISSUE TITLE
applaunch.sh prevents Kodi from restarting correctly its Remote control service

### ISSUE THREAD

**Issue by gabsoftware** [zach-morris/plugin.program.iagl#147]
When we return from retroarch and Kodi is restarted by applaunch.sh, Kodi is restarted with an error about the Remote control service. The effect is after playing a game, we can no longer control Kodi with Kodi Kore app, and Kodi has to be restarted manually.

That remote control service cannot start because port 9777 is already taken by applaunch.json and its subprocesses.

That port is taked by applaunch.json because it is launched from Kodi, so it inherits all the opened sockets (so, opened UDP ports as well).

I have a solution, not exiting and restarting Kodi. Instead, I propose to suspend and resume Kodi processes.

Here is my modified applaunch.sh:

    #!/usr/bin/bash
    # App Launch script - Exit Kodi to launch another program
    # Updated by zachmorris for use with IAGL
    # This script will try to exit Kodi first via JSONRPC, then a normal shutdown if the first attempt fails, then a hard shutdown if the second attempt fails
    LOGFILE=$HOME/.config/retroarch/log.txt
    # Check for agruments
    if [ -z "$*" ]; then
        echo "No arguments provided." >> $LOGFILE
        echo "Usage:" >> $LOGFILE
        echo "applaunch.sh [/path/to/]executable [arguments]" >> $LOGFILE
        exit
    fi

    JSON_RPC_NOTIFICATION=$(curl -s --data-binary '{"jsonrpc": "2.0", "method": "GUI.ShowNotification", "params": {"title": "Please Wait", "message": "Running IAGL Launch Script" },  "id":1}' -H 'content-type: application/json;' --user myuser:mypassword http://127.0.0.1:8080/jsonrpc) >> $LOGFILE
    KODI_PID_LINUX_X11=$(ps -A | grep [k]odi-x11 | head -1 | awk '{print $1}')
    KODI_PID_LINUX=$(ps -A | grep [k]odi | head -1 | awk '{print $1}')

    echo "KODI_PID_LINUX_X11 = $KODI_PID_LINUX_X11" >> $LOGFILE
    echo "KODI_PID_LINUX = $KODI_PID_LINUX" >> $LOGFILE

    #Sleep to let Kodi write to log
    sleep 1

    #Suspend Kodi
    if ! [ -z $KODI_PID_LINUX_X11 ]
    then
        echo "Suspending Kodi..." >> $LOGFILE
        kill -STOP $KODI_PID_LINUX_X11
        kill -STOP $KODI_PID_LINUX
        echo "Kodi suspended!" >> $LOGFILE
    fi
    #End Suspend Kodi

    # Start Emulator Launch
    echo "Launching Emulator with command: $@" >> $LOGFILE
    # Launch app - escaped!
    "$@" &
    EMULATOR_PID=$!
    echo "Waiting for emulator to exit..." >> $LOGFILE
    wait $EMULATOR_PID
    echo "Resuming Kodi..." >> $LOGFILE
    sleep 2
    kill -CONT $KODI_PID_LINUX_X11
    kill -CONT $KODI_PID_LINUX
    echo "Kodi resumed!" >> $LOGFILE
    #End of script

Note that I stripped everything that was not about Linux (like Darwin support), but hopefully that can be added back :)

**Comment by zach-morris** [comment]
Thanks for this.  I have recreated this issue as well and don't have a great one-size-fits all solution

**Comment by gabsoftware** [comment]
Ah, I didn't pay attention to the pause option in the plugin settings... Indeed it does pause Kodi processes...

**Comment by zach-morris** [comment]
Closing this item as I think it's been addressed with apppause.sh if you want to use that.

In addition, i've updated applaunch script to first attempt to close Kodi via JSONRPC, so in theory that should have Kodi gracefully shut itself down (although you need to enable web control in Kodi settings)
