### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Cal75** [zach-morris/plugin.program.iagl#148]
Hello i have a problem to play a retro game in scumm on kodi there is no available emulator 
Maybe there is a answer to this
Greetings Christian

**Comment by drinfernoo** [comment]
Kodi's libretro implementation doesn't yet have a ScummVM core. You can setup IAGL to use RetroArch, along with the core there.

**Comment by Cal75** [comment]
Hello thank you for your answer
My sis is already been busy with retroarch and some of the games are working but some games like the 7 guest isnt working
Gr Christian

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by zach-morris** [comment]
It's working for me (on OSX).  If you want to try and use Kodi, you could also use [these pre-built game addons](https://github.com/zach-morris/kodi_libretro_buildbot_game_addons), but as @drinfernoo said, it should work with RA as well.
<img src="https://i.imgur.com/sSON2Cy.png" width="600" >

**Comment by Cal75** [comment]
Thx for your great advise, my sister got it to work, is there also a way to play the games under exodos with scummvm, like the 11th hour and so on or will there be more games in the future added to scummvm

Outlook voor Android downloaden<https://aka.ms/ghei36>
________________________________

**Comment by zach-morris** [comment]
The exodos archive was unfortunately removed from archive.org, so I'll likely have to remove the list from the addon.
