### ISSUE TITLE
Change Addon Category to Game Addon

### ISSUE THREAD

**Issue by tradewatcher** [zach-morris/plugin.program.iagl#149]
I use Win10 - 64bit with Kodi 19.5 with Confluence.

I can't add IAGL as Game Addon (submenu) cause it is provided as Video Addon.

Please fix it or tell me how to fix this.

Greetings and thanks for the good job!

I hope this is not a bug of the Skin. There are not much good Skins :(

**Comment by zach-morris** [comment]
Read the wiki [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#13--this-addon-shows-up-as-a-video-addon-and-not-a-program-addon).

**Comment by drinfernoo** [comment]
Game Add-ons are separate from Program Add-ons. However, this add-on usually shows in both Video and Game sections for me.

**Comment by zach-morris** [comment]
It should [show in both by default](https://github.com/zach-morris/plugin.program.iagl/blob/main/addon.xml#L14) (video and games), although you can change that in the advanced settings.
