### ISSUE TITLE
Last Played error in widget

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#15]
I've posted my kodi.log [here](https://paste.ubuntu.com/p/6nZG3DrPYS/). The widget was working until I exited and reopened Kodi :(

**Comment by zach-morris** [comment]
Try 2.0.1.  I believe this is fixed.  Probably the same issue I was having with #9

**Comment by zach-morris** [comment]
I believe this is fixed.  Please re-open with a debug log if not, thanks
