### ISSUE TITLE
Help with setting up Sega CD on IAGL

### ISSUE THREAD

**Issue by pirsir76** [zach-morris/plugin.program.iagl#150]
Hello Master Zack,

I am using a Sony 2019 model TV (Android OS) + Kodi + Retroarch + IAGL to play.
And I have the internet login enabled.

All I'm getting when I try to play any Sega CD game is a blank screen.
I check some of the closed issues and it appeared as if someone had the same problem as me.
You advised: "I would need a debug log to know why. I tried it on my end and it works fine. If I had to guess, you don't have the BIOS files in the right spot. Check the wiki."
That's probably my problem as well; the BIOS file is in the wrong spot.
But, I can't find the info on the wiki to put the BIOS file in the right spot.

I went to: https://github.com/zach-morris/plugin.program.iagl/wiki
And clicked on the "Platform Compatibility" link (presumably the information I need) but it just sends me back to the same webpage.

Can you offer some basic instructions on how to get the SegaCD games working?

Thanks

**Comment by pirsir76** [comment]
I've been searching for a fix, the The Retro BIOS tool is not working it seems for me.
When I install it into Kodi it's coming up with an error.

**Comment by zach-morris** [comment]
OK, I'll take a look at the tool since I haven't messed with it in a while.  It should in theory still work though.  Thanks for the report.

I gave up on the compatability page currently.  Things change so fast for Libretro cores that it's too hard to maintain
