### ISSUE TITLE
Opening RetroArch for the first time leads to a black screen (RPi4, Kodi Leia v18)

### ISSUE THREAD

**Issue by nakulbende** [zach-morris/plugin.program.iagl#152]
Hello, I was following the setup instructions on this repo - on my Raspberry Pi 4 running Kodi v18 (it's actually a dietpi installation, if that matters). I installed IAGL and RetroArch (through gamestarter) and was trying to follow instructions in section *Basic External Setup Instructions*. I want to copy the bios files to appropriate folder - but when i start RetroArch, I get a notification that Kodi will exit and RetroArch will start - but I just have a black screen. Also, I can hear audibly the remote control inputs, so something is happening, but I cant see anything. I tried this with 1080p/ 4k resolution, reinstalled everything, but nothing worked. 

A quick look into the debug log brings this issue up: 
```
2020-02-12 07:40:41.303 T:2973215840   DEBUG: We have an error loading picture 0!
2020-02-12 07:40:41.303 T:2973215840   ERROR: Error loading the current image 0: /storage/.kodi/addons/game.retroarch/fanart.jpg
2020-02-12 07:40:41.303 T:2973215840    INFO: set image /storage/.kodi/addons/game.retroarch/fanart.jpg unplayable
2020-02-12 07:40:41.313 T:2447155408   DEBUG: PushCecKeypress - received key a8 duration 0
2020-02-12 07:40:41.364 T:2973215840   DEBUG: HandleKey: 168 (0xa8, obc87) pressed, action is Right
```

This just goes on and on in my log. What am I missing, and how do I fix this? Where is the default system folder for retroarch?

PS: Thanks for supporting this awesome repo. Grew up in India, where video games were not so common. I can replay my childhood!

**Comment by zach-morris** [comment]
Thanks for the kind words, and the log info.  Not sure what exactly is going on, but the error shown seems to point to the fact Kodi can't find an image for the gamestarter addon, which necessarily might not even be the problem.  Your symptoms sound like it's starting in retroplayer and showing a black screen.

The debug log should also show the launch command, and you should make sure that looks correct.  it should show something to the effect of:
```
IAGL:  Sending Launch Command: /storage/.kodi/addons/game.retroarch/addon.sh nestopia "/path/to/my/game/mario.nes"
```

You should also be able to see this command in the addon by bringing up the context menu and selecting "Review List Settings". This will show you the current download and launch parameters are.

Setup for gamestarter [here](https://github.com/bite-your-idols/Gamestarter#additional-info) shows the BIOS files go in ```/storage/emulators/```


Might also want to [check the issues in the gamestarter repository](https://github.com/bite-your-idols/Gamestarter/search?q=black+screen&type=Issues).  Many point to a black screen problem and it's possible there's some binary dietpi doesn't have that gamestarter needs.

**Comment by nakulbende** [comment]
Hello @zach-morris - I did add the bios files in the /storage/emulator - but it still has the same issue. I have actually also located the fanart.jpg. The gamestarter thing might be only for librelec?? Is there a way to just add retroarch on dietpi?

I am also adding this issue in gamestarter repo - maybe somebody there will know. 

BTW - my log did not have any such command for launching IAGL. Should it? I am just trying to open retroarch, in the step before even opening IAGL.

**Comment by zach-morris** [comment]
Ah, i missed that part, i assumed you were trying to launch from IAGL.
Dietpi appears to not be supported very well for RA in my limited research.  See [here](https://retrogadventure.wordpress.com/2018/07/03/rock64-dietpi-retroarch/).  I've personally never used it.

**Comment by drinfernoo** [comment]
@zach-morris Is this even an IAGL issue then??

**Comment by nakulbende** [comment]
Yikes, I believe this is indeed not a IAGL issue. DO I have a recourse here? Installing individual emulators? Seems like I can run IAGL fine, but need emulators. 

Sorry for noobiness.

**Comment by zach-morris** [comment]
With dietpi, [I'm seeing nothing but roadblocks](https://github.com/MichaIng/DietPi/issues/1515). RPi4 and emulation seems like it would be better suited for either LibreElec + Gamestarter (which based on the forum [appears to work](https://forum.libreelec.tv/thread/287-gamestarter-retrogaming-add-ons-rpi-generic/)) or a dedicated build for emulation like [Libreelec RR](https://forum.libreelec.tv/thread/12662-libreelec-rr-9-x-emulationstation-retroarch-pegasus-dolphinqt-moonlight-chrome-s/)

**Comment by nakulbende** [comment]
At the time I got RPi4, LibreElec was not working with it. Dietpi was
actually the only thing that worked, but I should have just tried a simple
raspian install :( Thanks a lot for you help. I am going to read on how
easy it is to backup a kodi config, and maybe start on a LibreElec. Thanks!

PS: On another note - cou;d I use other emulation packages that gamestarter
has, and use them as external emulators to IAGL? Or install some random
emulators, and use IAGL without retroarch? I guess I am asking if there is
any way to get my setup working in absence of IAGL.



Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com


- Ever tried. Ever failed. Try Again. Fail again. Fail better.

--Samuel Beckett

**Comment by zach-morris** [comment]
Yes, you dont need IAGL at all.  IAGL is just a Kodi addon to download and launch games.  Particularly useful if you dont already have the game files and/or your machine doesn't have a lot of storage space to keep the files locally.  LibreElec or one of the Flavors of LibreElec or RetroPie I think are what you would want to look into.

**Comment by nakulbende** [comment]
I guess I really liked the interface and the ease of just having all-in-one
stop for tv/ games etc. I was asking more on the note of using IAGL without
RetroArch. If I understand correctly, Retroarch just provides emulators to
launch with - can you give other emulators to IAGL with launch with
external emulator option?



Nakul Bende,

Materials Scientist, Formlabs Inc.

http://nakulbende.com


- Ever tried. Ever failed. Try Again. Fail again. Fail better.

--Samuel Beckett

**Comment by zach-morris** [comment]
Yes, IAGL comes packaged with most standard commands for setups that people use, but you can enter any launch command you want for each game list, see [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#3--i-want-to-use-emulator-xxx-instead).
