### ISSUE TITLE
load a personal zip

### ISSUE THREAD

**Issue by fatshotty** [zach-morris/plugin.program.iagl#154]
Hello,
I've downloaded a zip file and I'd like to load id in IAGL in order to play it. Is it possible?
My zip file contains .cue and .bin files. Is it a valid file for IAGL?

thanks in advance

**Comment by zach-morris** [comment]
You can, but you'd have to manually add it to a game list (xml file) if the name is unique.  You can copy the format of any of the files [here](https://github.com/zach-morris/plugin.program.iagl/tree/main/resources/data/dat_files) to get an idea of how they're organized, which pretty much follows the standard of dat files, and then adds metadata.

Finally, in your game list xml header, you need to point the addon to where the zip file is located.  So the header would look something like:
```
	<header>
		<emu_name>Fatshottys List</emu_name>
		<emu_description>Fatshottys List</emu_description>
		<emu_category>Comma,Seperated,Categories,Here</emu_category>
		<emu_version>11111</emu_version>
		<emu_date>03152020</emu_date>
		<emu_author>Fatshotty</emu_author>
		<emu_visibility>visible</emu_visibility>
		<emu_homepage>NA</emu_homepage>
		<emu_baseurl>https://archive.org/download/</emu_baseurl>
		<emu_launcher>retroplayer</emu_launcher>
		<emu_default_addon>none</emu_default_addon>
		<emu_ext_launch_cmd>none</emu_ext_launch_cmd>
		<emu_downloadpath>Define path to your zip file here</emu_downloadpath>		
		<emu_postdlaction>unarchive_game_launch_cue</emu_postdlaction>
		<emu_comment>This description shows up in Kodi as the game list plot</emu_comment>
		<emu_thumb>xxx.jpg</emu_thumb>
		<emu_banner>yyy.jpg</emu_banner>
		<emu_fanart>zzz.jpg</emu_fanart>
		<emu_logo>aaa.png</emu_logo>
		<emu_trailer>youtubevideoidhere</emu_trailer>
	</header>
```
