### ISSUE TITLE
this game isn't compatible with any available emulators

### ISSUE THREAD

**Issue by Anton2001868** [zach-morris/plugin.program.iagl#155]
Hi it keep saying this game isn't compatible with any available emulators please help me

**Comment by Anton2001868** [comment]
Now it's saying failed to play the emulator nec PC engine supergrafx had an internal error

**Comment by drinfernoo** [comment]
Those are issues with your emulator, unless IAGL itself is throwing the error.

**Comment by Anton2001868** [comment]
How do I fix it ???

**Comment by drinfernoo** [comment]
Have you looked to see what error is being thrown? What emulator(s) are you using? Are they the ones distributed by Kodi, or external emulators? What games are you trying to play? Have you followed the setup procedure outlined in IAGL's wiki?

It would be basically impossible to tell you how to fix it, as you've provided very nearly zero details on your issue.

**Comment by zach-morris** [comment]
Kodi for xbox (UWP) does not support Retroplayer since it's against the TOS for XBOX.
See forum thread [here](https://forum.kodi.tv/showthread.php?tid=352550&pid=2932544#pid2932544)

**Comment by drinfernoo** [comment]
@zach-morris Is he on Xbox?

**Comment by Anton2001868** [comment]
no i am on nvidia shield

**Comment by Anton2001868** [comment]
i am trying to play super mario 64 but the emulator's just dont work how do i see the error log ?

**Comment by drinfernoo** [comment]
Super Mario 64 is not a PCE game...

**Comment by Anton2001868** [comment]
What is PCE ?  Sendt fra Mail til Windows 10 Fra: drinfernooSendt: 19. marts 2020 16:45Til: zach-morris/plugin.program.iaglCc: Anton2001868; AuthorEmne: Re: [zach-morris/plugin.program.iagl] this game isn't compatible with any available emulators (#155) Super Mario 64 is not a PCE game...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zach-morris** [comment]
I assumed you were the same user who posted in the Kodi forum (the same day with the same message description).  Suggest starting by following the [Setup Guide](https://github.com/zach-morris/plugin.program.iagl/wiki/1.--Setup).

**Comment by zach-morris** [comment]
Closing this issue now.  I think I've simplified setup for v3.0.0 and it's much more user friendly.  I've also updated the messaging to be more clear on what you need to do in order to get launchign to work (external or retroplayer).

Reopen if you still have issues.
