### ISSUE TITLE
How to actually create a custom list?

### ISSUE THREAD

**Issue by KUPOkinz** [zach-morris/plugin.program.iagl#156]
Hello Zach, first let me say what a wonderful apps you've made. Here a little over a year ago, I created a video https://www.youtube.com/watch?v=M9eTz9ILRY0&t=9s even showing how to set this up on Kodi :) Of course, I praised you like gold in it!

But I have a question, I have gsuite, my college has paid for it for the past 10 years therefore I have unlimited Google Storage. I am wanting to create my own lists, instead of using these older outdated ones. I notice for example, a lot of the games only have one copy of what I want. Like for example, there is a lot of special bonuses in the Japanese version of Chrono Trigger that isn't shown because the list only contains the USA one.

I have a very neatly organized folder layout in my drive. Starting with Roms > Systems > Nintendo - Nintendo SNES. I have tried to copy and paste a link into it, but it seems like you use some sort of automation tool to fill these lists in, I'm doubtful you've filled in 30,000 titles manually lol. Is there any reason you've not released the tool so we can easily make our own lists or is it that you have a super simple method that I'm thinking too hard to find out?

I was attempting to use a batch renaming utility to embed my links in the xml file, but again, I cant actually get anything to show up. Seems counter-intuitive to even try without a tool.

P.S. As a side project, I have integrated IAGL into EmulationStation as it's own stand-alone app that can be launched from within and when games are downloaded, they go directly into the emulation folder itself and are shown as normal ;) I have a heavily rigged form/script that is connecting parallel shortcuts (%home%) to the OG folder and then using the basic ".portable." format for Kodi.

Please, help me create my own lists! Teach me the ways :P Please, I have spent the better part of a few days trying to figure this out, all I want is my own collection from my google drive. :( I am in love with IAGL, ever since your first release came about before you had changed the original name (I forgot what it was called :P).

Again, my idea was to erase as much useless information (all I can about is direct downloads) and try to leave only the base URL parts and the hyperlink. I would then use a batch utlity to copy and paste the scripts in and between each link. But.. I cant figure it out! Thank you :)

**Comment by zach-morris** [comment]
Yes, agreed on the whole tooling thing needed for lists bigger than say 20 games.  You could do it manually, but it's a slog.  I personally have created a completely custom tool to deal with exactly this, including scraping IA, then various metadata sites, to generate the lists.  I am very reticent to provide it mainly because there's absolutely no documentation on it and, up to this point, I'm really the only person who knows how to make it work.  Supporting a half-baked (but working!) system isn't what I'm interested in doing.   That being said, I could package it up and make it a github repo.  You're free to give it a go.

I'm more inclined to make a converter tool though, if thats what people want.  If you had an ES xml file, that would be fairly simple to convert that to IAGL.

What do you think?

**Comment by drinfernoo** [comment]
@zach-morris The main benefit, I think, of having said tool publicly available, would be for users to make their own lists.

I'd really love to set up IAGL with a GameCube list, for example, and have found an archive of them, but don't know how to or have time to make my own list for it.

**Comment by KUPOkinz** [comment]
@zach-morris please share, I'm very fluent in scripting, as long as it does it for me I can set everything up. I literally beg you :P I have been wanting my own personal lists for months and months, maybe over a year. Please package it, I will wait diligently :)

**Comment by KUPOkinz** [comment]
@zach-morris oh and what do I think? I think exactly as I said in the video, IAGL is the best thing to every happen to the emulation community in terms of ease of usability! I have since switched to IAGL over a year ago and will probably never, ever, ever switch to anything else. Especially if I can get my own lists :) I would personally use this tool https://chrome.google.com/webstore/detail/download-link-generator-f/ilhlicblaojlghndblbncdehbakkebim?hl=en to get my links. Please, can you release it today? I am willing to spend weeks making my own lists :P

**Comment by KUPOkinz** [comment]
Excellent! I am sitting here refreshing your repositories I'm so excited that I've seen you uploaded the script! Do you have discord Zach?

**Comment by KUPOkinz** [comment]
I am trying to run the script thru python (first time using it) and recieving SyntaxError: unexpected character after line continuation character Error. 

I have placed all three .py scripts in my base C drive, then open CMD as Admin
>Python
>C:\archive_tool.py

It does this with all three scripts, I'm trying to figure it out on my own and not bother you but I'm so excited to try and make my owns lists ^.^

**Comment by drinfernoo** [comment]
@KUPOkinz Maybe you're getting errors because you're too busy rushing? Just be patient, it seems like it will come eventually.

**Comment by KUPOkinz** [comment]
@drinfernoo yea, I have no idea where to even begin using this code. I've never used python before :(

**Comment by drinfernoo** [comment]
@KUPOkinz Just relax.

**Comment by zach-morris** [comment]
> @zach-morris The main benefit, I think, of having said tool publicly available, would be for users to make their own lists.
> 
> I'd really love to set up IAGL with a GameCube list, for example, and have found an archive of them, but don't know how to or have time to make my own list for it.

GameCube is in the latest version of IAGL :-)

**Comment by zach-morris** [comment]
> @drinfernoo yea, I have no idea where to even begin using this code. I've never used python before :(
> 
> EDIT: apparently not haha xD I just got excited, Zach help us! :P

Well fair warning, it's written in python

**Comment by KUPOkinz** [comment]
> > @drinfernoo yea, I have no idea where to even begin using this code. I've never used python before :(
> > EDIT: apparently not haha xD I just got excited, Zach help us! :P
> 
> Well fair warning, it's written in python

I will defenitelly learn, I love learning anyways. It's a passion of mine. Do you think you can release it tonight? And so very sorry I seem so impatient, IAGL means a lot to me as emulation is part of my life growing up and is by far my favorite thing in the world <3 If you could release it in a zip, and give a slight instruction just to get started, I would spend all night figuring it out as long as you were sure it worked, even if it was a puzzle in 10 thousand pieces :P

**Comment by zach-morris** [comment]
It will take a bit to clean it up to make it worthy of pushing out, but given we're all stuck at home it shouldn't be too long

**Comment by KUPOkinz** [comment]
> It will take a bit to clean it up to make it worthy of pushing out, but given we're all stuck at home it shouldn't be too long

soooo, tonight :P? Okay okay I'll stop 😃

**Comment by zach-morris** [comment]
One more note on this if you want to start tonight.  One thing my tool currently does not do is extract links from google drive (pretty much only utilizes IA for source data, with some small exceptions), so you'll need to get those somehow externally.  There are plenty of examples on the internet on how to do that with python though.

**Comment by KUPOkinz** [comment]
Like this?  I used the tool I listed about AND YES I WANT TO START TONIGHT<3 I have to donate to you somehow 😄 


8 Eyes (USA).nes 
https://drive.google.com/uc?id=1DHB2ORF9S2J92s0bfnDvIpNp7-zPr3dz&export=download

Action in New York (Europe).nes 
https://drive.google.com/uc?id=1bFs8iIR710N-8vBzW0mCEoKQR-yURaOl&export=download

Aces - Iron Eagle 3 (Japan).nes 
https://drive.google.com/uc?id=1P1exKfAg9leX7b3CYIj-CyFSBp-MC7G8&export=download

**Comment by KUPOkinz** [comment]
I then use a batch converter to break them into there ID links

18uZ7wqnlLn5VrBb891dOi-3pfUIUiONG

1J1Zcz7Wm7y_PgDaXds10_hj5N7bqwYWG

1DHB2ORF9S2J92s0bfnDvIpNp7-zPr3dz

1bFs8iIR710N-8vBzW0mCEoKQR-yURaOl

1P1exKfAg9leX7b3CYIj-CyFSBp-MC7G8

1PI3dKI2UPdVh8dWrf012wlob01jE69x9

1xHqYhA3xFXOEtJC1d_SfbGqcxBoTT6Wa

1-I7Qhq76Q2UqYz7GDt8UKdTGclqRbjt7

**Comment by zach-morris** [comment]
Yes, however, the issue is that the addon needs to know what the filename is ahead of time.
Take a look at the google drive example [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#16-can-iagl-launch-games-hosted-from-google-drive--dropbox--my-online-host-of-choice) if you haven't already, note the filename appending to the end.

**Comment by KUPOkinz** [comment]
![Untitled](https://user-images.githubusercontent.com/63320687/78735298-7659e400-7918-11ea-94c2-ea1ab1d16b07.png)

**Comment by KUPOkinz** [comment]
the file names are just what they say, somethingsomething.nes

My drive folder is structured

Roms > Nintendo > Nintendo - Nintendo Entertainment System > randomrom.nes

**Comment by KUPOkinz** [comment]
Is this is Zach? (yes I am stalking the repos :P) script.module.archive_tool

**Comment by KUPOkinz** [comment]
@zach-morris you there friend?

**Comment by zach-morris** [comment]
OK, I've made an initial commit to [this project](https://github.com/zach-morris/argdb_scraper).  I will be adding some more examples for metadata scraping, but the simplest one should get you started (just a list of games made into an xml file).
