### ISSUE TITLE
[Request] Information item in context menu

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#16]
Just as it says on the tin: Can we get an Information item on the context menu for games?

I typically use the 'Download and Launch' default action, but this means I can't see the information screen :(

While I'm here, would it be feasible to integrate [script.extendedinfo](https://github.com/phil65/script.extendedinfo) for the information dialog? Lots of skins use it, so it would be more likely to match the users' skin, while still being robust enough to show trailers, information, and possibly even launching options.

**Comment by drinfernoo** [comment]
I guess I don't really understand how it works. I was thinking that if you packaged a DialogVideoWindow.xml, that used EIS, you could show your information in an EIS window, already skinned to match the user's system. Maybe that's not how it works?

**Comment by zach-morris** [comment]
I asked a similar question in the past, but as I understand it now, if a skinner packages a DialogVideoWindow.xml file named script-IAGL-infodialog.xml with their skin, Kodi will use that version of the file, otherwise it will default to the one packaged with the addon
