### ISSUE TITLE
Issue with downloading large links outside of ArchiveOrg

### ISSUE THREAD

**Issue by KUPOkinz** [zach-morris/plugin.program.iagl#160]
Running into an issue as to where IAGL cannot confirm the downloads of files over 30mb (because of Google Drive needing the "can't scan for viruses, click to accept download" token). I assume this is an issue with the IAGL app itself which is why I posted it here. I am guessing it can easily be solved with a simple variable of (if -wait) for element pointing to the download button but am not experienced enough to do this myself.

**Comment by drinfernoo** [comment]
Are these for files hosted on your own Google Drive, then? It sounds like the links you're using aren't direct links. I would use something like this to generate them: https://sites.google.com/site/gdocs2direct/

**Comment by KUPOkinz** [comment]
We are way ahead of you on this and have already built and exporter that does this automatically, it's just files that are over 30mb require an extra prompt to download.

See this direct link found here of a repacked KODI folder. 

https://drive.google.com/uc?id=1OK3zAszWfkSWqNhzLZg5ZtVKsNIff-bH&export=download

There needs to be an edit to how IAGL fetches download links, and set an (if) parameter to push the download button if required.

**Comment by drinfernoo** [comment]
Is your browser popping up to let you hit the button... when IAGL tries to download the file? That seems pretty I likely, since IAGL doesn't open any browser that I'm aware of.

**Comment by KUPOkinz** [comment]
IAGL runs on python, it can easily do this. This is something we should work with Zach on figuring out as he's currently in development of a game parser, without a fix, it wouldn't work with his own drive generator.

**Comment by drinfernoo** [comment]
@KUPOkinz I know that Python *can* do what you're asking. You *currently* are not getting a browser popping up, are you?

**Comment by zach-morris** [comment]
I think the URL needs to be different:
https://webapps.stackexchange.com/questions/43386/google-drive-direct-download-for-big-files

It could be as easy as adding your api key to the URL (I haven't tried this)

**Comment by KUPOkinz** [comment]
I've tried that, google removed that feature bad in late 2016. I think the only way would be to add it to the main.py script in IAGL, I'm looking over it but again, not really experienced in Python :/

**Comment by zach-morris** [comment]
Sounds like you have this sorted by changing the URL (adding API key)
