### ISSUE TITLE
Missing options in string.po file.

### ISSUE THREAD

**Issue by roliverosc** [zach-morris/plugin.program.iagl#162]
Hi @zach-morris  . I would like translate it also. I leave you some screenshots. I feel the inconvenience.

![Sin título](https://user-images.githubusercontent.com/24685253/79375497-04594e80-7f59-11ea-9e8f-e0d032e1b8bb.png)
![Sin título (1)](https://user-images.githubusercontent.com/24685253/79375507-07543f00-7f59-11ea-95c9-adac20df2bba.png)
![Sin título (2)](https://user-images.githubusercontent.com/24685253/79375515-08856c00-7f59-11ea-9394-d1b130850109.png)
![Sin título (3)](https://user-images.githubusercontent.com/24685253/79375518-0b805c80-7f59-11ea-8d8d-b592b67d5ffd.png)
![Sin título (4)](https://user-images.githubusercontent.com/24685253/79375523-0d4a2000-7f59-11ea-89e5-37868a248061.png)
![Sin título (5)](https://user-images.githubusercontent.com/24685253/79375532-0fac7a00-7f59-11ea-9c48-4a08dea5380c.png)

**Comment by zach-morris** [comment]
OK, thanks, that should be doable

**Comment by roliverosc** [comment]
Thank you very much @zach-morris

**Comment by zach-morris** [comment]
I've localized everything I think I can in v19.  I still need to come up with a method for some strings in your first and third picture, since the structure of the addon for those files doesn't lend itself to localization very well.  I'll see if I can come up with a method for this
