### ISSUE TITLE
Issue with Amiga emulation using controller and a random PS1 game

### ISSUE THREAD

**Issue by pirsir76** [zach-morris/plugin.program.iagl#165]
Hello,

Issue 1
I'm using the PUAE Amiga emulator and it seems to emulate most of the library that I want to play perfectly. Although, there's an issue in that I can't seem to configure my PS4 controller to play the games on it. All's I can do is press Select on my controller and that brings up a virtual keyboard which works but it basically makes the games unplayable because the virtual keyboard takes up most of the screen.

Is there a way I can configure my PS4 controller to be able to play Amiga games?

Issue 2
Nevermind I solved it. But while I'm here I have a question about storage. I would like a solution for this problem: I'm getting tired of continually downloading big game (like PS1 games.) Is there a solution for this? Like could I download them once to an external HDD and then have IAGL access the HDD next time I go to play the game? If so can you provide explicit instructions for how to do it?

**Comment by zach-morris** [comment]
See the wiki [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to) for issue 2
If you're on an android, there's and extra step, also discussed in the [wiki](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#15-im-on-android-and-i-cant-change-the-download-path-for-games).
