### ISSUE TITLE
Sega Dreamcast games not unzipping

### ISSUE THREAD

**Issue by pirsir76** [zach-morris/plugin.program.iagl#166]
Hello Master Zack,

All the Sega Dreamcast games that I've tested are downloaded as 7z files.
I can read on the Download Paramaters in IAGL for Dreamcast: Unarchive Game, Point to CUE.

Unlike all the other games systems I have tested, Sega Dreamcast games are not unzipped after downloading and the only emulator that has cores in Retroarch is Flycast and Flycast does not un-zip games and cannot play zipped games.

(I have found a temporary work-around for the issue. I take the 7z Dremcast file and manually unzip it on my computer.)

EDIT TO ADD: Oh and that might be another issue as well. Retroarch only has 1 core (Flycast) available for Dreamcast, yet in IAGL, in 'update launch command' it lists 9 cores.

**Comment by zach-morris** [comment]
OK.  It should unarchive 7z files if you have vfs.libarchive installed, although i'll note that there's an issue that will cause Kodi to crash in Windows 10 x64 (unrelated to IAGL). 

Regarding the listed cores, I assume you're talking about all these potential cores?
![img](https://i.imgur.com/frCJbqr.png)

If you can believe it, most of those are still available in some form depending on your system.  The latest flycast is the one at the bottom of the list.

**Comment by pirsir76** [comment]
Hello Zack,

Yes I am talking about those potential cores.
They are listed as being available in RA but when I run IAGL there's only Flycast listed.

(AS A FOOTNOTE: btw I thought I'd let you know on the RA discord all discussion of IAGL is censored. They consider it as breaking their rules.)

**Comment by zach-morris** [comment]
Yeah, I can understand the desire to not discuss this from RA's point of view.  There is a discord channel now for IAGL, although I haven't been on it much lately.

To make your own list, the easiest thing to do is copy from one of the existing lists.  Just take a look at any xml file [here](https://github.com/zach-morris/plugin.program.iagl/tree/main/resources/data/dat_files) of your choosing to make a new list or edit an existing one locally.

Did vfs.libarchive solve the unzipping issue for Dreamcast?

**Comment by pirsir76** [comment]
"Did vfs.libarchive solve the unzipping issue for Dreamcast?"
I think I'll wait till you add it to next update. Since my set-up is NVIDIA Shield TV on my Sony Bravia, it makes that kind of stuff complex for me.

**Comment by zach-morris** [comment]
OK, if you want to try it, you should be able to just install vfs.libarchive by going System>Addons>Install Addons>Official Kodi addons repository>VFS Addons (or something like that) and vfs.libarchive should be listed

**Comment by hymer-up** [comment]
The vfs.library x86-64 Linux Leia version from git is atm broken and not available in Kodi repo.  
Here fully working repacked addon from deb-multi to install for extraction of the 7z files in IAGL  :

[vfs.libarchive-1.0.7.zip](https://github.com/zach-morris/plugin.program.iagl/files/4717255/vfs.libarchive-1.0.7.zip)

**Comment by hymer-up** [comment]
The vfs.libarchive x86-64 Linux Leia version from git is atm broken and not available in Kodi repo.
Here fully working repacked addon from deb-multi to install for extraction of the 7z files in IAGL :

[vfs.libarchive-1.0.7.zip](https://github.com/zach-morris/plugin.program.iagl/files/4717335/vfs.libarchive-1.0.7.zip)

**Comment by zach-morris** [comment]
Closing this issue, v19 includes a new DC library of CHD files (no unzipping necessary)
