### ISSUE TITLE
Close/Pause Kodi on Launch has no effect

### ISSUE THREAD

**Issue by edco** [zach-morris/plugin.program.iagl#17]
When running external RetroArch, the "Close Kodi on Launch" and "Pause Kodi on Launch" options appear to have no effect.

Because the game details screen (with the Launch, Trailer, Download and Close options) requires constant full-screen redraws, it causes Kodi to place a very high load on the CPU. This load remains once the game has launched, regardless of whether the close or pause options are selected. It is possible to alt+tab back to Kodi from RetroArch and see that the screen is still updating.

I'm running:
- Xubuntu 18.04
- Xfce (with compositing disabled)
- Kodi installed from the stable PPA (2:17.6+git20180430.1623-final-0bionic), also tested with the unstable PPA (2:18.0+git20180828.0901-beta1-0bionic)
- The Xorg modesetting driver

The hardware is a mini PC with:
- Intel 8350U CPU
- Intel UHD 620 onboard graphics (Mini-DP out)
- 8GB RAM
- 128GB SSD

**Comment by zach-morris** [comment]
Can you link a debug log?

**Comment by edco** [comment]
Sure: https://paste.kodi.tv/tugeyiyezu
I launched the game twice in this log session, first with pause enabled, then with close enabled. Each time I verified that the kodi-x11 process was still showing up with around 60% CPU usage.

**Comment by edco** [comment]
I've downloaded and installed the latest from git and it doesn't seem to have made any difference. Is there something I should look for in the logs? Any extra logging I can turn on to get a clearer idea of what's happening?

**Comment by edco** [comment]
Got it working now, but only if I update the launch command for each individual list. Is there some way to update them all at once? Happy to bust out sed to do it, just want to check I'm not missing something obvious.

**Comment by zach-morris** [comment]
Hmm, yes, it should work with the wizard, although I didn't try that.  I'll get that working / verify that works before closing.  Thanks

**Comment by edco** [comment]
I tried the wizard and it seems to ignore the pause-Kodi setting. I replaced the command in the XML file with 'none' and the wizard just set it to the standard command without apppause.

**Comment by zach-morris** [comment]
I think I have all this straightened out.  I released 2.0.4.  Can you confirm it works for you?

**Comment by edco** [comment]
2.0.4 works perfectly - the pause script is working, and the wizard updates the list files to enable/disable pausing.
