### ISSUE TITLE
Support for 32bit build of RetroArch

### ISSUE THREAD

**Issue by mikerogerz** [zach-morris/plugin.program.iagl#171]
Attempting to use the RetroArch_ra32.apk build via the External Launcher results in jumping back to the game list. I tried modifying the entries in external_command_database.xml to use the ra32-build-specific directories, but it didn't seem to help at all.

Example updated command:
`<launcher_command>/system/bin/am start --user 0 -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -n com.retroarch.ra32/.browser.retroactivity.RetroActivityFuture --es "LIBRETRO" "/data/user/0/com.retroarch.ra32/cores/opera_libretro_android.so" --es "CONFIGFILE" "%CFG_PATH%" --es "ROM" "%ROM_PATH%" --es "IME" com.android.inputmethod.latin/.LatinIME --activity-clear-top</launcher_command>`

If official support isn't planned, has anyone figured out how to do this manually? I'm specifically trying to load the 32bit build for MAME 2010 support, among other cores that aren't available in the 64bit version of RetroArch. Also, RetroArch 32bit works fine when used standalone.

**Comment by drinfernoo** [comment]
Ah, I made a PR to add explicit support for the aarch64 version... sometime last year. I didn't realize there was an ra32 version at the time 😅

**Comment by mikerogerz** [comment]
@drinfernoo I was just looking at your pull request. It looks like the changes I made should have worked. Any idea why it wouldn't? I'm not seeing anything else that would require changes besides the launcher command entries for the existing Android config.

**Comment by drinfernoo** [comment]
It may be possible that the arguments to the ra32 builds are different from the other... but I wouldn't think so.

Hard to say, and I haven't been using this add-on much anymore 🤷🏿

**Comment by zach-morris** [comment]
Fixed in v19 branch, will release shortly
