### ISSUE TITLE
Launch Dolphin Emulator android.

### ISSUE THREAD

**Issue by RyskiMod** [zach-morris/plugin.program.iagl#173]
Could you please include the option to Launch dolphin after download, ive tried by editing your RetroArch Open only command and failed, Im sure it will take you 2 secs :P

**Comment by QmwJlHuSg9pa** [comment]
Tangentially related: RetroArch Dolphin core has apparently been broken on Android for at least 18 months:
- https://github.com/libretro/dolphin/issues/92
- https://github.com/libretro/dolphin/issues/125

I can confirm that standalone Dolphin is working and would make for a suitable workaround at this point in time.

**Comment by zach-morris** [comment]
OK, i think I found the correct commands to send in this PR, i'll give it a try:
https://github.com/dolphin-emu/dolphin/pull/2144

**Comment by zach-morris** [comment]
For future reference, I found this amazing tool for pegasus that helps parse what commands are needed:
https://pegasus-frontend.org/tools/metagen-android/
