### ISSUE TITLE
Saturn games link not working

### ISSUE THREAD

**Issue by jellymunky** [zach-morris/plugin.program.iagl#178]
Tried to play panzer dragoon 1 and 2 and was receiving the error about requiring login.  Read through your FAQ about possible broken links.  Submitting ticket per instruction.

Console - Sega Saturn
Game - Panzer Dragoon 1 and 2 (US, EU and JP) all failed.

Confirmed my login worked on archive.

**Comment by zach-morris** [comment]
The archive has changed at archive.org.  A replacement is in work.

**Comment by jhonny-oliveira** [comment]
Any update on this?

**Comment by zach-morris** [comment]
Target is to release an update for v19 of Kodi, which is in release candidate now.  Hopefully I can get it ready for the actual release

**Comment by zach-morris** [comment]
Fixed in last commit [v18](https://github.com/zach-morris/plugin.program.iagl/commit/c13011b0e53bcebc346e1192df96e8ef0738422d), [v19](https://github.com/zach-morris/plugin.program.iagl/commit/984493085d32130269f0cbf2f074036dde6483df)
