### ISSUE TITLE
"Item not available" 403 errors in downloading display as "Archive requires account email and password in settings" 

### ISSUE THREAD

**Issue by djay** [zach-morris/plugin.program.iagl#180]
Full text of 403 page is
"Item not available
The item is not available due to issues with the item's content."

Currently getting this for dreamcast.

Confusing when user and password has been entered

**Comment by zach-morris** [comment]
Yep, the archive has changed (several of them have).  I'm working on some replacements, as well as better messaging for v19 (closing this one since I've already got an issue open for it).  Thanks for the report.
