### ISSUE TITLE
DEBUG: IAGL:  The Retroarch Core directory could not be found.  Defaulting to /usr/lib/libretro and addon.py issue

### ISSUE THREAD

**Issue by dicotom** [zach-morris/plugin.program.iagl#185]
**Latest IAGL and kodi 17.6 and odroid xu4 with Ubuntu 20.04 with RetroPie installed**

External Launchers -> My System Type -> Linux/Kodibuntu (odroid xu4)
External Launchers -> RetroArch App Location -> /opt/retropie/emulators/retroarch/bin/retroarch
External Launchers -> RetroArch System Folder -> /home/kodi/RetroPie/BIOS
 
It does not find the Retroarch Core directory
So I had to edit main.py and include all the /opt/retropie/libretrocores/lr-* directories

**If I choose as My System Type, RetroPie**

External Launchers -> My System Type -> RetroPie (not raspberry pi, but odroid xu4)
External Launchers -> RetroArch System Folder -> /home/kodi/RetroPie/BIOS 

and that is ok, as for the Retroarch Core directory, but although it lunches with:

 NOTICE: IAGL:  Sending Launch Command: "/home/odroid/.kodi/addons/plugin.program.iagl/resources/bin/applaunch_retropie.sh" 0 _SYS_ mame-libretro "/home/odroid/.kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/pacmanbl.zip"

which expanses correctly to:

/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame2003/mame2003_libretro.so --config /opt/retropie/configs/mame-libretro/retroarch.cfg "/home/odroid/.kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/pacmanbl.zip" --appendconfig /dev/shm/retroarch.cfg

kodi closes but game is not launched, launching the game from the console works.

in kodi.log found:

 ERROR: CPythonInvoker(8, /home/odroid/.kodi/addons/plugin.program.iagl/addon.py): script didn't stop in 5 seconds - let's kill it
12:51:31.337 T:2755652240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SystemExit'>
                                            Error Contents: <NULL>
                                            Traceback (most recent call last):
                                              File "/home/odroid/.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 4530, in onClick
                                                self.action_download_and_launch()
                                              File "/home/odroid/.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 4579, in action_download_and_launch
                                                IAGL_LAUNCH.launch(return_home=self.return_home) #Launch Game
                                              File "/home/odroid/.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 4141, in launch
                                                self.launch_success = self.launch_external(return_home=return_home)
                                              File "/home/odroid/.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 4325, in launch_external
                                                external_command = subprocess.call(self.external_launch_command,shell=True)
                                              File "/usr/lib/python2.7/subprocess.py", line 172, in call
                                                return Popen(*popenargs, **kwargs).wait()
                                              File "/usr/lib/python2.7/subprocess.py", line 1110, in wait
                                                if pid == self.pid:
                                            SystemExit
                                            -->End of Python script error report<--

Also please update the documentation, because if you change the settings in IAGL you need to run the wizard again in order for them to be red.

**Comment by zach-morris** [comment]
Thanks for the report, i'll add this to the list.
I'll note that v19 is going to be changed so that the user just points to the RA cfg file, and then the addon just parses out what it needs directly from there.

**Comment by zach-morris** [comment]
Fixed in v19 branch, will release shortly
