### ISSUE TITLE
KODI + IAGL + Retroarch In XBOX One (Dev Mode) Workaround

### ISSUE THREAD

**Issue by lukeraw93** [zach-morris/plugin.program.iagl#186]
Hi all, (noob alert) please forgive.

After some intresting messing around over the last couple of days i have managed to install KODI with IAGL & Retroarch onto my Xbox in dev mode. i have succesfully downloaded a ROM via IAGL and rather than booting retroarch through kodi, i ran it standalone and was able to use a USB drive to store roms from IAGL downloaded via the xbox to be ran in the retroarch app seperatley.

The only issue im currently encountering and i suspect this is due to the drive being external is the VFS error when trying to play larger games, So far i have ran sega mega drive roms with no problems. i also managed to run a "small" playstation one game.

In theory i was going to change the download path in KODI to a location on the Xbox where i could then use retroarch to run them seperatley, however due to the nature of the UWP system the only place i can get retroarch to locate that KODI also has access to is an external device. So far i have only used a USB pendrive, i have toyed with the idea of tring it with an external HDD but i fear the same thing would happen with the VFS error.

So all in all, ive a small work around for smaller games but thats all.

P.S forgive me if this is already known and used method, i am very new to this.

Thanks

UPDATE: So ive realized the VFS error is due to the core emulator im using PCSX. so i changed to Beetle PSX in the cores and was able to sucessfully boot from usb drive a game i had downloaded from IAGL in KODI. i had a few issues with crackling sound however which i will further look into.

Another Idea i had was using the Xbox built in browser microsoft edge. so i logged into to remote connection via Edge on the xbox went into the file browser and was succesfully able to move a game i had downloaded from IAGL in KODI onto my pendrive, into the Retroarch Downloads folder. this then allowed me to play the game with PCSX, which in my opinion is a ot smoother.

Thanks

**Comment by zach-morris** [comment]
Thanks for the report.  Do you know if an XBOX in dev mode can mount an SMB drive?  I'm working on v19 of the addon currently and it should support saving to a network location

**Comment by zach-morris** [comment]
Closing this issue, I think it's overall covered by [this issue](https://github.com/zach-morris/plugin.program.iagl/issues/42). Long story short, it's not a great solution atm for XBOX
