### ISSUE TITLE
Kodi 19 (Matrix) Support

### ISSUE THREAD

**Issue by jason-oliveira** [zach-morris/plugin.program.iagl#188]
Seems Kodi has moved everything to Python3 in version 19, and all the AddOns need to be updated accordingly.
This isn't one of those "Everything is broken for 3 minor versions" sort of release, unlike 17 or 18, so please let us know where to send beer to facilitate a rapid transition.

**Comment by Philps** [comment]
i think its in the works. See: https://github.com/zach-morris/plugin.program.iagl/pull/179#issuecomment-722029829

@zach-morris: would be great if you cold push the current stand to a branch for wider testing

**Comment by zach-morris** [comment]
I'm close to release.  It's in good shape, see the branch [here](https://github.com/zach-morris/plugin.program.iagl/tree/v19).  Feel free to beta test it!

**Comment by Philps** [comment]
1.) make sure you have a Matrix compatible Version of Youtube installed, otherwise you will recieve a dependencie error 

2.) Assertion within Config Wizard -> Let IAGL choose default media player

2021-02-23 07:58:42.571 T:1244    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument of type 'NoneType' is not iterable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\run_IAGL_wizard.py", line 189, in <module>
                                                       if not any([y in addons_available for y in [x for x in RP_DEFAULTS.get(game_list_id) if x] if y]):
                                                     File "C:\Users\dell\AppData\Roaming\Kodi\addons\plugin.program.iagl\run_IAGL_wizard.py", line 189, in <listcomp>
                                                       if not any([y in addons_available for y in [x for x in RP_DEFAULTS.get(game_list_id) if x] if y]):
                                                   TypeError: argument of type 'NoneType' is not iterable
                                                   -->End of Python script error report<--
												   
3.) Woudl be great if the Check Login Credentials returns a Dialogbox with value good/bad, at the moment there is no feedback ( maybe indicate login is valid )					   
												   
												   2021-02-23 08:00:30.673 T:3404    ERROR <general>: CScriptInvocationManager::ExecuteAsync - Not executing non-existing script special://home/addons/plugin.program.iagl/check_archive_org_login.py


Will continue testing, so far so good. Keep up the good work!

**Comment by zach-morris** [comment]
Thanks, I think I got all three of those

**Comment by Philps** [comment]
great!

Under Android/FireOS, i am not allowed to download/store a game when launching emulator. I wonder if the default store path has been changed? I will provide debugs logs soon and open a separate Issue

**Comment by zach-morris** [comment]
@Philps, its likely Androids security getting in the way.  See [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#15-im-on-android-and-i-cant-change-the-download-path-for-games).

**Comment by Philps** [comment]
I'll add an SD Card and let you know

**Comment by mjkapkan** [comment]
I upgraded to Matrix Today, got a dependency error briefly, then IAGL no longer showed up. Cleaned up, installed repoistory from scratch, still only the BIOS tool is listed in the repository. Let me know how can I help.

**Comment by zach-morris** [comment]
The addon is not in the repository yet.  See the third post in this thread.

**Comment by zach-morris** [comment]
v3.0.0 is released in the repository.  There's a couple things not perfect, but I think it's in a 'good enough' state to release and get people using it   :rocket:
