### ISSUE TITLE
Latest version of KODI incompatible with IAGL

### ISSUE THREAD

**Issue by pirsir76** [zach-morris/plugin.program.iagl#192]
Just as the title says.
Can anyone provide an easy fix for this? Perhaps someone can provide basic instructions to downgrade to the last working version of KODI?

More information: the version of KODI that's incompatible is version 19. (Matrix skin version.)

**Comment by zach-morris** [comment]
You can manually install 2.1.8 from [here](https://github.com/zach-morris/repository.zachmorris/tree/master/plugin.program.iagl)
