### ISSUE TITLE
Incomplete Translation for v3

### ISSUE THREAD

**Issue by zach-morris** [zach-morris/plugin.program.iagl#193]
As the title says.  I've updated the strings in IAGL for v3.0 quite a bit.  The strings.po file is a bit of a mess because there are so many strings now (the organization just isn't as clear as it was before).

Pinging those that assisted with translation previously @roliverosc , @LITUATUI , @Intel11 .  If you have the time, that'd be awesome.  Otherwise I'll look into some sort of automation of language translation

**Comment by doctornono** [comment]
I'm ok for french translation.
Where i can find the strings ?

**Comment by Intel11** [comment]
Hi

https://github.com/zach-morris/plugin.program.iagl/tree/main/resources/language

**Comment by doctornono** [comment]
Thanks, i read before strings.po in french, but all the strings seem to be translated but not in IAGL

**Comment by jose1711** [comment]
The issue seems to be with plot tag of xml files and random play section.

**Comment by zach-morris** [comment]
IAGL v4 is using some AI services to automatically translate everything. I'm sure it's not perfect, but hopefully it's serviceable.

For future reference, all strings.po files are generated from the xls table here (eventuall this will be in the main branch):
https://github.com/zach-morris/plugin.program.iagl/blob/v4/resources/data/language.xlsx
