### ISSUE TITLE
Updating to 3.00 

### ISSUE THREAD

**Issue by buddy9507** [zach-morris/plugin.program.iagl#195]
Trying to update IAGL to 3.00 but it says the dependency on xbmc.python version 3.00 could not be satisfied. Will this be fixed? Love this game add on a lot!

**Comment by zach-morris** [comment]
Are you using Kodi v19 (Matrix)?  The new version is only compatible with Kodi v19

**Comment by buddy9507** [comment]
I’m using 18.9 and using the repository 1.0.0

**Comment by zach-morris** [comment]
Yes, the addon has moved on to v19 in the repository.  You can still install the old version via zip as suggested.

See [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#14d-i-try-and-download-a-game-and-i-got-an-error) for your other error.

**Comment by githuborer** [comment]
I don't want to update to Matrix for a long time cos it will break a lot of addons I have. Do you still maintain the v2 version for Kodi 18 ?
