### ISSUE TITLE
The dependency on xbmc.python of version 3.0.0 could not be resolved. 

### ISSUE THREAD

**Issue by beta-tester** [zach-morris/plugin.program.iagl#197]
did something changed iwith the add-on?
i see this message from time to time when i start LibreELEC...
"CAddonInstallJob[plugin.program.iagl]: Die Abhängigkeit auf xbmc.python in Version 3.0.0 konnte nicht aufgelöst werden."
{"The dependency on xbmc.python of version 3.0.0 could not be resolved."}

i also can not update the add-on by manually click the Update option.

**Comment by zach-morris** [comment]
The addon in the repository is for Kodi v19 now (which is the python 3.0.0 dependancy).
Users of Kodi v18 or earlier have to manually install v2.X of the addon from [here](https://github.com/zach-morris/repository.zachmorris/tree/master/plugin.program.iagl) (there is no more repository for the old version).

**Comment by beta-tester** [comment]
thank you. now i was reading the announcement for Kodi 19 and all the changes... now i understand.
