### ISSUE TITLE
Search option

### ISSUE THREAD

**Issue by NerdFlix** [zach-morris/plugin.program.iagl#2]
Hi Zach,

first of all thanks for this new project, it looks awesome and more organized than IARL(game searching). I'd like to know if it is possible to have a search option, like the user type Mario and IAGL finds all Mario games available in the addon for all Nintendo platforms, making it easier to create custom games collections like the ones you asked users to share in IARL.

Thanks in advanced.

**Comment by zach-morris** [comment]
Yeah, thats coming

**Comment by NerdFlix** [comment]
Thanks :)

**Comment by drinfernoo** [comment]
Will this be using a similar interface to IARL for search? That dialog was a bit overwhelming, and it always crashed my system.

**Comment by zach-morris** [comment]
Yes, it wasn't that great, I'll admit.  I thought a context menu search option available on categories and individual lists would be simple.  I'm open to ideas though

**Comment by drinfernoo** [comment]
My biggest complaint against the old search was that there was essentially no contrast (17.6, multiple skins), making it very difficult to see what options you were selecting. Searching by list would be fine, but would make it a bit tedious to search for all the games in a series (across multiple consoles), for example.

**Comment by NerdFlix** [comment]
My two cents: Yes the old search screen contrast made difficult to see the options we were selecting. I agree with drinfernoo, searching for a game like street fighter across all platforms would be tedious, maybe a single list for each search would be good, but instead of creating a list with all info about every game(like IARL.Extras) would make an unecessary and huge result file. I think a simple line for every game found would be enough, each line calling the corresponding game routing/route in dat file, similar to Super favourites addon:
example: `
<favourite name="Super Mario RPG - Legend of the Seven Stars" thumb="http://i.imgur.com/G4oWefq.jpg">ActivateWindow(10025,&quot;plugin://plugin.program.iarl/Emulator/SNES_ZachMorris/Game/Super+Mario+RPG+-+Legend+of+the+Seven+Stars+%28USA%29?sf_options=desc%3D%26_options_sf&quot;,return)</favourite>`

About the interface for the search, you could use this guy idea below, not so complete like custom skin but simpler and efficient:

http://romanvm.github.io/script.module.pyxbmct/examples.html
https://github.com/romanvm/script.module.pyxbmct

**Comment by NerdFlix** [comment]
I made collections lists using the search code from IARL, taking the result lists and parsing them to be opened in Super favourites addon, that's the result I want to achieve with the result lists created by IAGL, if possible.

Collection lists:
https://youtu.be/iL-kFcKklCQ?t=598

**Comment by zach-morris** [comment]
Included in 2.0.1
