### ISSUE TITLE
IAGL creating m3u in wrong folder

### ISSUE THREAD

**Issue by Pintglass** [zach-morris/plugin.program.iagl#20]
I have installed iagl in kodi leia on windows 10
when i download a game using the playstation list the game works fine launching retroarch, but then any subsequent download fails to launch because the m3u file thats generated is placed in the first game folder instead of its own folder, also the m3u file contains the cue of the original download and the subsequent download instead of just containing the cue of the latest download this behaviour is easy fixed by copying the m3u to the correct folder and removing the wrong cue from the file.
Just wondered if this can be rectified to save having to move the file manually.
I have not checked if this behaviour  is the same for other lists.

**Comment by zach-morris** [comment]
Thanks for the report, I'll take a look at this.  m3u support was on my list of things to update for the various cores that are getting updated m3u support as well (amiga being the big one)

**Comment by drinfernoo** [comment]
I haven't run into any .m3u files in my IAGL escapades. Am *I* doing something wrong?

**Comment by zach-morris** [comment]
PS1 is currently setup to automatically make m3u files and launch a game with them (this particular issue pointed out that there's an issue with the automatically generated file, I believe the latest commit fixed it, but still testing).  I just updated the Atari ST game list to support automatic m3u file generation.  I'll be adding back in Amiga soon as well as the retroarch core is adding m3u disk support.  It is really helpful for multi disk games.

**Comment by zach-morris** [comment]
This should be fixed with 2.0.5, however I also updated the postdl command to launch a cue file for PS1.  Can you confirm this is working for you?

**Comment by Pintglass** [comment]
This is now working fine for me.

**Comment by zach-morris** [comment]
Thanks!
