### ISSUE TITLE
Set up wizard issue

### ISSUE THREAD

**Issue by pirsir76** [zach-morris/plugin.program.iagl#203]
In setup Wizard (the one with the cool sounds)
It asks:
Cache Lists to Disk
Do you want IAGL to pre-cache all game lists?
This process takes several minutes but will speed up browsing later.

If I choose yes, when I get to "Processing Game List: The Powder Toy" it comes up with an error saying:
Add-on error: check log for more information.

I'm not only reporting this issue I had but I would like to know where I can access the log the error message talks about.

**Comment by zach-morris** [comment]
The error is in the Kodi log.  If possible, turn on debug logging and recreate the issue.  Instructions [here](https://kodi.wiki/view/Log_file/Easy).

**Comment by pirsir76** [comment]
"What system type are you using?"

I'm using an NVIDIA Shield Pro 2019 edition.

**Comment by zach-morris** [comment]
There is also an official addon in the Kodi repository called 'Logfile Uploader', that does the hard work for you (much easier if you dont have access to the filesystem)

**Comment by pirsir76** [comment]
Thanks, that would be easier for me. I'll try that.   :)

**Comment by zach-morris** [comment]
I was able to reproduce and fix this on an android phone.  For some reason there's a specific python function that acts differently on Android... At any rate, should be fixed in the next update.
