### ISSUE TITLE
Ask about: Favorites

### ISSUE THREAD

**Issue by Intel11** [zach-morris/plugin.program.iagl#207]
Thanks for the great job at IAGL and the trailers in 3.0.2 :)

1.- How can I delete a favorites list? If there is no way, can it be implemented by right clicking?

![imagen](https://user-images.githubusercontent.com/25161862/110461970-1e82aa80-809e-11eb-9bba-d5352b2a49d4.png)

2.- How can I delete a game added to a favorites list? If not, can it be implemented in the right click?

![imagen](https://user-images.githubusercontent.com/25161862/110462244-6bff1780-809e-11eb-8c19-9a3f43c3b2ae.png)

Thanks.

**Comment by zach-morris** [comment]
Thanks for the report, both to be implemented

**Comment by zach-morris** [comment]
Working now in 3.0.3
