### ISSUE TITLE
External Launcher error when RA App Path / CFG Path is not defined (but other emulator paths are defined)

### ISSUE THREAD

**Issue by grupoleon** [zach-morris/plugin.program.iagl#208]
Me again, but this time I left a decent donation on the site so I don't feel too bad about submitting two issues in the same amount of days.

I've tried to set external emulators in the settings (tried a few options there, have the right path)
when I tried to select it in the game list settings I receive and error about external emulators not set

Here is the kodi log - https://paste.kodi.tv/wamacahopo.kodi
[Pictures.zip](https://github.com/zach-morris/plugin.program.iagl/files/6111061/Pictures.zip)

**Comment by zach-morris** [comment]
So I understand correctly, you're trying to use a different emulator (non-Retroarch)
You want to use Demul (although I see Mednafen set as the exe)?

After you enter that info in the addon settings, then you'll need to set the launcher for that game list.
Select the game list, select update launcher to external, then it will bring up a list of emulator/launchers to choose from.  Demul should be at the bottom of the list and then the addon will fill in the command based on where you told it the exe was.

After that is set, you can verify the command that will be sent by selecting the game list, then context menu<"View List Settings", which will let you see at the bottom what command will be used.

I do see an error in the log, but can't determine why it's set (if you can turn on debug that would also help).  Where in the flow above does this break?

**Comment by zach-morris** [comment]
I see potentially another problem.  You don't have the Retroarch app path set at all, and based on the code I'm looking at thats probably where it's getting tripped up.  That should probably be fixed, but a workaround right now is to set the two settings in your first picture:  Retroarch App Path, Retroarch CFG Path

**Comment by zach-morris** [comment]
OK, it was an easy fix.  I was able to reproduce it after all.  The workaround listed above does work, but the fix will be in the next release.
