### ISSUE TITLE
cd-i

### ISSUE THREAD

**Issue by camatthew** [zach-morris/plugin.program.iagl#21]
cd i games just restart kodi

**Comment by zach-morris** [comment]
I need a log for any and all issues.

**Comment by zach-morris** [comment]
Any input on this one?  Otherwise I will close it.  I just tried CDI and it works for me.

**Comment by zach-morris** [comment]
Closed due to lack of info

**Comment by camatthew88** [comment]
can you try it with qemu arm running librelec

**Comment by camatthew88** [comment]
my main problem is that i left my rpi at school and i am busy turning it into an arcade. When i am finished i will test it.

**Comment by drinfernoo** [comment]
@zach-morris I think he wanted you to test it on LibreELEC for him.
