### ISSUE TITLE
Problem strings.po

### ISSUE THREAD

**Issue by Intel11** [zach-morris/plugin.program.iagl#210]
Hello, I have updated the file strings.po Spanish (Mexico)

And I have problems with this part (strings.po english):

![imagen](https://user-images.githubusercontent.com/25161862/110745387-2b6fdd00-8209-11eb-8091-3ba848811d17.png)

strings.po spanish (Mexico) : 

![imagen](https://user-images.githubusercontent.com/25161862/110745457-493d4200-8209-11eb-9bc8-6250a647f9a9.png)

But in IAGL on kodi, when I select MAME 2003, it appears to me like this:

![imagen](https://user-images.githubusercontent.com/25161862/110745510-5fe39900-8209-11eb-846c-33c4e981c736.png)

Do I have to change the string somewhere else?

Thanks.

**Comment by zach-morris** [comment]
Thanks for the report.  Thats a different string currently.  I still have to localize the page you have shown.  It's on my to do list.  I'll reuse strings where possible.

Currently the only addon browsing directory thats localize is the top directory ([this one](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/data/databases/browse_database.xml)).
I still have to localize others in [this](https://github.com/zach-morris/plugin.program.iagl/tree/main/resources/data/databases) directory.  I had planned on adding the following:
- [Choose Database](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/data/databases/choose_database.xml) (the one you have pictured)
- [Categories Database](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/data/databases/categories_database.xml)
- [Search Database](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/data/databases/search_database.xml)
- [Random Database](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/data/databases/random_database.xml)

There are other databases in that folder as you can see, but I didn't think it would be worth localizing the others.   In addition, the plot/description in these is not yet localized, I wasn't sure if that was worth it either.  What do you think?

**Comment by zach-morris** [comment]
Take a look at 3.0.3, there are many new strings now available, hopefully that covers everything you think should be translatable.  Thanks again for supporting this effort!
