### ISSUE TITLE
IAGL suggestion

### ISSUE THREAD

**Issue by dicotom** [zach-morris/plugin.program.iagl#211]
Hi,

Wouldn't it be much much much better if you would make your own front-end for IAGL?

What is the purpose of Kodi? You needed to rewrite IAGL for kodi 19 which does not make sense, when you could make your own front-end.

**Comment by zach-morris** [comment]
There's a lot to consider in that question.
Kodi provides the multi-os available framework for the front end, which in my opinion is invaluable.  I can't think of, off the top of my head, another framework that would provide the multi-os, multi-input (keyboard, controller, remote), multi-skin capabilities that Kodi does while providing the add-in capability that it does.  Maybe they exist, but I'd likely trade re-writing python code for writing code in another language and then some.

**Comment by dicotom** [comment]
Yes, I understand, but I was not thinking about another framework, but writing a front-end in python, which will obviously work on any os.

**Comment by zach-morris** [comment]
Closing for now.  Maybe someday, or if I'm stuck at home during the next pandemic....  I'm envisioning like an electron app or something only containing IAGL
