### ISSUE TITLE
IAGL NAOMI does not work with Retroarch (flycast)

### ISSUE THREAD

**Issue by asomolinos** [zach-morris/plugin.program.iagl#212]
Hi @zach-morris,

I am trying to run NAOMI games from IAGL using Retroarch FlyCast in Android but it gives an error because the CHD is not downloaded in a folder with the rom name (https://docs.libretro.com/library/flycast/).

Example (MAME ID=ikaruga)
- [ROM FOLDER]/ikaruga.zip
- [ROM FOLDER]/ikaruga/gdl-0010.chd

This can be configured?

Thanks!

**Comment by zach-morris** [comment]
Thanks for the report.  Updated the archive and tested and should work now.  The new game list will be included in the next addon update.
