### ISSUE TITLE
Game languages taken away?

### ISSUE THREAD

**Issue by pirsir76** [zach-morris/plugin.program.iagl#213]
Hello Zach,

I noticed in the latest IAGL when I view the games, it no longer tells me which language they are in.
I have to download a few of them now or else I might get the Japanese version.

It would be a lot better, if it was like before, when I was viewing the games on the list, it always states which region/language the game is for.

**Comment by zach-morris** [comment]
If you mean the language thats listed in the game name, thats still there.

Change the 'Clean Game Titles' option in addon settings:
<img width="796" alt="Screen Shot 2021-03-21 at 9 27 10 AM" src="https://user-images.githubusercontent.com/12554283/111912612-add97780-8a27-11eb-8e8f-e22566875f00.png">

Then after you do this you need to reset the cached game list names. To do that, you can:
- 'Refresh Game List' from the context menu for each game list you want to refresh
- Or re-run the wizard
- Or in advance settings you can 'Clear All Cache'

Any one of those will reset the naming.  I'll update the wiki to clarify how to reset the game list after you update certain settings.

**Comment by pirsir76** [comment]
I tried un-checking "Clean Game Title" and then in advance settings did 'Clear All Cache'.
And it worked thanks.

My suggestion is to make it the default so that you can see which language the games are in.
I play many systems through IAGL and it comes in real handy to know the region/language of the games.

Thanks Zach!

**Comment by zach-morris** [comment]
Agreed.  I did, and it'll be in the next release
