### ISSUE TITLE
Can't seem to get Naomi working

### ISSUE THREAD

**Issue by pirsir76** [zach-morris/plugin.program.iagl#215]
Hello,

I had Naomi games emulating fine on previous versions of IAGL.
The emulator which worked was "Retroarch Flycast (Dreamcast/Naomi)".
But for some reason that emulator just comes up with a blank screen for me now when I try and launch Naomi games.
I have tried all the Naomi emulators and none seem to work for me.
I have also tried launching the games both zipped and un-zipped and I've had no luck with that.
System = Android  Device = NVIDIA Shield Pro 2019
(The issue might be something to do with the Post DL Command? I'm not sure.)

My main theory is that it's a BIOS issue.
Can anyone confirm whether or not I need a BIOS for Naomi emulators to work?
If so, where should I place the BIOS files?

I took a couple of screenshots to help identify the issue:

![DSC00591](https://user-images.githubusercontent.com/57454066/112347688-fee2b780-8d16-11eb-906c-bb22a957f231.JPG)
![DSC00592](https://user-images.githubusercontent.com/57454066/112347701-01451180-8d17-11eb-9b97-3bb216945fad.JPG)

**Comment by zach-morris** [comment]
I [just updated that game list](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/data/dat_files/Naomi1_ZachMorris.xml), ref [this issue](https://github.com/zach-morris/plugin.program.iagl/issues/212).  It's not released in the repository yet.  There was an issue with the old archive.  You can download and test if you like.

**Comment by pirsir76** [comment]
I think I will just wait till it's released in the repository.
So, I'm guessing if I wait until the next version of IAGL the problem will be fixed?

**Comment by zach-morris** [comment]
Updated in 3.0.3, should work for you now hopefully
<img width="786" alt="Screen Shot 2021-05-04 at 4 02 13 PM" src="https://user-images.githubusercontent.com/12554283/117347881-6fc0d780-ae5e-11eb-909a-971fe2da0dd9.png">

**Comment by pirsir76** [comment]
Tested, Naomi works great now,
Thanks Zach!
