### ISSUE TITLE
how to solve the vfs.rar problem on an raspberry pi 4?

### ISSUE THREAD

**Issue by lizbethmutterhunt** [zach-morris/plugin.program.iagl#216]
header is body, telling me not available: the newer libarchive.vfs? it's not available but don't think has to do with the python3.... kodi-addoin on arch is building failure I guess depreciated, telleing me:

```
../src/Helpers.h:30:10: error: ‘ADDON_LOG_NOTICE’ was not declared in this scope; did you mean ‘ADDON_LOG_FATAL’?
   30 |     case ADDON_LOG_NOTICE:
      |          ^~~~~~~~~~~~~~~~
      |          ADDON_LOG_FATAL
/home/lizbeth/kodi-addon-vfs-rar/src/vfs.rar-2.3.1-Leia/lib/UnrarXLib/../../src/Helpers.h:36:10: error: ‘ADDON_LOG_SEVERE’ was not declared in this scope; did you mean ‘ADDON_LOG_ERROR’?
   36 |     case ADDON_LOG_SEVERE:
      |          ^~~~~~~~~~~~~~~~
      |          ADDON_LOG_ERROR
make[2]: *** [lib/UnrarXLib/CMakeFiles/unrarxlib.dir/build.make:76: lib/UnrarXLib/CMakeFiles/unrarxlib.dir/archive.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:153: lib/UnrarXLib/CMakeFiles/unrarxlib.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

```

any help appreciated!

lizbeth

**Comment by zach-morris** [comment]
Are you trying to build it yourself?  It should be available from the official repository, no?
I do see it available [here](https://test.libreelec.tv/addons/9.80.11/)

**Comment by lizbethmutterhunt** [comment]
yes, I tried to built it myself as it is not in the repo. Today I compiled libarchive.org source but doesn't seem to work. the plugins for the arch-pi4 are partly still on Leia! 

I tried your link, but Kodi couldn't install the .zip file (not for v7 nor vor v8), probably need aarch64, telling me "invalid structure"!

**Comment by zach-morris** [comment]
Ah, ok.  Yeah i couldn't find aarch64 in the normal addon repository for some reason, but it is at some mirrors ([this](http://mirrors.mit.edu/kodi/addons/matrix/vfs.libarchive%2Bandroid-aarch64/) one for example, I just searched for vfs.rar aarch64)
Specific to building it I can't comment on what the issue is.  You might get more support with an issue in the repository [here](https://github.com/xbmc/vfs.rar/issues).

**Comment by lizbethmutterhunt** [comment]
Dear Zach Morris, 

after closing the issue I found the right kodi-addon at: https://aur.archlinux.org/packages/kodi-addon-vfs-rar-git/ . It makes a diffference using the -git in the clone clommand, because without it, it's for Leia. Thx for the support and I'm proud to make a discussion with suc a huge developer and programmer as you! My thumb goes up and and on the Joystick-Button to the left!
