### ISSUE TITLE
IAGL crashing on LibreELEC 10 Beta 5

### ISSUE THREAD

**Issue by Grandma-Betty** [zach-morris/plugin.program.iagl#217]
Please have a look here, where I already posted my issue:
[Link](https://forum.libreelec.tv/thread/24187-iagl-internet-archive-game-launcher-most-games-not-working/)
Any help appreciated, thank you.

**Comment by zach-morris** [comment]
Thanks for the report.  I'm not sure exactly whats causing the issue, but it boils down to the downloaded game not unzipping using vfs.libarchive:
```
archive_tool: set to use vfs.libarchive
Create - unsupported protocol(archive) in archive:/... game.zip/
```

**Comment by zach-morris** [comment]
I believe this is fixed on the LibreElec side, please let me know if the issue persists
