### ISSUE TITLE
repository zipfile error

### ISSUE THREAD

**Issue by Pintglass** [zach-morris/plugin.program.iagl#22]
Hi 
I tried installing your program with the repository zip file but it fails to install. 
I was trying this, as i see you have updated the program with changes to the post download actions, is this to try & fix the issues i was having with the playstation games being in the wrong folder and the m3u being incorrect?

**Comment by Pintglass** [comment]
This is all i get from the logs

[kodilog.txt](https://github.com/zach-morris/plugin.program.iagl/files/2466700/kodilog.txt)

**Comment by zach-morris** [comment]
I can't recreate the error.  The log makes it seem like there's a problem with the zipfile, but you should be able to download it on your computer and verify you can unzip it in windows normally.

The file is the one linked in the wiki [here](https://github.com/zach-morris/repository.zachmorris/raw/master/repository.zachmorris/repository.zachmorris-1.0.0.zip).

**Comment by Pintglass** [comment]
I can manually open the zip file fine on windows.

**Comment by zach-morris** [comment]
Yes, installing on the latest beta works (on OSX at least).  This particular zipfile hasn't been updated for over 3 years, so nothing has changed

**Comment by Pintglass** [comment]
I'll try it on OSX to see if it works for me on there.

**Comment by Pintglass** [comment]
I get the same error trying to install on OSX I must be doing something wrong 
I am suppose to just install it using the zip file in Kodi not adding a repository.

**Comment by zach-morris** [comment]
You can do either.
Install the respository [zipfile](https://github.com/zach-morris/repository.zachmorris/raw/master/repository.zachmorris/repository.zachmorris-1.0.0.zip)
or install the addon [zipfile](https://github.com/zach-morris/repository.zachmorris/blob/master/plugin.program.iagl/plugin.program.iagl-2.0.4.zip?raw=true) (latest version is linked)

**Comment by zach-morris** [comment]
@Pintglass , did you ever get this sorted out?

**Comment by zach-morris** [comment]
Closing without additional info

**Comment by zach-morris** [comment]
I reuploaded the [zipfile](https://github.com/zach-morris/repository.zachmorris/blob/master/repository.zachmorris/repository.zachmorris-1.0.0.zip?raw=true) and retested it on both windows and OSX, both worked with the latest Kodi v18 beta.  You can give it another try.

**Comment by Pintglass** [comment]
Sorry only just got to try this and can confirm the re-uploaded zip works OK.
