### ISSUE TITLE
Games download but get deleted after a restart

### ISSUE THREAD

**Issue by AwesomeAsh313** [zach-morris/plugin.program.iagl#227]
I am running LibreElec (BETA RELEASE for Kodi Matrix) using IAGL to download games and play them.

Smaller games like NES or SNES games are fine and I'm not bothered having to re-download them after every restart, but bigger games like PSX games can often be over a gigabyte big in file size, and it's quite annoying using my bandwidth to download games like Crash Bandicoot or Ace Combat.

If there's a configuration option or an actual issue, an answer would be greatly appreciated!
Thanks in advance.

**Comment by zach-morris** [comment]
Yes, you have two options, either update the cache size in addon settings, or update the download location for the game.  both are covered [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to).

**Comment by AwesomeAsh313** [comment]
Thank's Zach :D
