### ISSUE TITLE
A very singular request

### ISSUE THREAD

**Issue by boios** [zach-morris/plugin.program.iagl#228]
In your old project (https://github.com/zach-morris/plugin.program.iarl/blob/main/resources/data/external_command_database.xml) I found a mention about "freej2me_libretro.dll" (the retroarch core of freej2me **for Windows**). Do you happen to still have that file by any chance? Or can you point me to a source where I can download it? Because it is non existent on the web. Thank you.

**Comment by zach-morris** [comment]
Unfortunately I don't have it, the command database is automatically generated based on what was in the libretro buildbot at the time, and it looks like they removed that core.

The source code for it is here:
https://github.com/hex007/freej2me

And you'd likely have to try and compile it yourself.  Just looking at the repository, doesn't look like it's being actively developed.  Theres a retropie forum linked in the readme, they might be able to help.

**Comment by boios** [comment]
I totally understand, thank you for your time

Il mar 14 set 2021, 20:50 Zach Morris ***@***.***> ha scritto:
