### ISSUE TITLE
"Scrapers" instead of packaged .dat files?

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#23]
Couldn't this be setup to scrape all the information from the web server, rather than having to maintain your own .dat files for everything?

**Comment by zach-morris** [comment]
I dont think so, not for this project.  It's setup this way to really take the painful scraping part of projects like retropie, emulation station, etc out of the equation.  What kind of feature are you looking for as the end goal?

**Comment by drinfernoo** [comment]
I only recommended it as a way to make your code potentially easier to maintain in the long run, and to potentially save some work (and drive space) of maintaining and packaging many separate (and **verbose**) .dat files. If that's not a feasible solution, or not in the vision, that makes sense.

**Comment by zach-morris** [comment]
I do have some scripts, scrapers, etc in the background that help me generate the dat files if / when some of the game files change.  I'm actually working on a separate project to package that info up to become (another) games database and scraper.  That should be released at some point so it could in theory be used as a general Kodi/Retropie/whatever scraping source.

**Comment by githuborer** [comment]
Hi. I extracted lots of direct url links from archive.org for xml (dat) files but scared to add all info for covers..etc by hand. It will be possible with your scrapper to add all these infos automatically ?

**Comment by zach-morris** [comment]
Not at the moment, no. There's no scraping capability provided by my addon.  You're probably going to be better off saving those games your interested in locally, then scraping with a different addon like [AEL](https://github.com/Wintermute0110/plugin.program.AEL).

Closing this for now with the action for adding extra list functionality eventually.
