### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by aanderse** [zach-morris/plugin.program.iagl#232]
Could you please tag a new release when you get a chance? Thanks!

**Comment by zach-morris** [comment]
Sure, i take it thats how whatever system your using is grabbing releases?  Or can it grab releases from:
https://github.com/zach-morris/repository.zachmorris/tree/master/plugin.program.iagl

**Comment by aanderse** [comment]
Sounds good! Thanks again.

**Comment by zach-morris** [comment]
[Done](https://github.com/zach-morris/plugin.program.iagl/releases/tag/3.0.5)

**Comment by aanderse** [comment]
Great! Thank you so much @zach-morris :tada:
