### ISSUE TITLE
Launching MSU rom hack game

### ISSUE THREAD

**Issue by grupoleon** [zach-morris/plugin.program.iagl#236]
Greetings and happy holidays.

Was hoping to log this issue as I started playing a Zelda 3 rom hack.  I am having an issue where IAGL sends the wrong file to retro arch.  instead of sending the .SFC file it sends the .MSU file.

I have tested the game runs fine with retroarch, both loading it via the gui and command line.

**My own command line test that works successfully:**
`C:\Users\user\AppData\Roaming\RetroArch\retroarch.exe -L "C:\Users\user\AppData\Roaming\RetroArch\cores\bsnes_hd_beta_libretro.dll" "X:\Legend of Zelda, The - A Link to the Past (USA).sfc" --verbose
`

**Kodi+IAGL command from the log file:**
`INFO <general>: IAGL:  "C:\Users\user\AppData\Roaming\RetroArch\retroarch.exe" -L "C:\Users\user\AppData\Roaming\RetroArch\cores\bsnes_hd_beta_libretro.dll" "X:\Legend of Zelda, The - A Link to the Past (USA).msu" --verbose`

Lastly, I removed the MSU as a test and Kodi+IAGL sent the right .SFC file.  Log reflected the .sfc and game launched.

**Comment by zach-morris** [comment]
Hmm.  I cant recreate this issue.  The SNES hacks game list doesn't even have any MSU files in it.  Is the MSU file something auto generated from retroarch?

**Comment by grupoleon** [comment]
hey zach,  thanks for taking a look at this.  attached is the log file with debug option turned on.

RE your .MSU question - this is hacked rom and, retro arch still uses the SFC file but the msu file is to allow higher definition music (https://www.romhacking.net/hacks/2234/).  The msu came with the package and it is not added by retroarch and it lives on the same directory level as the SFC.

You may also be interested in that I patched the SFC file that IAGL download to my destination folder. 
[kodi.log](https://github.com/zach-morris/plugin.program.iagl/files/7824528/kodi.log)

**Comment by zach-morris** [comment]
OK, I think this patch will fix it.  You can test it locally by replacing the utils.py with the latest one [here](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/lib/utils.py) on git.

**Comment by grupoleon** [comment]
works!  thank you so much.
