### ISSUE TITLE
pcsx-rearmed memory card location

### ISSUE THREAD

**Issue by drrak** [zach-morris/plugin.program.iagl#242]
When I was able to fix the problem with the controller ([link](https://forum.kodi.tv/showthread.php?tid=287826&pid=3064148#pid3064148)), now I have a problem with the memory card. I do not know where it is. I checked a few locations but nothing is there, although the memory card works. E.g.:
Userdata\addon_data\game.libretro.pcsx-rearmed\save

**Comment by zach-morris** [comment]
This again isnt' something IAGL does.  This is a function of Kodi.
However I checked and the memory card saves are saved in the same location as the game files.
Example:
```
userdata/addon_data/plugin.program.iagl/game_cache/NBA Hangtime (USA).bin
userdata/addon_data/plugin.program.iagl/game_cache/NBA Hangtime (USA).cue
userdata/addon_data/plugin.program.iagl/game_cache/NBA Hangtime (USA).sav **
```

Saves made automatically by Kodi, when you exit a game for example are in:
```
userdata/Savestates/InGameSaves/NBA Hangtime (USA).cue.sav
```

**Comment by drrak** [comment]
I am not asking for a stupid sav file, but for a memory stick 😡 I want to use my save from other emulators.
