### ISSUE TITLE
Please make the download part to be more easy and eficient 

### ISSUE THREAD

**Issue by odball0** [zach-morris/plugin.program.iagl#243]
i dont know how to download the games into my phone because the settings are too complicated 

add in the download section "where to download games/roms"
and you select the folder in your external storage where to download the games

and make it automaticly make the folders like: 3do,nes,gameboy and each folder corespond with the games you download

and to also download a whole folder of games like for a exemple i want to make a console with only nes games i do want to download the whole nes library from iagl but without "sort by __" because will be the same thing over and over and it will take a sh*t load of space like if the wii will be like this it will be a nighmare

**Comment by zach-morris** [comment]
There is already a way to change the download location, see [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to).

I will leave this open though, and track the addition of a method for changing download paths all in one go.

**Comment by zach-morris** [comment]
The wizard now asks you about setting up alternate download paths, so I'll consider this closed, but I'll also update the wiki
