### ISSUE TITLE
3.0.6 broke widgets

### ISSUE THREAD

**Issue by daveftw84** [zach-morris/plugin.program.iagl#244]
my widgets wont load after updating to .6
reverting back to .5 for now

**Comment by zach-morris** [comment]
Works for me.  I'd be surprise if this did happen, since I haven't made any changes recently that would effect widgets.
What skin, etc?  Any debug log?

**Comment by daveftw84** [comment]
im using aura mod, i used widgets and your addons before for many many years. my greatest hits of nintendo games fails to load. after reseting settings and reseting the links for widgets. all them started failing.
using addons like auto widgets allows it to work still. ill get you a log soon

**Comment by daveftw84** [comment]
im calling this one

**Comment by daveftw84** [comment]
skin was issues. updated with a "real updated gui" instead of using a kodi 18 skin with a forged marked up gui,,, fixed it

**Comment by daveftw84** [comment]
[kodi.log](https://github.com/zach-morris/plugin.program.iagl/files/8716799/kodi.log)

**Comment by zach-morris** [comment]
Do others work?  I tried widgets again, but cannot reproduce this issue (all game lists work for me).  I tried to find the skin listed in your debug log but cannot find it anywhere, but I'm guessing it's the skin.

**Comment by daveftw84** [comment]
Ya, everything else is working fine. I'm sure it's the skin too but it use
to work. Not your problem,  just figured I post

**Comment by zach-morris** [comment]
Nothing special about that list (all the game lists are pretty much the same), if you can find the userdata folder for the skin, you can see whats different about the link to that list, or try deleting and re-adding it (I'm sure you tried this already, but worth a shot).

**Comment by daveftw84** [comment]
Thanks, I'll check it out.  I noticed  a /1 at the end of the working
links. I tried but nothing.
For now I copy each link in a super favorite folder and have that widget
pointing to it

**Comment by zach-morris** [comment]
I think i've fixed this, please let me know if it still occurs and if so which skin.
