### ISSUE TITLE
Possiblity to use torrent for fast download

### ISSUE THREAD

**Issue by marcoboutch** [zach-morris/plugin.program.iagl#245]
Hi,

is hard to add possiblity download from torrent on archive.org for fast download ? many kodi addon alreadeay use torrent.
Thank you :)

**Comment by zach-morris** [comment]
i have actually already tried this and there's a few problems:
For small files it actually makes it slower
For large files, the issue with many archive.org torrent files is they become broken and no longer work

At this point, it wasn't worth the effort in my opinion.
Multi-threaded download sped things up drastically, so it's actually usable.  Take a look at the advanced settings 'Download Threads' option.  You can try bumping that up some and seeing if it speeds things up for you (5-10 seems to be the sweet spot for me, to high and you'll actually slow things down).
