### ISSUE TITLE
Controllers issue. Don't act like game controller

### ISSUE THREAD

**Issue by 9acca9** [zach-morris/plugin.program.iagl#246]
Hi. I'm using iagl on Kodi 19.3 on a Android. The problem is that the controller i use it's not take it as a game controller. Every time I press start, or other button i get the pause/resume reset exit settings (game menu option).
What can I do?
Thanks

**Comment by zach-morris** [comment]
IAGL doesn't do anything regarding controller input.  Thats all Kodi and the Android OS you're using.
You can go into the Kodi settings > System > Input > Configure Attached controllers to edit the input settings
You can also change the driver settings there to see if that makes a difference

I use a DS4 controller with android and works great.

**Comment by 9acca9** [comment]
Hi. I download and install RetroArch from playstore to try if the controller is ok. And yes, all work fine in RetroArch.
So, i try to change the launcher app from iagl. And select for SNES, something like "RetroArch SNES 9x" the core i have working on RetroArch. Also put the path to the config RetroArch app.
But... It is not working, in getting this error: 
https://pastebin.com/VbzWaU3U

Thanks

**Comment by 9acca9** [comment]
Hi. I download and install RetroArch from playstore to try if the controller is ok. And yes, all work fine in RetroArch.
So, i try to change the launcher app from iagl. And select for SNES, something like "RetroArch SNES 9x" the core i have working on RetroArch. Also put the path to the config RetroArch app.
But... It is not working, in getting this error: 
https://pastebin.com/VbzWaU3U

Thanks

P.s. so it seems the problem is in this kind of sentence
 plugin://plugin.program.iagl/game/SNES_Bestof_ZachMorris/Super+Metroid+%28Japan%2C+USA%29+%28En%2CJa%29

That "game" directory don't exist.

**Comment by 9acca9** [comment]
I found am.jar in /system/framework/

So change the command in Kodi to launch the games...

But have the same error anyway.

**Comment by 9acca9** [comment]
And that was not the file.
I found just "am" in /vendor/xbin/

And that seems to work but ... I have other error and in this case probably is something related to Iagl or how is config. I get this:

https://pastebin.com/EB2ybT1b


Why is looking for that "game" directory that don't seems to exist?

Thanks!

**Comment by zach-morris** [comment]
That's not really an error, just a Kodi directory message which doesn't effect anything.  I've update the default commands to they just state ```am start``` now, so that should hopefully help others in the future (although I'm not sure why some distros change the default).

Seems like you're comfortable with the command line.  If you paste the command:
```
/vendor/xbin/am start --user 0 -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -n com.retroarch/com.retroarch.browser.retroactivity.RetroActivityFuture --es "LIBRETRO" "/data/user/0/com.retroarch/cores/genesis_plus_gx_libretro_android.so" --es "CONFIGFILE" "/sdcard/Android/data/com.retroarch/files/retroarch.cfg" --es "ROM" "/storage/emulated/0/Download/Sonic The Hedgehog (USA, Europe).md" --es "IME" com.android.inputmethod.latin/.LatinIME --activity-clear-task --activity-clear-top --activity-no-history
```
You may get some more details on whats not working.  Since you're using some weird Android box, it's possibly a 32bit vs 64 bit issue, which I've seen happen before.  You could also try installing ra32 to see if that resolves your issue.

**Comment by 9acca9** [comment]
Thanks, thanks, thanks! ... It's seems that i try several times but never notice this: i was starting the game with RetroArch already running or not good stopped. (I don't speak English, as you can notice). 

I try the syntax on the terminal, don't give me any error and the game starts, i go out without closing the app (RetroArch, the game) and when try to run again I get the grey screen. So... Probably i do all the other test with RetroArch already running or bad closed.

Anyway now is working like a charm! Thanks for the time!!! 

By the way, putting just "am" sounds a good solution, there is a lot of android things out there. 
Thanks thanks thanks!!!

**Comment by zach-morris** [comment]
OK.  The flag ```--activity-clear-top ``` is supposed to close any existing RA apps before it starts a new one, but glad its working.
