### ISSUE TITLE
Android & External Download Paths

### ISSUE THREAD

**Issue by Wanderer189** [zach-morris/plugin.program.iagl#25]
I absolutely love this addon. The issue I am having is I cant change the download path (game path) to use a sd card or a SMB share on a pc on the same network on an android device. I do this for my other media

Is there any place I can edit any file(s) to accomplish this??

I have TB's of games already installed on PC and simply want to share them with the addon.

**Comment by zach-morris** [comment]
It can interface with local content, provided the content is the same exact filenames, etc.  But I agree, Rom Collection Browser or AEL are good choices for local content.  It's typically best to have IAGL download the content to your specified alternate folder and then it will be available after that.  That being said, you should be able to change the download path.  What error do you get when you attempt to change it?  Or if you can extract a log from your android device please provide a pastebin link.

**Comment by Wanderer189** [comment]
It downloads to the pc shared folder just fine, so I do apologize, your addon is working great so far in this project. After doing more research on it today, I have found the issue is actually Retroarch for android. It doesn't know how to access the SMB share and not sure if they will ever include it, they are gearing more to Google drive instead. I have been trying to find a way to mount the SMB share from android, but only app I can find so far is cifsmanager and it is very old and not even sure it will work on more modern devices

**Comment by zach-morris** [comment]
Yeah, SMB is a pain.  I've tried in vain to get it to reliably work for android and I just gave up and use an external drive

**Comment by zach-morris** [comment]
Closing per @Wanderer189 , "appears to be an issue with Retroarch / Android"
