### ISSUE TITLE
kodi iagl game settings

### ISSUE THREAD

**Issue by jacwyl** [zach-morris/plugin.program.iagl#250]
After play few times i wanted to change the screen wideness through the game menu (settings) on iagl.
I choose the widest one and now i cannot play anymore due to to big screen. Howto reset this settings to default?
Of course i try to uninstall all addon but somehow it remembers this setting.
IS it somewhere in retroplayer settings?

**Comment by zach-morris** [comment]
I don't understand the issue.  What setting are you referring to?

**Comment by jacwyl** [comment]
Hi Zach - thank you for your reply. I'll try to describe the issue -? During the game (on Kodi) you can stop the game and even exit the addon (or Retroplayer?) then the windows pops up - so you can decide to stop / pause / play / exit or change the settings.
I changed the setting there to make the game screen larger and after accept it the screen is so big so i cannot see now the game setting to reset it to the defaults. I also uninstall iagl and install again but somewhere this settings are still saved. is there any solution to change it or reset to default? i also attached the screenshot to show you the place:

![screenshot](https://user-images.githubusercontent.com/103172290/162431339-e3059a3a-4666-4f3f-93ef-8202086fb5d7.png)

**Comment by zach-morris** [comment]
Ah, those are Kodi settings and not part of IAGL.
You should just be able to go back in there and edit the settings after you start any game.  I'm not sure why they would go away or why you couldn't get back to them.  Those settings are saved in [guisettings](https://forum.kodi.tv/showthread.php?tid=214507) for Kodi.  You can reset those if you need to, but be aware it will reset all settings for the Kodi GUI.
