### ISSUE TITLE
Unable to start Spectrum games

### ISSUE THREAD

**Issue by chapas** [zach-morris/plugin.program.iagl#251]
Need some help launching Spectrum games with [game.libretro.fuse](https://github.com/kodi-game/game.libretro.fuse).
Game is being downloaded from archive.org in a zip format, but fuse can't launch a ZIP and it fails.
This seems simple, what am I missing here?

Thanks

**Comment by zach-morris** [comment]
It seems the addon removed zip as an acceptable extension format.  I added it manually, and it plays just fine.
I'll open a PR or issue for the addon.  In the meantime, you can edit the [addon.xm](https://github.com/kodi-game/game.libretro.fuse/blob/master/game.libretro.fuse/addon.xml.in#L13)l and change the extensions and add zip
<img width="835" alt="Screen Shot 2022-04-16 at 1 55 03 PM" src="https://user-images.githubusercontent.com/12554283/163691094-07317f41-d251-4fa9-a0af-6151ea264920.png">
.

**Comment by zach-morris** [comment]
Added PR https://github.com/kodi-game/game.libretro.fuse/pull/9

**Comment by chapas** [comment]
Thanks for the quick update!
