### ISSUE TITLE
How to change emulator for a game?

### ISSUE THREAD

**Issue by jbrepogmailcom** [zach-morris/plugin.program.iagl#252]
Hello, I installed one PSX emulator, then tested PSX game, it does not work well. So I installed second PSX emulator, but game now launches still in first emuletor, I do not have choice to pick PSX emulator that I installed later. How can I do that?

**Comment by zach-morris** [comment]
The wiki covers this:
https://github.com/zach-morris/plugin.program.iagl/wiki/1.--Setup#-
