### ISSUE TITLE
404 Archive.org errors

### ISSUE THREAD

**Issue by saharasarge** [zach-morris/plugin.program.iagl#253]
A significant portion of USA CHD PS2 Games are returning download exceptions which are 404 errors in the Kodi log upon attempt to download which began mid March.  It does appear most have been reuploaded March31/Apr1.
[KodiExerpts.txt](https://github.com/zach-morris/plugin.program.iagl/files/8550682/KodiExerpts.txt)

**Comment by zach-morris** [comment]
Thanks.  I'll see if I can update this one

**Comment by vvarcos** [comment]
> Thanks. I'll see if I can update this one

any news?
