### ISSUE TITLE
Incorrect behavior with some Kodi skins

### ISSUE THREAD

**Issue by AtreyuTuga** [zach-morris/plugin.program.iagl#256]
Hello
The roms play very nicely but after i close it, the game will relaunch itself over and over. Sometimes I even have to close kodi and start it again in order to solve the problem. I'm on Kodi 19 Android box Minix.

Is there something in the configurations that prevent this?
Thanx

**Comment by zach-morris** [comment]
It is likely the skin /shortcuts you are using causing the issue (There have been a few other reports of this).  What skin are you using?

**Comment by AtreyuTuga** [comment]
> Hello The roms play very nicely but after i close it, the game will relaunch itself over and over. Sometimes I even have to close kodi and start it again in order to solve the problem. I'm on Kodi 19 Android box Minix.
> 
> Is there something in the configurations that prevent this? Thanx

Hi,
Thanx for your reply.
Yeah, that was my first thought. I have AeonTajo skin installed. Can you advise me on a skin that can solveit?

**Comment by zach-morris** [comment]
Most Kodi skins do not have this issue.  I personally use the default, as well as [arctic.horizon.2](https://github.com/jurialmunkey/skin.arctic.horizon.2)

**Comment by zach-morris** [comment]
Closing.  If this occurs with a different skin let me know
