### ISSUE TITLE
Failed to install dependency

### ISSUE THREAD

**Issue by Cheddartoast** [zach-morris/plugin.program.iagl#257]
I can't seem to install the addon, Kodi gives me the error that a dependency failed to install. Any idea?

**Comment by zach-morris** [comment]
Which dependency?  Do you have a debug log?

The required dependencies are listed here:
https://github.com/zach-morris/plugin.program.iagl/blob/main/addon.xml#L3

Everything listed is in the official kodi repositories, except for script.module.archive_tool, which is in my repository.

**Comment by zach-morris** [comment]
Closing for lack of debug log.  Give it a try with the latest repo and the latest version of IAGL
