### ISSUE TITLE
rpi mess 2014 cdi

### ISSUE THREAD

**Issue by camatthew88** [zach-morris/plugin.program.iagl#26]
the launch command is correct but it still cashes, the launch command is mess2014 %rompath%

**Comment by zach-morris** [comment]
I figured out your issue.  Gamestarter does not include mess2014, see [here](https://github.com/bite-your-idols/Gamestarter/tree/master/packages/libretro-cores-RPi).

Not much I can do if the core is not available.

**Comment by camatthew88** [comment]
i sent a issue to bite-your-idols about this

**Comment by camatthew88** [comment]
can you compile mess 2014 for the rpi

**Comment by zach-morris** [comment]
My addon does not provide any cores, so no

**Comment by zach-morris** [comment]
It appears gamestarter doesnt ship MESS.  I have added a to do item to hide this list from view by default for RPI gamestarter users
