### ISSUE TITLE
Fb Alpha neo request 

### ISSUE THREAD

**Issue by edgarmc2000** [zach-morris/plugin.program.iagl#260]
Is there a way to have namco classics collection vol 1&2? I'd love to have it since I always enjoyed em. Cheers!

**Comment by zach-morris** [comment]
I dont think those are in the FBNeo Rom Set currently, that I could find (so I doubt they would play in FBNeo).  There are some of those games in the MAME romset.

You could make a custom list of pretty much most Namco games though.  Use the search function, select the FBNeo list, then filter by Studio Namco (and the variants of Namco), and you'll get a list of just the Namco games.
