### ISSUE TITLE
DOSBox Pure does not work, maybe due to unpacking of games

### ISSUE THREAD

**Issue by fladi** [zach-morris/plugin.program.iagl#262]
I tried to run some games from the exodos list, namely Sid Meiers Civilization. When I start it it only shows the "No executable file found" message. I assume this is because DOSBox Pure expects the game to be in a single archive instead of getting unpacked as IAGL does. The debug log is attached.

![screenshot00001](https://user-images.githubusercontent.com/234220/180619763-051c4b8a-a548-4755-9706-67e00527ea0f.png)
[kodi.log](https://github.com/zach-morris/plugin.program.iagl/files/9174495/kodi.log)

Setting the exodos launcher to vanilla DOSBox does not help as it does not recognize the configuration file.

Is there a way to pass the downloaded archive file directly to DOSBox Pure?

**Comment by zach-morris** [comment]
I haven't played with DOSBox Pure, but you could potentially change the post download command.  Current default for eXoDOS is to unarchive and generate a conf file to launch.

You can change this line in the file:
```
//path_to_userdata/addon_data/plugin.program.iagl/dat_files/eXoDOS_ZachMorris.xml
```

From:
```
<emu_postdlaction>unzip_and_launch_exodos_file</emu_postdlaction>
```
To:
```
<emu_postdlaction>none</emu_postdlaction>

```

Then when you open up Kodi again, select Refresh Game list to erase any cached settings, and it should just try and launch the zip file directly.  If that works let me know and I'll try and jig up a more automated method.

**Comment by fladi** [comment]
Yeah, changing this line worked for me. Now I can see the list of executeables. Still stuck on DOSBox Pure not accepting input from keyboard/mouse but this seems like an issue with DOSBox Pure itself. Thanks!

**Comment by RazzerMan** [comment]
The workaround dated 24 July worked perfectly. Further, RetroArch now works with keyboard and mouse input. I have just tested with v4.0 beta and games launching in RetroArch/DOSBox-Pure no longer work. Further, I cannot locate an eXoDOS xml. Is there an alternate fix for v4.0?

**Comment by zach-morris** [comment]
There is no more xml.  All the settings are in a sqlite db now.
I could expose the post download command, however then the game wouldn't work with different cores (like plain dosbox or svn).

The setting for dosbox-pure core allows the game to be loaded without issue though, i think ultimately thats the best method for launching these games:
<img width="796" alt="Screen Shot 2024-12-27 at 6 37 49 PM" src="https://github.com/user-attachments/assets/7060ecbe-00d6-4611-942b-36e483f0eb4a" />

**Comment by zach-morris** [comment]
Fixed with latest commit
