### ISSUE TITLE
Downloading roms to a usb drive

### ISSUE THREAD

**Issue by commercial-sample123** [zach-morris/plugin.program.iagl#264]
Is there any way to download the roms to a usb drive?
My android box only has around 4gb and some playstation games take up the entire storage.
I wanted to know a way to have the roms downloaded to a 128 gb usb drive I have.
Any way I can achieve this?

**Comment by zach-morris** [comment]
Yep, you can do that. See [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to).
For android, pay attention to that last note as you may have to name your storage folder as suggested for permissions to work.

**Comment by bongobil** [comment]
Right click on the console in the list and choose "set download location" ?
