### ISSUE TITLE
SNES emulators missing

### ISSUE THREAD

**Issue by TheDiggler** [zach-morris/plugin.program.iagl#267]
I have Kodi Nexus and IAGL v3.0.6, on a Windows 10 PC. 

I have SNES set to, RetroPlayer and choose but in the list of emulators it does not show me any SNES emulators.  No problems with MAME/Genesis and PS1.  I got around it by manually installing an emulator from the Kodi repo but thought I would at least post something.

**Comment by zach-morris** [comment]
Hmm.  This seems to work for me.  Does it work in v20.1?

<img width="1069" alt="Screen Shot 2023-03-16 at 9 35 38 PM" src="https://user-images.githubusercontent.com/12554283/225813800-67955e77-2c3b-472c-b360-73686a93a420.png">
<img width="1069" alt="Screen Shot 2023-03-16 at 9 35 59 PM" src="https://user-images.githubusercontent.com/12554283/225813794-5850d853-3edc-4118-9785-693e8625f7bc.png">
<img width="1073" alt="Screen Shot 2023-03-16 at 9 36 09 PM" src="https://user-images.githubusercontent.com/12554283/225813797-31b5113e-76c7-4fdb-af72-dbd2234e8e53.png">
