### ISSUE TITLE
windows 3.1 config file error when cache is not zero

### ISSUE THREAD

**Issue by camatthew88** [zach-morris/plugin.program.iagl#27]
windows 3.1 games stillvgive illegql command mono_dlx.bat. this might help 
https://archive.org/details/win3_Mono3Dlx. Retroarch does not crash

**Comment by zach-morris** [comment]
OK, after some investigation, I've found an issue.
Note it does work if cache is set to zero:
![image1](https://i.imgur.com/pUkKohd.png)

It doesn't work if there are multiple win31 games in the same directory.
![image1](https://i.imgur.com/cLH7cjl.png)

Some issue with the pointer files that are generated when creating the game folder.  I'll look into this further.

**Comment by camatthew88** [comment]
i also have windows initalazation files missing.

**Comment by zach-morris** [comment]
This should be fixed with 2.0.5, can you confirm?

**Comment by camatthew** [comment]
im sorry, i have been busy, this is my other account. I have just forgotten about it and will try asap.

**Comment by camatthew** [comment]
the win31 still doesent work.

**Comment by camatthew** [comment]
same error

**Comment by zach-morris** [comment]
I've tested this on OSX and Windows and Android and they all seem to work.  Please open a new issue with a log if you can recreate an issue here.
