### ISSUE TITLE
Wont Launch RetroArch On Android 13

### ISSUE THREAD

**Issue by jayjayuk** [zach-morris/plugin.program.iagl#272]
i have been trying to launch retroarch via IAGL on kodi 20 (Samsung Fold 3) for the past few days and nothing i do will work.
i have tested launch commands via adb shell and they work fine, also if i download a game and then use AKL to find the game and launch it, it launches retroarch as it should.

i have read lots of information here on issues and on the forum for AKL + AEL about these android issues and it seems like changes have been made to kodi to implement launching retroarch properly but i cannot get it to launch retroarch using IAGL.

is this a bug for everyone right now or just with my setup?

i can provide more info if its just my setup, but if its for everyone i guess its just a waiting game. i just cannot find a clear answer.

**Comment by jayjayuk** [comment]
thank you, thats the answer i was looking for. i have tested the master but i get the same result unfortunately.

i have tried many combinations/versions/launch-commands of retroarch / kodi / iagl and finally after pulling my last hair out i had to ask the question. i will just wait for the kodi fix and eventual iagl update.

thanks for clearing that up and for making this plugin, very much appreciated.

**Comment by jayjayuk** [comment]
ok so i decided to try a fresh kodi 20 install from the play store, installed the repo 1.0.3 to install the dependencies, then installed IAGL 3.0.7. from a zip file and turned on debugging. i have attached a link to hastebin which shows a section of the log which indicates permission issues... please see log.

https://hastebin.com/share/sirulicore.yaml

**Comment by zach-morris** [comment]
Should be working in 3.0.7 - the wiki will have to be updated but there are some caveats.  Main one being that the files need to be downloaded to a shared directory (one that both apps can see given their permissions).  The wizard is updated to account for this.  Let me know if you run into any issues.
