### ISSUE TITLE
PS1 - Roms from EU and localization

### ISSUE THREAD

**Issue by doctornono** [zach-morris/plugin.program.iagl#275]
First of all, thank you very much for this great work.

All PS1 roms are US, is it possible to have a list with all EU roms ? For example based on this page :
https://archive.org/details/rr-sony-playstation
Do I have to create my own list/Dat_files?

And how to have the game description in another language than English?

**Comment by zach-morris** [comment]
Transferring this request to 
https://github.com/zach-morris/plugin.program.iagl/issues/38
