### ISSUE TITLE
Game console support requests (they already are emulated)

### ISSUE THREAD

**Issue by upintheairsheep** [zach-morris/plugin.program.iagl#276]
Please add support for more platforms:
Flash ( https://archive.org/details/softwarelibrary_flash )
Calculators ( https://archive.org/details/calculatordrawer )
Obscure consoles ( https://archive.org/details/consolelivingroom )
more soon

**Comment by upintheairsheep** [comment]
Palm and Palmpilot ( https://archive.org/details/softwarelibrary_palm )

**Comment by zach-morris** [comment]
Consolidating these into the other issue already open for list updates 
https://github.com/zach-morris/plugin.program.iagl/issues/38
