### ISSUE TITLE
Device storage not accessible from Setup Wizard

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#28]
This is on Android, specifically from an nVidia Shield.

During the "system directory" phase of the Setup Wizard, device storage isn't browsable. It is browsable during the "config file" phase, and by setting the system directory manually.

**Comment by zach-morris** [comment]
Can you verify if it works  / doesn't work after going into Kodi Settings>Media>General>Show Hidden Files and Directories

I'm not sure if there's a way to enable that via addon, but I'll look into it.

**Comment by drinfernoo** [comment]
@zach-morris I have hidden files showing. The only things listed are my file manager sources, so one possible fix is to add my external storage as a course inside the file manager, but that seems like more of a workaround.

**Comment by zach-morris** [comment]
OK, I think this will solve it, Kodi added a "list local drives and network shares" option which I switched these file browse dialogs to use

**Comment by zach-morris** [comment]
This should be fixed with 2.0.5, can you confirm?

**Comment by zach-morris** [comment]
I believe this is fixed, please reopen if not
