### ISSUE TITLE
User Experience Issues Related to Caching and Downloading

### ISSUE THREAD

**Issue by CFTBL** [zach-morris/plugin.program.iagl#284]
Testing IAGL 3.0.9 on LibreELEC-RR on RPi4. So far, in IAGL. I've only been looking at this on FB NEO, but there are three things about IAGL caching and downloading that are problematic. If you specify a download folder in a game list's settings, there are two undesirable side-effects: 1) Every game launched from that list is retained in that download folder (regardless of whether or not the user clicked the Download button). This causes unnecessary clutter (and is problematic if your download folder is also your Emulation Station content folder). 2) If a download folder has been specified, the cache size setting is ignored and the game will not be cached in IAGL's default game cache folder. The third thing is this: If a download folder has not been specified, and the user clicks the Download button, the game is downloaded to IAGL's game cache folder. That's OK, but the expectation is that "download" refers to a permanent copy whereas "cache" refers to a temporary copy.

I think the following changes would result in expected/desired behavior:

1) Each list should have it's own game cache folder and its own download folder (the latter can be a user-specified path)
2) If the above change is made, the game cache size setting shouldn't be a global IAGL setting. It should be a list-specific setting.
3) Launched games should be retained in the list's game cache based on the list's game cache size setting.
4) Games are never downloaded to the download folder unless the user clicks the Download button.

**Comment by zach-morris** [comment]
There is an option to organize the cache folder in advanced settings.  Probably not very good documentation, but see 'Organize Cache Folder using System Folders'.
However - if the overall cache folder is too large, then the entire folder is purged.

I understand what your saying with the download button - it might be best actually to hide the button if the default cache folder is used.

Another possibility is that I can add a context menu for an ad-hoc 'download this to ..'

**Comment by zach-morris** [comment]
The default is now organizing the game cache folder.  In addition, there's options to change the default folder for downloading, or you can manually download the game to an alternate folder, or you can set the download folder specific to the game list.  The only directory that IAGL monitors or deletes files from is the userdata folder however.  Anything else would be asking for trouble.
