### ISSUE TITLE
Cannot install due to unmet dependency for xbmc.python

### ISSUE THREAD

**Issue by makuser** [zach-morris/plugin.program.iagl#288]
I don't know what I'm doing wrong. I'm running libreelec 10.0.4 with Kodi 19.5-Matrix.

Installed the repo in version 1.0.4, no game addons showing up there though.

Tried the plugin zip directly, but I only get an error:

`ERROR <general>: CAddonInstallJob[plugin.program.
iagl]: Die Abhängigkeit auf xbmc.python in Version 3.0.1 konnte nicht aufgelöst werden.`

Are you sure it's supposed to be xbmc.python 3.0.1 and not 3.0.0?

**Comment by zach-morris** [comment]
The docs state:



Kodi version | xbmc.python | xbmc.gui | xbmc.json | xbmc.metadata | xbmc.addon
Nexus 20.x | 3.0.1 (ABI 3.0.0) | 5.16.0 (ABI 5.15.0) | 13.0.0 (ABI 6.0.0) | 2.1.0 (ABI 1.0) | 20.90.101 (ABI 12.0.0)
-- | -- | -- | -- | -- | --

 The ABI version you see in the table above is the backwards compatibility version for which add-ons are still marked "working".

So it should be 3.0.1 according to the docs.  If you're using Kodi v19 still, you'd need to install IAGL v2.X
See wiki here:
https://github.com/zach-morris/plugin.program.iagl/wiki/0.--Installation#1-kodi

**Comment by makuser** [comment]
> If you're using Kodi v19 still, you'd need to install IAGL v2.X
> See wiki here:
> https://github.com/zach-morris/plugin.program.iagl/wiki/0.--Installation#1-kodi

What are you even talking about? Your wiki states to install v2.X for Kodi 18. Not 19. Which one is it now? 😕 

`NOTE The addon in the repository is for Kodi v19 now (which includes python > v3). Users of Kodi v18 (python v2.X) or earlier have to manually install v2.X of the addon from here (there is no more repository for the old version).`


> So it should be 3.0.1 according to the docs.

And which docs are you taking about here?

**Comment by makuser** [comment]
Alright, I thought I'd do you a favor by pointing out either the bug or the doc inaccuracy.

But seeing now, that you introduced a hard incompatibility with Matrix, in neither a MAJOR, nor even a MINOR, but in a PATCH release (f4148d7 !?), and seeing how passive aggressive you shut down such a bug report, I get the feeling it wasn't even a mistake/oversight, but fully intentional.

Without overstepping the line, I'd suggest to update the wiki and possibly abandon or overthink that versioning, as it's utterly confusing the way its currently used.

**Comment by zach-morris** [comment]
I'm not sure i follow. Nexus is the latest version (v20) along with the python versioning that goes along with it.  v3.X of IAGL is not, or has ever, been compatible with Kodi v19.  IAGL v2.X is however compatible.

**Comment by makuser** [comment]
> I'm not sure i follow. Nexus is the latest version (v20) along with the python versioning that goes along with it.

Please have a look at your own linked docs. That will save us both any more time.

**Comment by makuser** [comment]
O cmon. These constant edits.

I meant to quote your original message:
> I'm not sure i follow. Nexus is the latest version (v20) along with the python versioning that goes along with it. v3.X of IAGL is not, or has ever, been compatible with Kodi v19. IAGL v2.X is however compatible.

To that I say: please look at your own docs, which explicitely state otherwise.

**Comment by zach-morris** [comment]
You'll either have to be more polite, or explain the issue more clearly.

**Comment by zach-morris** [comment]
OK, i think I confused versioning, but the issue stands as closed.  I develop for the latest version of Kodi, which unfortunately isn't backwards compatible.  I've updated the wiki where you suggested.
Thanks
