### ISSUE TITLE
Launch games on android 8.0

### ISSUE THREAD

**Issue by jramip** [zach-morris/plugin.program.iagl#29]
Hi, on Android 8.0 (Oreo) launching games with external emulator doesn't work, if retroarch is launched it shows retroarch but it doesn't load the game, if is not launched it does nothing. I think it's a permission bug in the new android.

Thanks

**Comment by zach-morris** [comment]
This should work now.  If possible please try 2.1.0 and let me know if the issue persists

**Comment by zach-morris** [comment]
Closing, re-open new issue with debug log if issue persists
