### ISSUE TITLE
amiga hdf games not working with puae emulator

### ISSUE THREAD

**Issue by mczerski** [zach-morris/plugin.program.iagl#291]
What is the current state of IAGL vs game.libretro.uae ? Cause I cannot launch any games in hdf format. Amiga CD32 works. The issue is described in those two issues:
https://github.com/kodi-game/game.libretro.uae/issues/6
https://github.com/libretro/libretro-uae/issues/586
but contrary to those IAGL issues are marked as solved:
https://github.com/zach-morris/plugin.program.iagl/issues/167
https://github.com/zach-morris/plugin.program.iagl/issues/273

I use CoreELEC 20.1 on Amlogic S903X3. game.libretro.uae is 3.5.something and IAGL is 3.0.9
Is anyone able to launch hdf games with IAGL and RetroPlayer ? If yest please report versions of the addons and KODI.

**Comment by zach-morris** [comment]
Yeah, i've found somehow the process for loading WHDLoad/HDF games has changed.  I will likely just update the archive to utilize LHA games, which from what I can tell just work.

**Comment by AmigaPuae** [comment]
Any updates on this?

It still seems to be broken. I am just getting a window saying

'Please insert volume DH0 in any device.' 

i am using libreelec 11.0.6 on a raspberry pi 4.

Is there a way to change it back to use adf files again?

**Comment by AmigaPuae** [comment]
Here is a debug log 
https://paste.libreelec.tv/enjoyed-possum.log

**Comment by zach-morris** [comment]
Fixed with the latest push in V4 beta.  2 amiga game lists are included:  One is the ipf / no-intro (disk based) games, the other is whdload lha games.  Both verified working
