### ISSUE TITLE
sort the launch commands by platform like retroarch does?

### ISSUE THREAD

**Issue by djay** [zach-morris/plugin.program.iagl#293]
it's a long list and often you aren't sure which name it the emulated might be listed under even if you do remember the name. I find myself have to read the list so many times.
 
- [ ] Sorting my the target would help narrow it down.
- [ ] If there was a way to match the list to the target and put those ones at the top it would be even nicer
- [ ] if the recommended one could be indicated, even nicer still. since IAGL has that list anyway.
- [ ] if the current one could be indicated that would also be nice. since you currently have to link into list info and try and reverse engineer the command to work that out.

**Comment by zach-morris** [comment]
IAGL v4 will give you options on how to find the core you're interested in when setting an external launcher:
<img width="668" alt="Screen Shot 2024-12-24 at 10 44 36 AM" src="https://github.com/user-attachments/assets/5f547a1f-596e-4f76-8512-8328cd750caa" />

The user can drill down depending on how they want to find the right core.   This is done automatically for most systems based on Retroarch info files.

I may eventually try to incorporate compatible cores in based on file extensions present in the game list, but for now i think this fits the bill

**Comment by djay** [comment]
It certainly helps. The extras isn't sorted by what it emulates however and I think it would be improved if it did. But at least it's much shorter now since the retriarch cores are seperated out.
