### ISSUE TITLE
There is no IAGL in the repository?

### ISSUE THREAD

**Issue by Taxicletter** [zach-morris/plugin.program.iagl#294]
There's only one program addon, some BIOS thing.
I tried multiple times.
(KODI 19.5 on LibreELEC 10.0.4, on Rasp 4, Zach Morris 1.0.4.)

**Comment by zach-morris** [comment]
The repository version is for the current version of Kodi (v20 and newer)
https://github.com/zach-morris/plugin.program.iagl/wiki/0.--Installation#3-iagl-addon

You could upgrade your version of LE to the current stable version and it would be present.

**Comment by Taxicletter** [comment]
Thanks!
I thought I had the newest version, it's set to update automatically...
