### ISSUE TITLE
Games with a ',' in the name wont launch 

### ISSUE THREAD

**Issue by jayjayuk** [zach-morris/plugin.program.iagl#298]
hello, i have been playing with kodi and iagl on the 4K-Max Stick and its been working great so far.

i just setup game gear with genesis core and tried to play "Lemmings (World)" and all was fine, then next in the list was "Lion King, The (USA)" and it failed to launch, i got the completed notification right away. then i tried the next one in the list "Lost World, The - Jurassic Park (USA)" this also failed to launch, at this point i noticed lemmings was a clean name and these two had a ',' in the name, for some reason its totally fine for there to be a ',' in the language part that is in parenthesis, but if there is a ',' in the name it fails, i tried other systems and its the same where a ',' in the name is failing to launch, other special characters seem fine. i also tried a game from a bug report here "Cannot launch game Revenge of Shinobi for genesis #297" and that game also has a ',' in the name and does not launch for me. 

firestick 4k max
kodi 20.2 stable
iagl 3.0.9 main
retroarch_ra321.15.0 

also, just to mention, it did download "Lion King, The (USA)" as i used adb to pull it from the game_cache folder and loaded it with retroarch directly and the game loaded fine

i just enabled debugging and that does not show the launch command used for some reason, i remember a while back it used to print the launch command but now i cant get it to print it in the log so i cant see what its actually passing to retroarch

update: just tested on windows and it works fine, i then set everything up on my android 13 phone and it failed again, so looks like an android issue with ',' in a name.

update 2: tried with /system/bin/am and full paths on cmd line for Lion King and it works, i then tried using full paths in the launch command for IAGL putting the rom path as the full path for Lion King pointing to IAGL cache folder and this failed (but lemmings with full path in IAGL works) so i guess that rules out expansion problem with %ROM_PATH%. last thing that i can no longer look into is it must be the way kodi is grabbing that rom line and thinking that comma is a separator for kodi string and parsing in incorrectly, but i dont know python so my road of discovery ends here, sorry i cant help more.

**Comment by zach-morris** [comment]
Thanks for the report!

**Comment by zach-morris** [comment]
I think this is fixed in IAGL v4.  It makes use of ```xbmcvfs.makeLegalFilename``` to avoid any illegal characters, depending on the OS.  I don't have a firestick to test on, but this works on other systems now.
