### ISSUE TITLE
Changing RetroArch Config has no impact unless you go through the Wizard again. [Android]

### ISSUE THREAD

**Issue by Kristijan1001** [zach-morris/plugin.program.iagl#301]
Changing the config option doesnt do anything and still loads the previous config, unless u change it there accept the changes, then go settings again and go through the wizard again. Even tho the wizard doesnt ask for the config again it will still save the new config once u go through it.

**Comment by zach-morris** [comment]
Which config are you referring to.  The Retroarch config?

**Comment by Kristijan1001** [comment]
> Which config are you referring to. The Retroarch config? The addon doesn't effect that config file at all. All the addon needs to know is the path to that config.

Yes the retro arch, lets say u want to select a new retroarch config, If you change it through the settings menu it wont SAVE. Even tho it shows like it has saved, next time u boot up a game it will just create a config with the old name even tho u removed it and wanted to use the new one. 

To fix it u need to go to settings and go through the wizard again, this time the setting will actaully stick and it will use the new config.

**Comment by zach-morris** [comment]
The addon only loads retroarch and points to the config file listed.  It doesn't save the file, or edit the file in any way, Retroarch does that.
If your on Android, you may have a write protection issue.  You can try saving the config file to a location on your box that you know both Android and Kodi can access.

**Comment by Kristijan1001** [comment]
> The addon only loads retroarch and points to the config file listed. It doesn't save the file, or edit the file in any way, Retroarch does that. If your on Android, you may have a write protection issue. You can try saving the config file to a location on your box that you know both Android and Kodi can access. See the wiki [here](https://github.com/zach-morris/plugin.program.iagl/wiki/1.--Setup#setup-with-android)

I understand that i dont think u get what i am saying. The file you point to doesnt save it still uses the previous one until u run the wizard again. Of you have removed the old one it will create the file on its own

**Comment by zach-morris** [comment]
I think this is fixed with IAGL v4
