### ISSUE TITLE
Starting a Game while RetroArch is running or another game is running doesn't do anything [Android]

### ISSUE THREAD

**Issue by Kristijan1001** [zach-morris/plugin.program.iagl#302]
If a game or retroarch is running another game wont boot until u quit retroarch completely.

**Comment by zach-morris** [comment]
IAGL v4 will now set the appropriate flags for launching on android to avoid this.  I'd say it's also best practice to have Retroarch exit when closing a game, to avoid this altogether:
https://www.youtube.com/watch?v=k5WWacfIn6Y


Reference for me if this ever comes up in the future:
```
FLAG_ACTIVITY_NEW_TASK = 0x10000000;
FLAG_ACTIVITY_RESET_TASK_IF_NEEDED = 0x00200000;
0x10000000 is the hexadecimal notation for 268435456.
0x00200000 is the hexadecimal notation for 2097152.
If you add these numbers, you get:
0x10200000, which is the hexadecimal notation for 270532608
Which is the flag sent by IAGL
```
