### ISSUE TITLE
save feature for 3.0.6

### ISSUE THREAD

**Issue by galis3rd** [zach-morris/plugin.program.iagl#303]
First off, thanks for the awesome work!
Can we have the save feature for iagl 3.0.6.? It's the only version that works with chromecast with google tv(android 12) + Kodi 19.5
I tried iagl 3.0.9 on Kodi 20.2 but the controller only controls menus and stop working in game so i have to downgrade.
Also when installing iagl 3.0.6, I have to manually install the archive_tool script for it to work.
thanks again

**Comment by zach-morris** [comment]
Game saves are handled by Kodi directly.  IAGL doesn't handle game saves at all.  I think the latest version of Kodi (21.1+) auto shows you any saves present, which is pretty cool.
