### ISSUE TITLE
IAGL on Smartphone. Possible to use the device as controller ?

### ISSUE THREAD

**Issue by Jeanaimarre** [zach-morris/plugin.program.iagl#305]
Hello
I have IAGL installed on my android smartphone via Kodi. As the screens are getting bigger and bigger, would it be possible to configure a “virtual” controller profile? For example, I would like to be able to use the bottom of my screen as a virtual controller. So for example the right side of my screen would be the joystick and the bottom left side would be my 4 buttons. The idea would therefore be to no longer need a physical controller to play but to create virtual zones in order to play on the smartphone

Thx !

**Comment by zach-morris** [comment]
If you launch retroarch with IAGL, that should work.  Retroarch already has virtual controllers.  You can configure them in Retroarch, then launch games with IAGL.  Kodi currently doesn't have that capability, as far as I know.
