### ISSUE TITLE
Cloud save?

### ISSUE THREAD

**Issue by digobigo** [zach-morris/plugin.program.iagl#306]
Is there a way to sync my save files so i can play on multiple devices without losing progress?

**Comment by zach-morris** [comment]
Cloud saving would be done either directly by Kodi, or by an external service.  Game saves aren't handled by IAGL at all.

There's a thread here for it:
https://forum.kodi.tv/showthread.php?tid=372681

But I'd suggest using google drive or your favorite file sharing service to sync.
