### ISSUE TITLE
Mame does not ever load up rom lists!

### ISSUE THREAD

**Issue by 03stevensmi** [zach-morris/plugin.program.iagl#307]
Title says it all! I'm a bit upset no one has bothered even discussing it anywhere.
But the Mame categories do not load! Just a forever loading circle! 
This issue is a problem on the newest arm64 rpi4 librelec using latest iagl, old matrix version of iagl (linux armhf) and x86_64 Linux latest version of kodi nexus using steamOS with latest iagl. 

What is going on?

**Comment by 03stevensmi** [comment]
just tried again on x86_64 steam os and it eventually loaded up... However both old and latest versions of iagl on librelec unfortunately doesnt load up. It used too quite quickly as the same as the rest of the systems... But for some reason it won't on rpi4 64bit old matrix librelec and rpi3b+ 64bit (and 32bit rpi2b+) latest nexus librelec. ...also sorry for spelling librelec wrong... I know thats not how it's spelt... Ive googled the name like 1000 times and I STILL can't get my head around how its spelt. (and no, don't have dyslexia. Lol)

**Comment by zach-morris** [comment]
I would need a log to understand the issue

**Comment by zach-morris** [comment]
Reading between the lines, it's possible the list was just too big for an rpi4 to load.  MAME has over 10k games in it.

That being said, IAGL has completely changed the game list method and database to utilize sqlite.  This should avoid any size issues in general. 

However, Kodi might still be memory limited.  Showing 10k items in a list will likely make Kodi chug.  Recommend setting up paging in IAGL settings to limit the number of items shown on a page.
