### ISSUE TITLE
Some images are not showing

### ISSUE THREAD

**Issue by Clutz450** [zach-morris/plugin.program.iagl#309]
When browsing through the addon and lists, some of the images from imgur are not found. 
![Screenshot_20240123_175302_Kodi](https://github.com/zach-morris/plugin.program.iagl/assets/38346645/ba304320-46de-464c-85ad-09be1b5d9d89)
![Screenshot_20240123_175332_Kodi](https://github.com/zach-morris/plugin.program.iagl/assets/38346645/6f4f1c93-cb4c-4669-8a03-0005fed0a9c3)
![Screenshot_20240123_175357_Kodi](https://github.com/zach-morris/plugin.program.iagl/assets/38346645/e8207a97-ca6a-4979-8749-21fce50edac1)

**Comment by zach-morris** [comment]
Bummer.  imgur was indeed on the way out for a year or so.  Seems like they've finally started purging images. I guess it's time to update every data file...

**Comment by Clutz450** [comment]
Sounds good.  Let me know if you need any help.  Also, haven't seen you around discord in a while.  Hope all has been well.

**Comment by zach-morris** [comment]
This'll take a while (real life got in the way for a while)! I'll target an addon update around the time the new version of Kodi is released.  Goal would probably be to pull most images from libretro-thumbnails repository, which should be the one of the best image repositories for this purpose.

**Comment by zach-morris** [comment]
Fixed (as much as possible) for v4
