### ISSUE TITLE
Browsing download folder for disk cache throws exception

### ISSUE THREAD

**Issue by LysanderM** [zach-morris/plugin.program.iagl#31]
Hi there,

The add-on works flawlessly on my FireTV Pendant on-demand mode. (Downloading without cache and run instantly on memory)

If I right click to a list and try to Change Download Path, an exception is thrown, it says see log for details. But I couldn't find the log file.

I need to assign my SMB/FTP folder as Download Path for roms, in order to play larger games.

Thanks,

Emir.

**Comment by zach-morris** [comment]
This should work now.  If possible please try 2.1.0 and let me know if the issue persists

**Comment by zach-morris** [comment]
Closing, re-open new issue with debug log if issue persists
