### ISSUE TITLE
Some lists could not be updated - Setup Wizard

### ISSUE THREAD

**Issue by physkets** [zach-morris/plugin.program.iagl#314]
At the end of the Setup Wizard, I see a message that says that some lists could not be updated, even though I input my archive.org credentials. I also checked the login details via `Settings > Download Options > Check login credentials`, and it is able to successfully login.

And some of the games fail to download with a "Download Request Exception"; for eg. `Mario Kart Wii`.

**Comment by zach-morris** [comment]
Yep, the current archive is no longer available from archive.org.  This will be updated in a newer upcoming addon version

**Comment by zach-morris** [comment]
Fixed in IAGL v4.0+
