### ISSUE TITLE
Controller Not Working After Install

### ISSUE THREAD

**Issue by diabl0w** [zach-morris/plugin.program.iagl#317]
Environment: Retroarch on CoreElec on S905 tv box // Logitech wired game controller
Steps to Reproduce (this is exactly what I did, not sure what exactly caused the issue):
- Use IAGL to launch N64 game via Retroarch

Uninstalled IAGL, controller still doesn't work. Not sure what IAGL did to my system to cause this, please help me revert this change
- Couldn't find a way to exit the game back to kodi, so I ssh'd into device and rebooted it
- Upon rebooting, my logitech controller no longer works

**Comment by diabl0w** [comment]
fixed, for some reason IAGL or it's Retroarch launch method disabled Kodi's setting for "Enable controller support"
Maybe this will help a googler

**Comment by zach-morris** [comment]
IAGL has a setting to disable the joystick while Kodi is in the background.  I think it's on by default.  This is only important though where the window manager doesn't automatically do this (some linux's and strangely windows don't always disable input on the background application).  If this doesn't apply to your OS, you can turn that option off in settings.
Normally this wouldn't matter.  If you return to Kodi after you exit the game, IAGL re-enables the joystick normally.

**Comment by diabl0w** [comment]
> IAGL has a setting to disable the joystick while Kodi is in the background. I think it's on by default. This is only important though where the window manager doesn't automatically do this (some linux's and strangely windows don't always disable input on the background application). If this doesn't apply to your OS, you can turn that option off in settings. Normally this wouldn't matter. If you return to Kodi after you exit the game, IAGL re-enables the joystick normally.

Gotcha, thanks for clarifying the behavior of it and the disable option! :)
