### ISSUE TITLE
PSP list empty in beta

### ISSUE THREAD

**Issue by djay** [zach-morris/plugin.program.iagl#318]
Just shows up blank after clicking show all.

**Comment by zach-morris** [comment]
It shouldn't be.  Do you have 1G1R filtering enabled?  I think i see an issue with that particular list and 1G1R listing.

**Comment by zach-morris** [comment]
Fixed 1g1r listing in latest push.  Current ppsspp listing isn't included as the naming convention doesn't follow redump
