### ISSUE TITLE
Increase Cache Size

### ISSUE THREAD

**Issue by Wanderer189** [zach-morris/plugin.program.iagl#34]
This isn't a bug, but I would like to be able to increase cache size to larger than 20GB. 

Many android devices allow up 128gb sd cards to be used as internal storage now with newer version of Andoid on them. I would like to be able to increase it to 32gb or 64gb.

I found the choices in the the plugin.program.iagl>resources>settings.xml file; line 19, where else would it need changed to work?

Thanks for maintaining the addon and lists.

**Comment by zach-morris** [comment]
I could add more temporary cache options, but I highly recommend if you're interested in a library that large, that you look into [alternate download locations](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to).  The addon works the same way with those alternate locations, but the data is just not purged as it would be in the temp cache folder.

**Comment by zach-morris** [comment]
Added 32GB and 64 GB in [this](https://github.com/zach-morris/plugin.program.iagl/commit/1266dfad388234a350a639663ac6aed3cf72896b) commit, will be in the next version update
