### ISSUE TITLE
IAGL Does Nothing When Selecting a Game

### ISSUE THREAD

**Issue by OneWithNothing** [zach-morris/plugin.program.iagl#35]
I'm very new to Kodi, so please let me know if there are any other details I can provide. I've tried a fresh install of Kodi with both LibreELEC and OSMC. In both versions, after I had everything setup, I would try to launch a game and it would do nothing at all, maybe pause for a second. I used the Gamestarter addon to install Retroarch, as well as tried pointing to a different directory, all to no avail. I'm also using a VPN, but I'm not sure this matters. Is this a problem you've seen before? Any help would be appreciated. Thank you very much!

**Comment by zach-morris** [comment]
Well, I'd need some more information, like a log, to try and help.  In the meantime I suggest looking [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#14b-i-pressed-launch-but-nothing-happened-your-addon-is-broken)

**Comment by OneWithNothing** [comment]
Thank you very much! I'll check out this section that I definitely missed, and will report back with logs if I still can't get it. Hope you've having a great new year!

**Comment by zach-morris** [comment]
Closing for now, provide logs and specifics if issues remain
