### ISSUE TITLE
[Request] Option to set views addon-wide

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#39]
I had previously opened #5, requesting more consistent view types, but I think it was explained wrong or dismissed erroneously as a skin issue.

After further experimentation, it does look like views "stick" inside of a specific view, but not *across* views, which is what I'm looking for.

Say for example, take a typical path, and I'll denote in parentheses which view types I would prefer to use, in the context of Aura (but the same logic should be applied across skins as well):

IAGL (Banner Wall) -> Browse All Lists (Banner Wall) -> Gameboy Advance (Banner Wall) -> One Big List (Landscape Showcase)

Now, the problem comes if I want a different console, with the same view types in the same categories. If I instead chose Super Nintendo, for example, I would have to change all the views to the appropriate views of my choice. I realize I *should* only have to do this the first time through, but since there are **so** many different sections of this add-on, that would be fairly tedious to set up all of my desired categories.

Another hitch that sometimes happens is this: If I use "lock view" in my skin to lock "TV Shows" content to a specific view type (like Landscape Showcase), then open a view inside IAGL, I have to "unlock view" in order to change the view, which in turn tends to change it in other "TV Shows" sections inside Kodi.

My request is that there be a way to set, through the add-on, a specific view type (most flexible would be to set it by view ID) for common views. For example, the "Choose from List" views could be set to a certain view, like Banner Wall, but you could set "One Big List" views to Landscape Showcase, and "Browse by Genre" to Poster Wall, etc...

I would think the best way would be to allow entering a view ID, as many skins have different views with different IDs. Seren does this, as defined in it's `settings.xml` file:

https://github.com/nixgates/plugin.video.seren/blob/e2d3ee33f836c3ed41972bede3623318310e9e60/resources/settings.xml#L16-L24

But I'm not sure where he handles the logic. However, his method, or something similar, seems a good way.

**Comment by zach-morris** [comment]
OK, I think I get this request.  I'll look into it.

**Comment by drinfernoo** [comment]
Let me know if I can help ;)

**Comment by zach-morris** [comment]
OK, I've almost got this finished.
<img src="https://i.imgur.com/38yEy4V.png" width="400" height="300">
But there's one 'issue' is that depending on the skin, the viewtype will be something completely different.  Example:
Estuary Banner View (id=501) is the same as Titan's Landscape View is the same as Aura's Poster Wall View.

There's no way to know which skins support which viewtype IDs.  Currently, I just list the name of the view for Estuary / Titan / Aura (since those are the ones I test with) along with the view ID.
<img src="https://i.imgur.com/N5LAX8l.png" width="400" height="300">

**Comment by drinfernoo** [comment]
The other add-ons I've seen that implement a system like this give the ability to enter the ID manually. I'm not sure if that would work for you, but it would work for me. Glad to see this is still being worked on, in any case.

**Comment by zach-morris** [comment]
This should work now.  If possible please try 2.1.0 and let me know how it works

**Comment by zach-morris** [comment]
Closing this as it's implemented.  will add additional views when requested
