### ISSUE TITLE
Typo in sx05re_launch.sh

### ISSUE THREAD

**Issue by Rensvind** [zach-morris/plugin.program.iagl#41]
There is a typo in the following line
https://github.com/zach-morris/plugin.program.iagl/blob/312794ee9b9bdca7e41b5b55c8c123ce3654f7e8/resources/bin/sx05re_launch.sh#L8

The path should be 
/storage/.kodi/addons/plugin.program.**iagl**/resources/bin/sx05re.start "$@"

**Comment by zach-morris** [comment]
Thanks
