### ISSUE TITLE
Recent Update of IAGL broke the addon?

### ISSUE THREAD

**Issue by zach-morris** [zach-morris/plugin.program.iagl#43]
Did a recent update to this addon break the addon?  No.  Well, kind of.  The issue is with the addon settings and language translation.  The settings need to be in the latest and greatest format (language agnostic) otherwise you'll get an error message.

Long story short:  Open up the addon settings, make sure your settings are correct, and then hit OK to have them be saved in the new format.  The addon should start working again after that.

**Comment by drinfernoo** [comment]
Is this due to an add-on update or changes with Kodi 18.0?

**Comment by zach-morris** [comment]
Addon.  The settings are now language translatable, rather than stored as english text, which requires the settings from the last version of the addon to be updated to the new version.  There's unfortunately no automated way (that I could find) to make that happen, so the user has to open the settings window, then hit save and the settings will save in the new format.

**Comment by zach-morris** [comment]
Closing this, as it was for info only and this functionality has been in the addon for several version updates
