### ISSUE TITLE
Help zach

### ISSUE THREAD

**Issue by angel7676** [zach-morris/plugin.program.iagl#44]
I'm having one issue maybe you can help me with. When I start up a game it downloads and it launches just fine the next day when I wanted to play that same game again the game downloads once again. It seems like every time I choose a game it download the game again. is there a way to fix that? (I have the setting on do not download again) please help

**Comment by drinfernoo** [comment]
Change the cache size to something larger than 0.

**Comment by angel7676** [comment]
I haveit on the highest setting 64g and thanks for answering btw

**Comment by drinfernoo** [comment]
There's also an option for "If ROM exists locally". Make sure that isn't set to download again anyway.

**Comment by zach-morris** [comment]
Verify you have the latest version installed (2.0.7), set cache to non-zero in settings, or set an [alternate download location](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to) for that particular game list, and then leave 'If ROM exists locally' set to 'Do Not Download Again'

**Comment by angel7676** [comment]
You are the man or woman......it worked but I notice dreamcast doesn't work. I hear the load screen but no picture

**Comment by drinfernoo** [comment]
@angel7676 Dreamcast cores for libretro are device-dependent, and there is no core for RetroArch on Android, for example. In nay case, core compatibility (or lack thereof) is out of the scope of this project.

**Comment by angel7676** [comment]
I'm running on Windows computer. And it shows multiple cores for Dreamcast but only one works but it doesn't. When I start the game hear the load up screen but there is no picture and then nothing I just have to back out
