### ISSUE TITLE
Question about Nintendo 64. 

### ISSUE THREAD

**Issue by angel7676** [zach-morris/plugin.program.iagl#45]
Just wanted to know if anyone else's  Nintendo 64's audio is screwed for every game

**Comment by drinfernoo** [comment]
Not at all. Again, that is out of the scope of this project. IAGL has absolutely nothing to do with game or core performance, and is only the conduit through which Kodi can find games to launch via its built-in and/or external emulators.

**Comment by angel7676** [comment]
Thanks
