### ISSUE TITLE
Systems disappearing?

### ISSUE THREAD

**Issue by bongobil** [zach-morris/plugin.program.iagl#46]
Hi. Really glad to use iagl finally. I've noticed today that atari 2600 games aren't working for me in kodi, they download but the emulator doesn't seem to be there anymore, i was really enjoying yars revenge! I've tried installing the emulator through iarl but it doesn't get suggested once the file is downloaded. Have you disabled some of the emulators? Are we able to manually install the emulators to work (file association?) Many thanks.

**Comment by drinfernoo** [comment]
If you're using the built-in libretro compatibility from Kodi, but are still seeing 2600 lists in IAGL, then it must be an issue with Kodi, rather than IAGL. IAGL doesn't supply *any* emulators, as it is only the conduit through which Kodi is able to find and launch ROMs.

**Comment by zach-morris** [comment]
Yes, as suggested, you can get game emulators for Kodi by following the steps in the [wiki](https://github.com/zach-morris/plugin.program.iagl/wiki/1.--Setup#setup-with-retroplayer).  IAGL only provides the list of content, not the emulators.
