### ISSUE TITLE
How do i add my own rom folders?

### ISSUE THREAD

**Issue by bongobil** [zach-morris/plugin.program.iagl#47]
Hi. Is there a way to add rom folders on my own drive?

**Comment by drinfernoo** [comment]
Not really, except by making your own game list. You should be able to add them natively in Kodi 18.0, though.

**Comment by zach-morris** [comment]
For local content, check out [AEL](https://github.com/Wintermute0110/plugin.program.AEL) addon.  Otherwise, you should just be able to add your local game folder to Kodi, then browse to it from the games section.
