### ISSUE TITLE
[armv7][kodi18] Yabuse - Cannot initialize ISO-File Virtual Drive

### ISSUE THREAD

**Issue by Philps** [zach-morris/plugin.program.iagl#49]
Trying to load Saturn Games via Yabuse end in internal failure

PasteBinLog: https://pastebin.com/9zvSvAg3

**Comment by drinfernoo** [comment]
This is likely an issue with Kodi's implementation of libretro, rather than IAGL.

**Comment by zach-morris** [comment]
The default for IAGL for the saturn game list is a bin/cue I believe, not an ISO.  The default emulator should be [beetle saturn](https://github.com/kodi-game/game.libretro.beetle-saturn)
