### ISSUE TITLE
[armv7][kodi18] Sega CD not working on Android with Kodi18

### ISSUE THREAD

**Issue by Philps** [zach-morris/plugin.program.iagl#50]
After downloading the Mega CD Rom and launching it, the screen goes black and does nothing

Kodi Debug Log: https://pastebin.com/r4Uh8cUa

**Comment by drinfernoo** [comment]
This is likely an issue with Kodi's implementation of libretro, rather than with IAGL.

**Comment by zach-morris** [comment]
Agreed.  This is an issue with Kodi and the addon genesis.plus.gx.   You can open an issue for that addon [here](https://github.com/kodi-game/game.libretro.genplus) (with a full debug log).
I will note that I tried this game in both genesis.plus.gx and picodrive.  I got a black screen with gx and it worked with picodrive, so you could try that.
