### ISSUE TITLE
Error changing default download directory

### ISSUE THREAD

**Issue by manurafal** [zach-morris/plugin.program.iagl#51]
Kodi version: 17.6
System: Android 8.1
Device: Tvbox amlogic s905x2
Language: Spanish

When I try to change the default directory of a platform, an error appears. Attached record of the Kodi.log

00:28:21.936 T:18446744072618592624  NOTICE: IAGL:  Lets Play!
00:28:24.514 T:18446744072541972848 WARNING: Skin Helper Service --> Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skin.helper.service/resources/lib/listitem_monitor.py", line 312, in set_listitem_details
                                                details["year"], details["imdbnumber"], details["tvshowtitle"])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.simplecache/lib/simplecache.py", line 284, in decorated
                                                result = func(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.metadatautils/lib/metadatautils.py", line 280, in get_imdbtvdb_id
                                                imdbid = self.get_omdb_info("", title, "", content_type).get("imdbnumber", "")
                                            AttributeError: 'NoneType' object has no attribute 'get'
00:28:24.514 T:18446744072541972848   ERROR: Skin Helper Service --> Exception in resources.lib.listitem_monitor ! --> 'NoneType' object has no attribute 'get'
00:28:25.024 T:18446744072541972848  NOTICE: IAGL:  Lets Play!
00:28:40.309 T:18446744072541972848  NOTICE: Previous line repeats 1 times.
00:28:40.309 T:18446744072541972848 WARNING: Attempt to use invalid handle -1
00:28:43.295 T:18446744072541972848   ERROR: EXCEPTION: Error: GetSources given  is NULL.
00:28:43.309 T:18446744072541972848   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Error: GetSources given  is NULL.
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iagl/addon.py", line 1173, in <module>
                                                plugin.run(sys.argv)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iagl/addon.py", line 422, in update_game_list
                                                new_value = IAGL.get_user_context_entry(current_key,current_game_list[current_key],current_choice)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 2235, in get_user_context_entry
                                                new_value = current_dialog.browse(0,self.loc_str(30337),'')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.kodi-six/libs/kodi_six/utils.py", line 55, in wrapper
                                                return py2_decode(func(*mod_args, **mod_kwargs))
                                            RuntimeError: Error: GetSources given  is NULL.
                                            -->End of Python script error report<--
00:28:48.696 T:18446744073325860004 WARNING: CPeripheralBusAndroid: failed to update input device with ID 2 because it couldn't be found

**Comment by zach-morris** [comment]
Thanks for the debug log.  Interesting that this fails for you but not on other OS's.  I've added a change that will try a slightly different method if the first fails.

I'm guessing if you[ add a files source in Kodi](https://kodi.wiki/view/Adding_video_sources), the error will also go away.  The error seems to be that Kodi doesn't have anywhere to browse.

**Comment by manurafal** [comment]
I have done what you told me, but the error continues.

**Comment by manurafal** [comment]
What can I do to solve it?

**Comment by zach-morris** [comment]
You can get the [latest commit](https://github.com/zach-morris/plugin.program.iagl/archive/main.zip), overwrite the addon files on your box, and test it if you like.  Otherwise, I will push an update to my repository in the near(ish) future.

**Comment by manurafal** [comment]
I install de latest commit and now I can not download games and have the next errors:

14:09:42.891 T:18446744072782645616  NOTICE: IARL:  Lets Play!
14:09:43.252 T:18446744072782645616   ERROR: IARL:  Error copying file from /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iarl/resources/bin/7za/7z.android to /data/data/org.xbmc.kodi/lib/7z.android\[Errno 13] Permission denied: '/data/data/org.xbmc.kodi/lib/7z.android'
14:09:43.466 T:18446744072782645616  NOTICE: [resources.lib.xbmcswift2b] Request for "/History" matches rule for function "last_played"
14:09:43.466 T:18446744072782645616  NOTICE: IARL:  No game history file was found
14:09:43.467 T:18446744072846047600   ERROR: GetDirectory - Error getting plugin://plugin.program.iarl/History
14:09:45.973 T:18446744072487434608  NOTICE: IARL:  Lets Play!
14:09:46.006 T:18446744072487434608   ERROR: IARL:  Error copying file from /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iarl/resources/bin/7za/7z.android to /data/data/org.xbmc.kodi/lib/7z.android\[Errno 13] Permission denied: '/data/data/org.xbmc.kodi/lib/7z.android'
14:09:48.131 T:18446744072485337456  NOTICE: IARL:  Lets Play!
14:09:48.143 T:18446744072487434608  NOTICE: [resources.lib.xbmcswift2b] Request for "/History" matches rule for function "last_played"
14:09:48.151 T:18446744072487434608  NOTICE: IARL:  No game history file was found
14:09:48.151 T:18446744072692955504   ERROR: GetDirectory - Error getting plugin://plugin.program.iarl/History
14:09:48.536 T:18446744072485337456   ERROR: IARL:  Error copying file from /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iarl/resources/bin/7za/7z.android to /data/data/org.xbmc.kodi/lib/7z.android\[Errno 13] Permission denied: '/data/data/org.xbmc.kodi/lib/7z.android'
14:09:48.711 T:18446744072485337456  NOTICE: [resources.lib.xbmcswift2b] Request for "/History" matches rule for function "last_played"
14:09:48.711 T:18446744072485337456  NOTICE: IARL:  No game history file was found
14:09:48.712 T:18446744072737519984   ERROR: GetDirectory - Error getting plugin://plugin.program.iarl/History
14:09:48.896 T:18446744072877160816   ERROR: Control 500 in window 10025 has been asked to focus, but it can't
14:09:49.390 T:18446744072690882928  NOTICE: IAGL:  Lets Play!
14:10:14.146 T:18446744072877160816  NOTICE: Previous line repeats 4 times.
14:10:14.146 T:18446744072877160816   ERROR: GetDirectory - Error getting plugin://plugin.program.iagl/game/GBA_ZachMorris/Cars+-+Motori+Ruggenti+%28Italy%29
14:10:14.148 T:18446744072877160816   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.iagl/game/GBA_ZachMorris/Cars+-+Motori+Ruggenti+%28Italy%29) failed
14:10:15.940 T:18446744072782645616 WARNING: CSkinInfo: failed to load skin settings
14:10:16.126 T:18446744072692955504   ERROR: Could not encode thumbnail: special://masterprofile/Thumbnails/2/2cb16bc4.png
14:10:16.126 T:18446744072692955504   ERROR: Failed to CreateThumbnailFromSurface for special://masterprofile/Thumbnails/2/2cb16bc4.png
14:10:22.729 T:18446744072782645616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc2 in position 6: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 4069, in onClick
                                                self.action_download_only()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 4093, in action_download_only
                                                download_and_process_success = IAGL_DL.download_and_process_game_files() #Download files
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 3591, in download_and_process_game_files
                                                self.check_if_files_exists_locally()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 3555, in check_if_files_exists_locally
                                                current_existing_files_fullpath = [item for sublist in [get_all_files_in_directory_xbmcvfs(x) for x in set(self.current_download_locations)] for item in sublist if os.path.splitext(item)[-1].lower() not in self.IAGL.remove_these_filetypes]
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iagl/resources/lib/main.py", line 4317, in get_all_files_in_directory_xbmcvfs
                                                current_files = current_files+[os.path.join(directory_in,dd,ff) for ff in files_in_dir2 if ff is not None]
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/posixpath.py", line 73, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 6: ordinal not in range(128)
                                            -->End of Python script error report<--
14:10:46.426 T:18446744072877160816   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
14:10:49.253 T:18446744072492677488  NOTICE: IARL:  Lets Play!
14:10:49.357 T:18446744072492677488   ERROR: IARL:  Error copying file from /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iarl/resources/bin/7za/7z.android to /data/data/org.xbmc.kodi/lib/7z.android\[Errno 13] Permission denied: '/data/data/org.xbmc.kodi/lib/7z.android'
14:10:50.175 T:18446744072690882928  NOTICE: IARL:  Lets Play!
14:10:50.248 T:18446744072690882928   ERROR: IARL:  Error copying file from /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iarl/resources/bin/7za/7z.android to /data/data/org.xbmc.kodi/lib/7z.android\[Errno 13] Permission denied: '/data/data/org.xbmc.kodi/lib/7z.android'
14:10:50.844 T:18446744072492677488  NOTICE: [resources.lib.xbmcswift2b] Request for "/History" matches rule for function "last_played"
14:10:50.845 T:18446744072492677488  NOTICE: IARL:  No game history file was found
14:10:50.845 T:18446744072667335024   ERROR: GetDirectory - Error getting plugin://plugin.program.iarl/History
14:10:52.488 T:18446744072628468080  NOTICE: IARL:  Lets Play!
14:10:52.551 T:18446744072690882928  NOTICE: [resources.lib.xbmcswift2b] Request for "/History" matches rule for function "last_played"
14:10:52.711 T:18446744072690882928  NOTICE: IARL:  No game history file was found
14:10:52.712 T:18446744072692955504   ERROR: GetDirectory - Error getting plugin://plugin.program.iarl/History
14:10:52.805 T:18446744072628468080   ERROR: IARL:  Error copying file from /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.iarl/resources/bin/7za/7z.android to /data/data/org.xbmc.kodi/lib/7z.android\[Errno 13] Permission denied: '/data/data/org.xbmc.kodi/lib/7z.android'
14:10:53.719 T:18446744072737519984   ERROR: GetDirectory - Error getting
14:10:53.840 T:18446744072628468080  NOTICE: [resources.lib.xbmcswift2b] Request for "/History" matches rule for function "last_played"
14:10:53.840 T:18446744072628468080  NOTICE: IARL:  No game history file was found
14:10:53.840 T:18446744072667335024   ERROR: GetDirectory - Error getting plugin://plugin.program.iarl/History
14:10:56.086 T:18446744072877160816   ERROR: GetDirectory - Error getting return
14:10:56.086 T:18446744072877160816   ERROR: CGUIMediaWindow::GetDirectory(return) failed
14:10:56.468 T:18446744072877160816   ERROR: GetDirectory - Error getting plugin://plugin.program.super.favourites/?cmd=ActivateWindow(10001%2c%22addons%3a%2f%2fsources%2fexecutable%2f%22%2creturn)&content_type&image=DefaultAddonProgram.png&label=Add-ons%20de%20programas&mode=650
14:10:56.471 T:18446744072877160816   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.super.favourites/?cmd=ActivateWindow(10001%2c%22addons%3a%2f%2fsources%2fexecutable%2f%22%2creturn)&content_type&image=DefaultAddonProgram.png&label=Add-ons%20de%20programas&mode=650) failed
14:11:05.363 T:18446744072782645616 WARNING: CSkinInfo: failed to load skin settings
14:12:48.974 T:18446744072782645616 WARNING: Attempt to use invalid handle -1

**Comment by manurafal** [comment]
I have also installed the IARL and it works well, I can download games and change the default directory of a platform, but with the IAGL I have problems.

**Comment by zach-morris** [comment]
Do you have some weird non-ascii character in your folder name?

**Comment by manurafal** [comment]
/Juegos/Game Boy Advance/

**Comment by zach-morris** [comment]
The error shows:
```
Error Type: <type 'exceptions.UnicodeDecodeError'>
Error Contents: 'ascii' codec can't decode byte 0xc2 in position 6: ordinal not in range(128)
```
Which appears to mean there's a characther "¥" in your path, which python does not like.  If possible, post a debug log (i.e. turn debug logging ON in Kodi, [see #2 here](https://kodi.wiki/view/Log_file/Easy)) and or post your game list xml header and post it to [hastebin](https://hastebin.com/) rather than paste it in a comment.

**Comment by manurafal** [comment]
You're right, there are some files with ANSI encoding and not UNICODE. I indicate some of which have ANSI condificación, please change them to UNICODE coding.

GBA_ZachMorris.xml
ZX_Spectrum_ZachMorris.xml
Sega_CD_ZachMorris
Sega_SG1000_ZachMorris
SNES_ZachMorris
TG16_Bestof_ZachMorris
TG16_ZachMorris
VirtualBoy_ZachMorris
Win31_ZachMorris
Wonderswan_Color_ZachMorris
Wonderswan_ZachMorris
PowderToy_ZachMorris
PS1_ZachMorris
Quake_Lefty420
REminiscence_ZachMorris
SCUMMVM_ZachMorris
...............

**Comment by zach-morris** [comment]
None of the dat files have an encoding line in them, python assumes utf-8 according to the documentation.  I don't think that would resolve the issue since it's python is complaining about the character.  I also can't recreate this issue, so it seems like some difference with your OS or version of Kodi...

Does your path have a non-ascii character in it?  If so, does a path with only ascii characters in it work?

**Comment by manurafal** [comment]
I changed the encoding of the files to UTF8 and now everything works fine. My path only has ascii characters.

**Comment by zach-morris** [comment]
Are you referring to adding the following to the file?
```
<?xml version = "1.0" encoding = "UTF-8" standalone = "no" ?>
```
If not, what exactly did you add to the xml file?

**Comment by manurafal** [comment]
I have not modified the content, just changed the encoding of the file to UTF8.
I use the notepad ++ program, I only open the file and I record it again as UTF8, but I do not modify the content.

**Comment by zach-morris** [comment]
OK.  Well it must be something the android box is doing to the files then.  Since they show by default as UTF-8 on my computer.  I've added the xml encoding line to every dat file, so that will hopefully resolve the issue
