### ISSUE TITLE
Downloaded size incorrect

### ISSUE THREAD

**Issue by ljmellor** [zach-morris/plugin.program.iagl#53]
I am currently downloading a game which claims to have downloaded 5.6GB / 841.8MB, upon checking the current file size it is sitting at 243MB according to the OS (ubuntu). Something isn't right here. Great add-on by the way, just awaiting the official binary addons for my OS of choice.

**Comment by zach-morris** [comment]
Which game and game list?

**Comment by ljmellor** [comment]
The Curse of monkey Island from scummvm

**Comment by zach-morris** [comment]
I'm guessing this is similar to #52, so I'm closing this one.  Also working on an update to the scummvm game list to the latest available (2.0 i believe)
