### ISSUE TITLE
the game does not start (RetroPie+Kod17.6i+Gamestarter addon)

### ISSUE THREAD

**Issue by githubrn** [zach-morris/plugin.program.iagl#59]
system:
Pi + Linux retropie 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux
Kodi 17.6
IAGL
Gamestarter add-on (from gamestarter repository)
RetroArch (from gamestarter repository)

settings:
My System Type: Gamestarter Addon
Emulator Launcher: Kodiretroplayer (correct???)

the game does not start, any ZX-80
[kodi.log](https://github.com/zach-morris/plugin.program.iagl/files/2905332/kodi.log)

**Comment by zach-morris** [comment]
It should be external.  Gamestarter, while a Kodi addon, uses external executables/binaries to launch the game.  I updated the [wiki](https://github.com/zach-morris/plugin.program.iagl/wiki/1.--Setup#setup-with-gamestarter-addon-rpi-and-x86) to be (slightly) more clear.

**Comment by zach-morris** [comment]
Closing as a duplicate to #69.  Retropie support is being worked on
