### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by 83RL** [zach-morris/plugin.program.iagl#6]
any way you can add kbps/remaining time and remaining kbpd?

here is downloader.py i pulled from romflix downloader.

[downloader.py.txt](https://github.com/zach-morris/plugin.program.iagl/files/2223892/downloader.py.txt)

i tried to mod in myself but your download script is way different lol

thank you in advance

**Comment by zach-morris** [comment]
Probably not remaining time as that would require some calculation of rate, and it would be [way off](https://i.stack.imgur.com/CFuan.png) a lot of the time.
I might be able to add some sort of file size info though.
