### ISSUE TITLE
Split out "Best of" list for Gameboy Classic and Gameboy Color

### ISSUE THREAD

**Issue by Clutz450** [zach-morris/plugin.program.iagl#62]
Every other game list is specific to one console except for the "Internet Archive Best of - Gameboy Classic and Color" which mixes in games from both systems.  Is it possible to create a "Best of" list for just Gameboy Classic and another "Best of" list for Gameboy Color.  Thank you.

**Comment by zach-morris** [comment]
It's one list because I couldn't find 50 'best of' games for each system (in the past I've made the lists based on sources on the internet, and there are usually several 50 best of lists for each).  It also made sense to combine these since all the cores I'm aware of play both classic and color.
You can of course, [make your own list](https://github.com/zach-morris/plugin.program.iagl/wiki/3.--Create-your-own-lists).  The included list xml file is [here](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/data/dat_files/GB_Classic_Color_Bestof_ZachMorris.xml), and you could edit that to make two if you wanted to.

**Comment by Clutz450** [comment]
Thank you for your explanation.  The reason why I wanted this list split goes hand in hand with my other issue I posted about wanting each system downloaded to a seperate folder for ease of shader and overlay setup.  So as it stands, the Best of Gameboy and Gameboy Color list will be the only list o wont be able to do that set up with.  But I can work with that if that's the only issue.  Thanks again.

**Comment by drinfernoo** [comment]
@Clutz450, you could make a "favorites" list for each system, and even set them to use different cores 👍

**Comment by Clutz450** [comment]
@drinfernoo Thanks for the tip.  I actually like all the lists that are already created.  It's basically just the Best of Gameboy and Gameboy Color that I wish were different.  I'll keep your idea in mind and try it out later.  Thanks again.

**Comment by zach-morris** [comment]
OK, I think based on the request, it's just easier to make two lists.  You got 50 games from each that are 'best'?

**Comment by drinfernoo** [comment]
@zach-morris Does it have to be 50? What about just 25?

**Comment by drinfernoo** [comment]
Also, [this list](https://en.m.wikipedia.org/wiki/List_of_best-selling_Game_Boy_video_games?wprov=sfla1) from Wikipedia has the top 53 games in total, with 36 being GB, and 17 being GBC... Not exactly a round number but maybe something to start with.

**Comment by Clutz450** [comment]
I see what you mean about it being difficult to make a list to 50 for each.  I usually rely on MetaCritic when looking for lists like that but for some reason they don't have one for Game Boy and Game Boy Color.  And the rest of the lists I've found online either combine the 2 systems or don't make it to 50 themselves.  But maybe this list from Wikipedia would help.  It is a list of the highest selling Game Boy and Game Boy Color games.  If you like the list you already have, then maybe after you split it out, you could fill in the rest with the highest selling ones to make your list to 50 provided all of these games aren't already on your list.

https://en.wikipedia.org/wiki/List_of_best-selling_Game_Boy_video_games

The other games I feel you could add to Game Boy Color at least are any music and rhythm games like the Dance Dance Revolution and other Bemani games.  

And finally, if you are still looking for games to add, maybe you could add in games that have full achievements set up for them through Retroachievements.  For Game Boy, they only have 93 games with Achievements and for Game Boy Color they only have 52. 

https://retroachievements.org/gameList.php?d=&c=4&f=1&s=0
https://retroachievements.org/gameList.php?d=&c=6&f=1&s=0

**Comment by drinfernoo** [comment]
[This list](https://gizmodo.com/these-are-the-25-games-the-game-boy-classic-edition-sho-1818843497) might also be good for GB 👌
