### ISSUE TITLE
Advanced option to download to folder with emu_name

### ISSUE THREAD

**Issue by Clutz450** [zach-morris/plugin.program.iagl#63]
I have been messing around with shaders and overlays in retroarch and think they are great.  You can have a shader and overlay set up exactly how you want it and then save it to a core override so that whenever that core is loaded it will automatically reapply the settings for the overlay and shaders I set up for it before.  The only problem is for systems that use the same core, for example Gameboy Classic and Gameboy Color.  They both use the Gamebatte core so if I try to save my Gameboy Classic settings to that core, it will also apply them to the Gameboy Color games I try to use as well.  Retroarch has a fix to this by being able to "save content directory overrides" meaning that if I had my roms seperate in different folders called "Gameboy" and another folder called "Gameboy Color" that any game launched from the Gameboy folder will apply the settings I want for the Gameboy and any game launched from the Gameboy Color folder will apply the settings I saved for the Gameboy Color games.  But since IAGL saves all roms to a common folder, that option cannot be used.  So what I am thinking (and I have no idea if this will actually work but I'd like to try) is if the games could be downloaded to a folder named after their game list name that I would be able to save a content directory override to that and this would alleviate my current issue I am having with my Gameboy and Gameboy Color games.  I know I wrote a lot but I hope you understand what I am asking.  Please let me know if you are in any kind of chat app like Discord and if needed I can explain my idea further.  Thank you.

**Comment by zach-morris** [comment]
You can change the folder the files are saved to  See [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to).  Would that get you what you wanted?

**Comment by Clutz450** [comment]
That might work.  I'll check that out.  But can I keep those folder in the cache folder so that when my cache folder hits its limit, it automatically deletes it.  Like I am doing this all on my cell phone and I only want to have about 1 gig worth of roms.  Mainly for when I am trying out game like PS1 that are several hundred meg in size.

**Comment by drinfernoo** [comment]
@Clutz450, the problem with having "content directory overrides" in IAGL's cache folder would be that they would get wiped as well, wouldn't they?

**Comment by zach-morris** [comment]
> That might work. I'll check that out. But can I keep those folder in the cache folder so that when my cache folder hits its limit, it automatically deletes it. Like I am doing this all on my cell phone and I only want to have about 1 gig worth of roms. Mainly for when I am trying out game like PS1 that are several hundred meg in size.

If you set the download path to a folder in the temp_iagl folder (manually), it will be deleted and not recreated after it's purged, so that wouldn't work.  You'd have to set the location to something else, then manually delete the files in your alternate location

**Comment by zach-morris** [comment]
Another option that might do what you want.  You can manually enter a command line for each game list and add an --appendconfig argument that retroarch uses.  Then have a config file that defines the overlays for each system.

**Comment by Clutz450** [comment]
@drinfernoo I don't know if those content directory overrides actually save in the content folder.  I thought they saved in the config folder. 

@zach-morris I created individual folders for a few systems (NES, GB, GBC, GBA) in the cache folder, my overlays and shaders were saved as content directory overrides, and everything worked great.  It was very tedious to do but it got the job done.  

But if the folders being deleted and not being created again is going to cause a problem then obviously that's not going to work.  Not really sure how appending an overlay works but if you believe that is a better way to go then I'd be willing to try it out and see if I get the results I am looking for.  Just let me know what I'd have to do and I'll let you know how I make out.  Thanks.

**Comment by zach-morris** [comment]
Well, I don't use overlays, but I did some digging.  There are core override folders that Retroarch accepts.  See [here](https://docs.libretro.com/guides/libretro-overlays/).  You can put the overrides in the Retroarch config folder path and it wouldn't even be in the IAGL path.

So for example, when I start Nestopia, I see that Retroarch is looking for config overrides in the path:
```
path_to_retroarch_config/RetroArch/config/Nestopia/
```
So what I did was copy an override from thebezelproject, and put it in that folder:
```
path_to_retroarch_config/RetroArch/config/Nestopia/Super Mario Bros. 3 (USA) (Rev A).cfg
```
The contents of the config was:
```
overlays = 1
overlay0_overlay = "/path_to_image/Super Mario Bros. 3 (USA).png"
overlay0_full_screen = true
overlay0_descs = 0
```

Launched the game from IAGL, and the overlay was displayed.
<img src="https://i.imgur.com/r4y0fyt.png" width="525" height="450">

This seems much easier than IAGL trying to configure this.  I played around with appendconfig but couldn't get it to do the same thing for some reason.

**Comment by drinfernoo** [comment]
@zach-morris Yes, it's somewhat easy to set up overlays and shaders per-core, but his "issue" is that since the Best Of list for GB and GBC are the same *list*, so they launch with the same *core*, this negating the usefulness of per-*core* overrides in the case of those two handhelds.

**Comment by zach-morris** [comment]
OK.  I get it now.  If thats really the ultimate issue, I'd rather make two lists ;-) . Now all I need is a reasonable list of 50ish 'best of' games for both handhelds.

**Comment by Clutz450** [comment]
Thanks for looking into it further.  The best idea is to just set up core overrides for each core so that when retroarch loads up that core, the settings are already there for overlays, shaders, and anything else I have set up.  This would allow me to still have all the roms download into the cache folder and purge themselves without issue when I hit my size limit.  

But the problem lies in systems that use the same core like Gameboy Classic and Gameboy Color.  (This would probably also happen with Sega Genesis and Game Gear as I believe they too use the same core but I haven't tested that out yet).  So my work around for systems that use the same core was to change the download path to each system and have it download into it's own system folder (ie. GBA, GBC, GB) and then set RetroArch to use Content Directory Overrides.  Doing it this way does work rather well but then adds in a couple of new issues.  1, it's very tedious to set up each indivual list to download to a new folder.  2, as you stated before, if I put those folders in the cache folder, those folders would be purged and not recreated causing me to have to manually set up all my folders again.  3, if I set up folders outside of the cache folder, I lose the ability to have IAGL automatically purge those roms when I hit my size limit and have to delete them manually.  And 4, this idea doesn't work with the Best of Gameboy Classic and Gameboy Color as both systems use the same core and will be downloaded to the same folder.  

The other 2 work arounds I've been thinking about would be to set up retroarch to use per game overrides.  This would mean that for every game I load up, I would have to reapply all my settings and save it to that game.  That would be very tedious but would allow IAGL to remain as is (no changes to download paths or changes in Game Lists) and would allow the cache folder to delete itself and not cause any issues.  

The other work around would be to make it so that every system (or game list) used a different core.  This would allow me to set up overrides per core and again nothing would have to be changed in IAGL.  I personally don't like this idea as I like using Gamebatte for both Gameboy Classic and Gameboy Color.  But I guess I could experiment with the other cores and find another one I like.

So in conclusion (a TL:DR if you will), what i think would be best is if there was an option for when you manually set the download path per list that you could also set that new path as a cache folder that you can have purged at a certain size limit.  That would allow me to have each game downloaded to its respective console folder, set up per content directory overrides, and keep the ability to have my games purged automatically.  

I'm not sure how difficult an option like that would be to add but in my opinion I feel like that would be best as in getting me everything I am looking for with the minimal amount of work on your end.  But in the end, you've already created an amazing program I thoroughly enjoy so if you don't agree and I have to put in a little extra work on my end to get things the way I want them I really won't mind.  Thanks again for hearing my ideas and I look forward to what you think.

**Comment by HydrelioxGitHub** [comment]
Sorry for posting here if it's not relevant but when I open the contextual menu on a game, I only have the option to add it as a favorite and not change the download path. 
What am I missing ?

**Comment by zach-morris** [comment]
You can only change the download path on the game list level.  Select a game list and bring up the context menu.  See [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to).

**Comment by HydrelioxGitHub** [comment]
Ok I've got it. On the FAQ I've read : 

To do change the download location:

Highlight the game archive of interest
Bring up the context menu (right click or press c)
Choose 'Update Download Path' and follow the prompts

The game archive misleading me, but the game list word is clearer ... at least for me !

**Comment by HydrelioxGitHub** [comment]
Thanks btw.

**Comment by zach-morris** [comment]
Advanced option should now be available to organize the cache folder.  The organized folder will use the emu_description tag in the xml file, converted to a 'safe folder' name (unix friendly, remove all strange characters, etc)

**Comment by Clutz450** [comment]
Thanks.  I'll have to test this out.  I'll let you know what I think.

**Comment by jordanadania** [comment]
How do I find the advanced options? I have successfully changed my cache folder to an external device, but how would I use organized folders by system?
