### ISSUE TITLE
Default core associations?

### ISSUE THREAD

**Issue by drinfernoo** [zach-morris/plugin.program.iagl#65]
Where does the add-on specify the default RetroArch core associations? I know that the launch commands themselves are in `external_command_database.xml`, and that the core associations *end up* getting saved into the `.xml` for each list, but where is it defined that the N64 list gets assigned to the Mupen64 core, for example?

I know that I can always change this from the context menu, but I'd like to know where the defaults are that get set by the wizard.

**Comment by zach-morris** [comment]
They're in [this line](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/lib/run_IAGL_wizard.py#L23)
I have a script to auto generate that line from a spreadsheet (see attached).  In the past I tried to keep up the compatibility list in the wiki to coincide with what I have in the wizard, but things change too often in Retroarch for me to keep up with (along with actually trying to test them all is impossible).
[IAGL_Wizard.ods.zip](https://github.com/zach-morris/plugin.program.iagl/files/2994869/IAGL_Wizard.ods.zip)

**Comment by drinfernoo** [comment]
@zach-morris Ah, I knew I had seen them, I just couldn't remember where 👍

**Comment by zach-morris** [comment]
Closing this issue, see #71 for a place to suggest changes
