### ISSUE TITLE
I can't change download path via open context menu

### ISSUE THREAD

**Issue by mosquito520** [zach-morris/plugin.program.iagl#66]
Hi, I've install IAGL 2.1.0 to my Kodi 18.1, Libreelec 9.0.1 with my raspberry pi 2.

I've follow the FAQ
https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#2-where-are-the-games-downloaded-to
- Highlight the game archive of interest
- Bring up the context menu (right click or press c)
- Choose 'Update Download Path' and follow the prompts

But when I bring up the context menu as my attached screen shot
It does not contain the 'Update Download Path' item? only one item 'Add to my favorite' in Chinese
(My system language setting is Chinese)

Take by VNC remotely
![192 168 0 5:5900 (LibreELEC : 0) - VNC Viewer_027](https://user-images.githubusercontent.com/2183030/54934694-ea1d8e80-4f59-11e9-9cc8-3ac32d33db5e.png)

I've duplicate same phenomenon on Kodi 18.1 with my Linux mint,
Could you help to check it?

Thanks

**Comment by drinfernoo** [comment]
You're not selecting the game archive, you're selecting the game. You can only change the download path for an *entire list*, not for each individual game.

**Comment by zach-morris** [comment]
Yep, as stated, it's for the game list, not the individual game.   If for some odd reason you do want a different download location for one game, you can do that, but you have to manually edit the game list.  See rom_override_downloadpath [here](https://github.com/zach-morris/plugin.program.iagl/wiki/3.--Create-your-own-lists).

**Comment by drinfernoo** [comment]
@zach-morris If the functionality is already there, is there any reason why not to allow it from the context menu, on a per-game basis?

**Comment by zach-morris** [comment]
The only reason is that writing data in the middle of the xml file is cumbersome/slow, filled with potential issues of writing to the wrong spot, and the default game lists are setup all to be played by one particular emulator (so the need to download to a different spot isn't there).  I can't really think of a non-very-unique use case.

**Comment by mosquito520** [comment]
@drinfernoo @zach-morris 
Thanks for the reply:) I'll try it later (when I back to home:p)
