### ISSUE TITLE
Changed the default core mame2003_libretro to mame2003_plus_libretro?

### ISSUE THREAD

**Issue by Intel11** [zach-morris/plugin.program.iagl#67]
Hello, in this commit I have seen that you have changed the default core of mame2003_libretro to mame2003_plus_libretro:

https://github.com/zach-morris/plugin.program.iagl/commit/07f6f9aecce04620911e429222a00c01dbf29da5#diff-32c1b506f32879518afe4a143faed695

![image](https://user-images.githubusercontent.com/25161862/55277198-6520d500-52cb-11e9-8bc9-814069fb75d0.png)

If I choose the list of mame_2003 games, should I load the mame2003_libretro core?

Because now the mame2003 games load me the core mame2003_plus :(

Can you change the default core of the list of games mame2003 to mame2003_libretro?

Thank you

**Comment by zach-morris** [comment]
Yes, that seems to have been a bad copy/paste from my part.  I will update that.  Thanks for catching it.
