### ISSUE TITLE
Add game hacks

### ISSUE THREAD

**Issue by ccates21** [zach-morris/plugin.program.iagl#68]
Can you add this online?
*Removed*

**Comment by zach-morris** [comment]
Please do not attach any game files to this repository.  I will change this to a request to 'add game hacks' and keep it open

**Comment by ccates21** [comment]
Thanks, sorry!

**Comment by zach-morris** [comment]
Closing this, hacks are in work, and the requests is listed [here](https://github.com/zach-morris/plugin.program.iagl/issues/38).
