### ISSUE TITLE
Add retropie support, retroarena support (retropie fork for odroid) and implement a kodi shutdown mechanism

### ISSUE THREAD

**Issue by camatthew** [zach-morris/plugin.program.iagl#69]
The addon doesent work with retropie and I need it for my odroid xu4. Currently I found this for retropie https://retropie.org.uk/forum/topic/8230/start-game-from-command-line/3 , although I would prefer linux command support with stuff like adding %r as a placeholder for the rom name because I use a port that has different paths.

**Comment by camatthew** [comment]
By the way kodi works

**Comment by zach-morris** [comment]
If kodi works, can you try this using a [manually entered command line](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#3--i-want-to-use-emulator-xxx-instead) to verify you can launch a game from Kodi?

**Comment by camatthew** [comment]
Im using a fork called retroarena just change the name to retroarena and it will work

**Comment by camatthew** [comment]
The home directory is renamed to retroarena.

**Comment by camatthew** [comment]
Ans so is the opt directory

**Comment by camatthew** [comment]
I tried it and I got a glitchy window in addition I had to change the directory to retroarena

**Comment by camatthew** [comment]
The command only worked once but it doesent work anymore.

**Comment by camatthew** [comment]
Also pressing the start + select button will close the emulator

**Comment by camatthew** [comment]
I meant pi gaming

**Comment by camatthew** [comment]
Nvm it works everytime I just need to close kodi.

**Comment by camatthew** [comment]
@zach-morris  we still need to implement a shutdown mechanism

**Comment by zach-morris** [comment]
I found [this](https://forum.kodi.tv/showthread.php?tid=287826&pid=2456140#pid2456140) info which might resolve the shutdown / restart issues, but it looks like you need to install two additional packages to make it work:
```
sudo apt-get install at
sudo apt-get install kodi-eventclients-xbmc-send
```
Is that possible in retropie?

**Comment by camatthew** [comment]
Yes. Its posssible

**Comment by camatthew** [comment]
Also instead of kodi event clients xmbc send its kodi eventclients kodi send

**Comment by camatthew** [comment]
The kodi-send command works

**Comment by zach-morris** [comment]
OK, I think I figured this out. Added a shell script this evening for launching on a retropie setup with Kodi installed as a Port.
I will add retropie as a system option in IAGL and then this should use the same default chosen emulators within retropie.  In the meantime if you'd like to test, you can [download the shell script](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/bin/applaunch_retropie.sh) to your setup and then put in a manual command like the following for exernal launching:

```
"%ADDON_DIR%/resources/bin/applaunch_retropie.sh" 0 _SYS_ nes "%ROM_PATH%"
```

**Comment by camatthew** [comment]
My retroarena script requires this [retroarena scipt](https://pastebin.com/22Ru8W86). Retroarena uses emulation station but has different file paths for /opt. This software is for a odroid xu4.

**Comment by camatthew** [comment]
We sould have a dropdown menu for retropie and another one for retroarena.

**Comment by zach-morris** [comment]
i'm not familiar with retroarena.  Retropie can be installed on an odroid, [can't it](https://retropie.org.uk/docs/Odroid-XU3-XU4/)?

**Comment by camatthew** [comment]
Yes it can be installed however retroarena has more optimizations specific to the xu4

**Comment by camatthew** [comment]
Also retroarena has a ready to go system with kodi preinstalled for the xu4.

**Comment by camatthew** [comment]
For retroarena replace /opt/retropie with /opt/retroarena. The software is the same.

**Comment by zach-morris** [comment]
I update the script to accomidate both [here](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/bin/applaunch_retropie.sh#L56).

**Comment by camatthew** [comment]
Good I found it. I think it is ready for repository.zachmoris

**Comment by camatthew** [comment]
any news

**Comment by zach-morris** [comment]
2.1.1 was released with this implemented.  I didn't exhaustively test it, but it seems to work just fine for RetroPie
