### ISSUE TITLE
IAGL Favourite not working when using Liste by Genre vs. One Big List

### ISSUE THREAD

**Issue by Philps** [zach-morris/plugin.program.iagl#70]
I can only add Games to the IAGL Favourite List when using "One Big List", when using "List by Genre" i can only add them to Kodi Favourites not IAGL Favourite.

Tested: Kodi 18.1 
Skin: Estuary & Titan Skin
IAGL Version 2.1

**Comment by zach-morris** [comment]
Huh, I see that too for all options that aren't "One Big List".  Thanks for the report.
