### ISSUE TITLE
Add phillips cdi to retropie iagl

### ISSUE THREAD

**Issue by camatthew** [zach-morris/plugin.program.iagl#74]
https://retropie.org.uk/forum/topic/12671/tutorial-cd-i-emulation-in-retropie-via-lr-mess-warning-slowdown-especially-during-fmv-but-surprisingly-playable/2

**Comment by zach-morris** [comment]
Philips CD-i is already included.  I'm guessing you'd use "RetroPie System MAME libretro" as the external launch command, but it looks like it's dependent on how you setup the system on the retropie side (there isn't a standard setup already including this).  I didn't see MESS as even an availability.  What command would you send to retropie to start MESS?

**Comment by camatthew** [comment]
I domt think theres a way. Just hide cdi for retropie setups.

**Comment by zach-morris** [comment]
This is included now in the wizard
