### ISSUE TITLE
[Request] Command Wrapper version

### ISSUE THREAD

**Issue by arnoldsecret** [zach-morris/plugin.program.iagl#75]
Something in the likes of [ia-rcade](https://github.com/TiBeN/ia-rcade) except that it works with RetroArch and other command-line emulators for use with frontends like Attract-Mode.

**Comment by zach-morris** [comment]
I don't understand the request.  IAGL already does exactly what this appears to do.

**Comment by arnoldsecret** [comment]
IAGL is currently dependent on Kodi for the code to work, since Kodi can't be forced in a sleep mode when another program is running (in that case RetroArch), hardware-intensive cores like mednafen_psx and mednafen_saturn stutter. Certain SNES games and even pcsx_rearmed may stutter on low-end hardware.

**Comment by zach-morris** [comment]
OK, I think I understand the request, however I think thats currently out of the scope of this project.
