### ISSUE TITLE
Will this work with latest (as we speak) osmc?

### ISSUE THREAD

**Issue by Haris1977** [zach-morris/plugin.program.iagl#76]
I am about to download osmc for raspi 3. Will this add-on work with it? (i ask this because i do not know if there is an active retroplayer in osmc - as in libreelec for example)

Thanks!

**Comment by camatthew** [comment]
test it out as is.

**Comment by camatthew** [comment]
And run the setup wizard with retroplayer

**Comment by Haris1977** [comment]
Thanks i will try it (even though some emulators like fba is currently missing)

**Comment by zach-morris** [comment]
Assuming there are game emulator addons to install for OSMC, then it should work out of the box.  I'm not sure if OSMC supports external launching in any capacity (gamestarter addon for example), but I do not have any external launch coding in specific to OSMC currently.
