### ISSUE TITLE
PSX beetle HW problem

### ISSUE THREAD

**Issue by babbag3** [zach-morris/plugin.program.iagl#77]
Hey there. Attempting to run PSX games using PSX Beetle core in retroarch using IAGL from kodi 18.1 (windows) - works fine. If I swap the core so its using the PSX Beetle H/W core, then PSX games won't work at all - nothing - trying to start a game just goes straight back to kodi. Of note, starting retroarch manually, loading the same PSX Beetle H/W core manually and selecting the same game and starting it - works fine!

Any ideas? Thanks!

**Comment by IndyTheParrot** [comment]
I'll give that a go and get back here to report, thanks for following up :)

**Comment by zach-morris** [comment]
I've tried this on windows and dont have any issues launching PSX HW.  Kodi in my setup is set to fullscreen (as is Retroarch) and Kodi is also set to fullscreen window (not sure if that would actually make a difference)

**Comment by ITV4Free** [comment]
They may need to have the Retroarch bios packs loaded in

**Comment by drinfernoo** [comment]
@ITV4Free RetroArch does not endorse, include, or distribute BIOS files, but yes, you do typically need them for PSX emulation, among other systems.

**Comment by zach-morris** [comment]
Closing this issue for now.  Reopen if you still have issues and provide a log.
