### ISSUE TITLE
all arcade stuff doesent launch on Retropie/Retroarena and ends in a infinite loop

### ISSUE THREAD

**Issue by camatthew** [zach-morris/plugin.program.iagl#79]

**Comment by zach-morris** [comment]
I'm guessing this is going to be very dependant on the version of MAME / FBA that retropie uses and the versions available in IAGL.
MAME is at 193 (latest-ish available)
FBA is at 0.xxx.44 (latest available)

If the versions are not the same, then depending on the game it might not work.  MAME2003 should work assuming it's setup in Retropie correctly.

**Comment by camatthew** [comment]
martial masters on fba doesent work

**Comment by zach-morris** [comment]
If some games work and some dont, then that just confirms my suspicion.  What versions of MAME and FBA are in Retropie?

**Comment by camatthew** [comment]
For fba the version is the one you mentined. Im not sure about mame.

**Comment by zach-morris** [comment]
I think the only thing I could do is to hide the default MAME list then.  MAME 2003 should work and I think is what most people playing on retropie use.

**Comment by ITV4Free** [comment]
MAME 2010/2000 doesnt work i keep getting emulator errors

**Comment by zach-morris** [comment]
There is no romset available for MAME 2010/2000.  There's one specifically for MAME 2003 and MAME 2003-plus

**Comment by drinfernoo** [comment]
@ITV4Free Emulator errors are out of the scope of this project.

**Comment by zach-morris** [comment]
Closing this for now.  The current 'fix' was to remove Retropie as an option in the external launch commands for now - it never really worked well.  Main reason was that retropie itself has scripting that is monitoring what is 'in front', so putting IAGL in the middle to modify whats being launched/displayed was problematic.

I will create a new issue for supporting other setups in general.  A lot of the previous setups IAGL supported are no longer even updated (Gamestarter, LibreElec Forks, etc), so they've all been removed.
