### ISSUE TITLE
Search option(Random search)

### ISSUE THREAD

**Issue by NerdFlix** [zach-morris/plugin.program.iagl#8]
Hi Zach,
I had an error while attempting to search for the tag **Street fighter** for all games list, limiting the search to 100 results and with no filters used. I've checked  out the log and it seems that the error(**ValueError: sample larger than population**) occurs by calling the function **random_sample()** inside **get_games_from_random_query_as_listitems()** in **main.py**, line 1805.

Thanks in advance.

**Comment by zach-morris** [comment]
Yeah, i found that bug too.  Fix in work.  The issue is when the search comes up with less matches than requested

**Comment by NerdFlix** [comment]
Thanks

**Comment by NerdFlix** [comment]
Hi Zach,
my bad, I forgot to test this issue after the last update, I've tested it now and the issue is that no list is returned by both search option and  random play, no matter what filter or tag(title) you make the search. Windows 10 and kodi 18 Alpha 3

Here is my log(unfortunately, it doesn't give any clue about what's wrong):
https://pastebin.com/xUNddapm

Thanks in advance.
