### ISSUE TITLE
Add mame 2016

### ISSUE THREAD

**Issue by camatthew** [zach-morris/plugin.program.iagl#81]
Add mame 2016 because it has lots of roms with a non changing version of mame

**Comment by zach-morris** [comment]
I will close this and add your request in the game list requests issue

**Comment by zach-morris** [comment]
Just opening this conversation back up.  I tried MAME 2015 in retropie and it ran dog slow.  MAME 2003 is already available and works pretty well.  Does retroarena give different results?

If not, I'm thinking the best thing to do is just to hide all MAME versions for retropie/retroarena except MAME 2003 and FBA.

**Comment by camatthew** [comment]
Yes because I have a odroid  with a better cpu

**Comment by camatthew** [comment]
Also fba didnt work with martial masters
