### ISSUE TITLE
Start kodi with kodi command in retroarena

### ISSUE THREAD

**Issue by camatthew** [zach-morris/plugin.program.iagl#83]
Its more likely to work if we just run kodi from the cmd line

**Comment by zach-morris** [comment]
I'm not sure I understand the request.  You're suggesting changing [this](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/bin/applaunch_retropie.sh) script?  If so, how?

**Comment by camatthew** [comment]
#

**Comment by camatthew** [comment]
#84

**Comment by camatthew** [comment]
Push to main repo

**Comment by zach-morris** [comment]
I only update the repository after I get enough changes incorporated, so it will probably be a while before the repository is updated.  You can always download from the main repository and overwrite your local files.
