### ISSUE TITLE
Install only the cores.

### ISSUE THREAD

**Issue by manurafal** [zach-morris/plugin.program.iagl#85]
Is there any way to install all the cores without installing Retroarch ??

Thanks a lot.

**Comment by zach-morris** [comment]
Not sure I understand the question.  Install instructions are in the [wiki](https://github.com/zach-morris/plugin.program.iagl/wiki/0.--Installation).
If you are using Retroplayer within Kodi, then you do not need retroarch at all.  If you are using external launching, then you do.
