### ISSUE TITLE
IAGL not launching Retroarch correctly in MacOS

### ISSUE THREAD

**Issue by JayMonkey** [zach-morris/plugin.program.iagl#87]
Hi,

Im running the latest build of Kodi with the IAGL add-on and the latest build of Retroarch on a iMac running MacOS Mojave 10.14.4.

The issue i'm seeing is that when i select a title in IAGL it appears to launch Rertroarch correctly with the download title but Retroarch does not initially launch retroarch in full screen mode.

What happens is that Kodi minimizes and I'm left at the MacOS desktop and dock. I can see that Retorarch has launched as it has a dot underneath it in the dock, but i have to click on retroarch it in the dock with the mouse in order for it to go to full screen and use the downloaded title.

I'm guessing it has something to do with the way IAGL is launching retroarch on MacOS, its like its launching it as a background task rather than a foreground task ?

If you could point me at the right script files i can have a go at trying to figure out whats wrong and see if i can fix it.

Cheers
Jay

**Comment by zach-morris** [comment]
I develop on a Mac, and I don't have any issues.
I think it's a Retroarch setup issue you have.  Start the retroarch app, then press F to go full screen, then go to save configuration, then exit.  Next time Retroarch is launched from Kodi it should go full screen.

**Comment by JayMonkey** [comment]
Hi Zach,

Thanks for the quick reply, Retroarch is configured to launch in full screen, which it does if I manually launch it from the dock.

Just looked at the Kodi log and there are two odd errors before the final launch command (sh) :

2019-05-09 19:06:43.167 T:123145491099648  NOTICE: IAGL:  Lets Play!
2019-05-09 19:06:49.091 T:123145485733888  NOTICE: Previous line repeats 1 times.
2019-05-09 19:06:49.092 T:123145485733888   ERROR: GetDirectory - Error getting plugin://plugin.program.iagl/game/MAME_ZachMorris/Galaxian+%28Namco+set+1%29
2019-05-09 19:06:49.107 T:4541584832   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.iagl/game/MAME_ZachMorris/Galaxian+%28Namco+set+1%29) failed
2019-05-09 19:06:51.550 T:123145486270464  NOTICE: IAGL:  Sending Launch Command: "/Users/jay/Library/Application Support/Kodi/addons/plugin.program.iagl/resources/bin/applaunch.sh" "/Applications/RetroArch.app/Contents/MacOS/RetroArch"  -L "/Applications/RetroArch.app/Contents/Resources/cores/mame2003_plus_libretro.dylib" "/Users/jay/Library/Application Support/Kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/galaxian.zip"

Could that have anything to do with it ?

Cheers
Jay

**Comment by zach-morris** [comment]
You have chosen the option "close Kodi on launch" in the IAGL settings, although that shouldn't cause the problem you see.  This option is really meant for low power systems that can't run both Kodi and Retroarch at the same time.  I'd try setting the IAGL setting 'Close Kodi on Launch' to 'Disabled', then rerun the wizard/update the list settings and see if that solves your issue.

After you update the settings, the log will show a similar command:
```
NOTICE: IAGL: Sending Launch Command: "/Applications/RetroArch.app/Contents/MacOS/RetroArch" -L "/Applications/RetroArch.app/Contents/Resources/cores/mame2003_plus_libretro.dylib" "/Users/jay/Library/Application Support/Kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/galaxian.zip"
```

This command is the exact same command you could enter in a terminal window, so you can also just  copy/paste the command in a terminal to troubleshoot if you continue to have problems.  The error you see on the log is not really an error, more of a nuisance with the info window that IAGL opens to display info in Kodi (Kodi is complaining it can't find a file in a folder that doesn't actually exist).

**Comment by JayMonkey** [comment]
Hummm ...

Ok so i turned off 'Close Kodi on Launch' and re-ran the set up wizard, got the progress bar while it updated the games list and hot OK to confirm.

Now when i try to launch a game nothing happens, system just stays in kodi, if i CMD-TAB to finder once again Retroarch is sitting in teh dock with a dot under it, if i click on it, it runs teh game i selected in IAGL ?

Checked the log file but those two errors are still there ?

tried copying the launch command into terminal but it it seems that something is wrong, looks like retroarch starts then immediately quits. the downloaded zip is still in the temp_iagl folder as i have the cache set at 10GB ?

 Does this make any sense ?

Cheers
Jay

**Comment by zach-morris** [comment]
The errors in the Kodi log are not related to your issue (and in this case, are not an issue at all).

There is nothing in the command that is causing the application to launch in the background or foreground.  As far as I know, OSX will always launch new applications in the foreground.

If you paste the command into terminal and Retroarch does not launch, then you should get some sort of error in the terminal window, what error do you get?

**Comment by JayMonkey** [comment]
No error in terminal when i execute the launch command ..

![Screenshot 2019-05-09 at 21 10 36](https://user-images.githubusercontent.com/5662056/57483592-189fc080-729f-11e9-9d5f-15b6e07f49de.png)

In this instance nothing happens at all which seems odd as i would either expect Retorarch to start or a file not found error in terminal.

Is there a log file for Retroarch anywhere ?

Cheers
Jay

**Comment by zach-morris** [comment]
Well, I got nothin.  This is not how my mac behaves.  If you paste the command in, and Retroarch doesn't start and you don't get any info back in the terminal I'm not sure what the hell is going on.

If you type the first half of the command:
```
"/Applications/RetroArch.app/Contents/MacOS/RetroArch"
```

Then retroarch should start and you should get some feeback in the terminal. If it doesn't then you've saved the Retroarch app into some other location or your mac is borked.

If you type in the command and add --verbose to the end, you should get a lot more info:
```
"/Applications/RetroArch.app/Contents/MacOS/RetroArch" --verbose
```

If you type in the full command and add --verbose to the end, you should get a lot more info too:
```
"/Applications/RetroArch.app/Contents/MacOS/RetroArch" -L "/Applications/RetroArch.app/Contents/Resources/cores/mame2003_plus_libretro.dylib" "/Users/jay/Library/Application Support/Kodi/userdata/addon_data/plugin.program.iagl/temp_iagl/galaxian.zip"
 --verbose
```

**Comment by JayMonkey** [comment]
Hi zach,

Sorry for not responding to your last post sooner, shortly after i saw it we lost our internet connection which has only just come back on this morning. 

I'll try those -verbose methods when i get back home tonight, hopefully it will give me a clue as to whats going on (or not)

I'll report back with my findings later ...

Thanks for your help and advise so far.

Cheers
Jay

**Comment by JayMonkey** [comment]
Hi Zach,

So it looks like (as you suggested) it's nothing to do with IAGL ...

If i try to launch Retoarch from terminal with 

`"/Applications/RetroArch.app/Contents/MacOS/RetroArch"` 

it does not immediacy open with foucs ..

Like before i see that Retoarch launches but it stays in the dock (minimized) with a dot on it until i click on it with the mouse or CMD TAB to it at which point it opens full screen with focus .... very strange as its the only app i have that seems to do that. Launching any other app from terminal opens that app with focus ...

I tried uninstalling Retroarch and deleting the Retroarch folder in ~/Documents and then reinstalled it, updated everything and configured it ..(inc Fullscreen) .. but alas that did not help, Retoarch does not launch with Focus when launched from terminal.

If i launch directly from the Dock it opens with focus fine ... very strange.

I'm using the Metal version of Retoarch V1.7.7 .. is that the same as you ?

I take when you launch Retoarch on your Mac it opens maximised with focus ?

I know this is not the fault of IAGL but if you have any other ideas i'd appreciate it.
I carry on looking into the issue see if i can find any advice on the Apple forums ..

Cheers
Jay

**Comment by zach-morris** [comment]
Yes, I'm running metal too.  You may have uninstalled the app, but try deleting/backing up the config files too at:
```
/Users/yourusername/Library/Application Support/RetroArch/config/
```

I doubt it's causing the issue, but I dont think the retroarch config is deleted when you uninstall from the app directory.

**Comment by JayMonkey** [comment]
Hi Zach,

Thanks for that but it did not help .....

However I think i've got it sorted now .... 

I added Terminal to the list of allowed apps in Sys Prefs -> Security & Privacy -> Privacy 

![Screenshot 2019-05-10 at 16 11 01](https://user-images.githubusercontent.com/5662056/57537534-63bce080-733e-11e9-9b95-f5d1456ede6c.png)

Now it works as it should .... odd as like i said i could launch other Apps (EG: Kodi) from Terminal with out this but hey its working now so I'm not going to argue.

Might be worth mentioning in your MacOS specific help .. as i don't remember seeing it.

Thanks for all your help buddy, and great job with creating IAGL ... its going to make a lot of retro gamers very happy ... myself included.

Cheers
Jay

**Comment by zach-morris** [comment]
OK.  Glad you got it sorted.  I have the same settings, but honestly never remember futzing with it.  I'm guessing at some point after using terminal OSX asks "Do you want to give access to Terminal"? and I blindly agreed.

**Comment by JayMonkey** [comment]
I never got prompted by MacOS to add it ... otherwise i obviously would have.

However i've been caught out by it before with some of my own compiled AppleScripts so thought i'd give it a go and it seems to have fixed the issue.

Thanks Again
Jay
