### ISSUE TITLE
Cant start another game after leaving\quitting a game - Android ARM v7 [FireTv Gen2]

### ISSUE THREAD

**Issue by Philps** [zach-morris/plugin.program.iagl#89]
This seems to be a new behavior in 2.1

I can start any game of any supported emulator fine. When exiting the game and tryin to launch another, the Download Begins and finished but it wont start and "Launch" Button is greyed-out

Edit: this only happens when default is configurd eg.: bring up Game Information

Workaround: Change default (Click on Game) to: Download + Launch Game

**Comment by zach-morris** [comment]
I can't recreate this, but I don't have that system type to test on (works on windows and OSX).  Can you get a debug log of this problem when it occurs?

**Comment by Philps** [comment]
i think that was somehow related to the external download path, i cant replicate it anylonger after reinstall.
https://github.com/zach-morris/plugin.program.iagl/issues/36#issuecomment-493016162

can be closed
