### ISSUE TITLE
Show busy dialog when post processing files

### ISSUE THREAD

**Issue by Philps** [zach-morris/plugin.program.iagl#90]
Not sure how IO is handled for the Download implementation, however it looks like it downloads all the data but need to run a verfiy / close file / flsuh buffer at the end. 

for larger files this may take up to 30s

not sure if Android Specific. May test this on windows as well.

**Comment by zach-morris** [comment]
I'm guessing what you're seeing/waiting for is the file to be processed.  For example, a [PS1 file](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/data/dat_files/PS1_Bestof_ZachMorris.xml#L17) needs to be unarchived, placed into a folder, and then launch a cue file.  For large files, that will obviously take a while.

I'll leave this open for now, I could potentially add a 'busy' dialog somehow to the gui when this is occurring.

**Comment by Philps** [comment]
Hey Zach, that make sense. Thx. Maybe its possible to reflect this Download ready processing in place.
