### ISSUE TITLE
Feature Request: Launcher Command for external Emulator should only list supported Emulators or at least sort them alphabetically/group them

### ISSUE THREAD

**Issue by Philps** [zach-morris/plugin.program.iagl#91]
Retroarch for example list all Emulators and you can find the EmualtedSystem in ()

Eg:
PSX ( Playstation)
PicoDrive (GG|Genessis|..)
Yabuse (Saturn)

So i wonder if you could filter the list, so if i select a for a sepcific Emulator and want to set a external Launcher Command, i want a list with these specific Emulators

**Comment by zach-morris** [comment]
Without adding a separate database / database entry that says which game lists are compatible with which emulators, I don't see how to easily do this.  And even that wouldn't be all that easy since it's another database to try to create and maintain.

**Comment by Philps** [comment]
I was just thinking about parsing the list. I guess you make an external call to Retroarch? or maybe you have a list of retro arch launcher commands and just list them all .. however that list can be filtered or at least sorted

**Comment by zach-morris** [comment]
OK, I could likely sort it somehow
