### ISSUE TITLE
Beetle Saturn not listed in Launcher Command Selection Screen for External Launcher

### ISSUE THREAD

**Issue by Philps** [zach-morris/plugin.program.iagl#92]
While RetroArch has support for Beetle Saturn, its not listed in the List for External Launcher within IAGL

**Comment by zach-morris** [comment]
Beetle Saturn = [Mednafen Saturn](https://github.com/libretro/libretro-super/blob/master/dist/info/mednafen_saturn_libretro.info), which [is in the database](https://github.com/zach-morris/plugin.program.iagl/blob/main/resources/data/external_command_database.xml#L255).
