### ISSUE TITLE
Sound Choppy

### ISSUE THREAD

**Issue by 9acca9** [zach-morris/plugin.program.iagl#93]
Hi.
Thank you very much for your addon, it is very good.
But I wanted to ask a question. I'm having problems with some games, like eg. super mario world 2 yoshis island.
It turns out that the sound comes out choppy.
I configured it to work with retroarch, and the same thing happens.
What could I do?
Greetings and thanks.

ps. im using raspberry pi 2 with Libreelec (last version)

**Comment by zach-morris** [comment]
Sorry, I can't help with specific issues like this.  After the game launches, my addon has nothing to do with playing the actual game.  See [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#11--how-do-you-get-retroarch-to-do-xyz).

**Comment by 9acca9** [comment]
Ok, anyway thanks for all your work!
