### ISSUE TITLE
Feature Request: BinMerge Support

### ISSUE THREAD

**Issue by Philps** [zach-morris/plugin.program.iagl#95]
Would be great if this could be a feature in the settings. I dont know if this is cross plattform compliant

https://github.com/putnam/binmerge

**Comment by zach-morris** [comment]
Which list would benefit from this?  I can't think of a core that can't support multiple bin/cue but can support single bin/cue

**Comment by Philps** [comment]
I was thinkin about Yabuse. https://github.com/libretro/yabause/issues/56 
But probably this is being fixed in the near future as Beetle Saturn does support it

**Comment by zach-morris** [comment]
This actually seems doable, so I'll leave it open and see if it's merged into the core.  I think the game list for Saturn should be updated as well to a more up to date / complete archive.

**Comment by Philps** [comment]
with the latest yabasinshero core ( yabuse ), i have no issue with any game list for Saturn. think this can be closed
