### ISSUE TITLE
Change options in Emulators

### ISSUE THREAD

**Issue by 9acca9** [zach-morris/plugin.program.iagl#97]
Hi.
Sorry if this is not good here...
Well i want to change some options in emulators (like save states of a game, "quick save", and not just where i stop playing). I think i can do this in options in emulators but i dont know how, or where access to this.
If i put select  for options i go to a video, audio, controls, advanced... but none of that option give me what i want. Can you tell me how access to that?
Thanks.

**Comment by zach-morris** [comment]
If you're using Retroplayer (Kodi only), then all the options you have available are in the settings menu after you start a game.  Quick save and the like are not yet implemented in Kodi Retroplayer.  Requests and discussions about implementing features in Kodi is in the [Kodi forums](https://forum.kodi.tv/forumdisplay.php?fid=292).

If you're using external launching / Retroarch, then all those options are available in the quick menu after you start a game.  Info on all the available options are in the [libretro wiki](https://docs.libretro.com/).
