### ISSUE TITLE
Feature Request: Make a seperate setting (additional to close/pause kodi) where you can enter a path to a own script

### ISSUE THREAD

**Issue by Cyber1000** [zach-morris/plugin.program.iagl#99]
Perhaps it's my setup of kodi (default rasbpian, kodi is started as systemctl daemon which respawns on crash), whatever, applaunch.sh didn't work the way it was supposed for me.

It would be nice to configure a own script which is called on start of retroarch (similar to applaunch.sh for "stop kodi")

**Comment by zach-morris** [comment]
You can do that already with manual command entry.  See [here](https://github.com/zach-morris/plugin.program.iagl/wiki/5.--FAQ#3--i-want-to-use-emulator-xxx-instead).  You should be able to enter any command line command (pointing to a shell script if necessary)
